!include <..\..\..\build-msvc\Makefile.config>

PROJECT = at_1_phase

OBJS=\
	$(OUTDIR)\$(PROJECT).obj \
	$(OUTDIR)\$(PROJECT)_top.obj \
	$(OUTDIR)\initiator_top.obj \
	\
	$(OUTDIR)\at_target_1_phase.obj \
	$(OUTDIR)\memory.obj \
	$(OUTDIR)\report.obj \
	$(OUTDIR)\select_initiator.obj \
	$(OUTDIR)\traffic_generator.obj

!include <..\..\..\build-msvc\Makefile.rules>
