TLM 2: tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list Class Reference
tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list Class Reference
Public Member Functions
delta_list ()
void insert (const PAYLOAD &p)
PAYLOAD & get ()
bool next ()
void reset ()
Public Attributes
unsigned int size
Private Attributes
std::vector< PAYLOAD > entries
unsigned int out
Detailed Description
template<typename OWNER, typename TYPES = tlm::tlm_base_protocol_types>
class tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::delta_list
Definition at line 154 of file peq_with_cb_and_phase.h.
Constructor & Destructor Documentation
template<typename OWNER , typename TYPES = tlm::tlm_base_protocol_types> tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::delta_list () [inline]
Definition at line 156 of file peq_with_cb_and_phase.h.
References tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::entries, and tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::reset().
Member Function Documentation
template<typename OWNER , typename TYPES = tlm::tlm_base_protocol_types> PAYLOAD& tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::get () [inline]
Definition at line 168 of file peq_with_cb_and_phase.h.
References tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::entries, and tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::out.
Referenced by tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::fec().
template<typename OWNER , typename TYPES = tlm::tlm_base_protocol_types> void tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::insert (const PAYLOAD & p) [inline]
Definition at line 161 of file peq_with_cb_and_phase.h.
References tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::entries, and tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::size.
Referenced by tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::notify().
template<typename OWNER , typename TYPES = tlm::tlm_base_protocol_types> bool tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::next () [inline]
Definition at line 172 of file peq_with_cb_and_phase.h.
References tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::out, and tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::size.
Referenced by tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::fec().
template<typename OWNER , typename TYPES = tlm::tlm_base_protocol_types> void tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::reset () [inline]
Definition at line 176 of file peq_with_cb_and_phase.h.
References tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::out, and tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::size.
Referenced by tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::cancel_all(), tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::delta_list(), and tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::fec().
Member Data Documentation
template<typename OWNER , typename TYPES = tlm::tlm_base_protocol_types> std::vector<PAYLOAD> tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::entries [private]
Definition at line 183 of file peq_with_cb_and_phase.h.
Referenced by tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::delta_list(), tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::get(), and tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::insert().
template<typename OWNER , typename TYPES = tlm::tlm_base_protocol_types> unsigned int tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::out [private]
Definition at line 184 of file peq_with_cb_and_phase.h.
Referenced by tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::get(), tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::next(), and tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::reset().
template<typename OWNER , typename TYPES = tlm::tlm_base_protocol_types> unsigned int tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::size
Definition at line 181 of file peq_with_cb_and_phase.h.
Referenced by tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::fec(), tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::insert(), tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::next(), and tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::reset().
The documentation for this class was generated from the following file:
include/tlm/tlm_utils/peq_with_cb_and_phase.h