TLM 2: tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL > Class Template Reference
tlm::tlm_base_target_socket
tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL > Class Template Reference
#include <tlm_target_socket.h>
Public Types
typedef FW_IF fw_interface_type
typedef BW_IF bw_interface_type
typedef
sc_core::sc_port
< bw_interface_type,
N, POL > port_type
typedef
sc_core::sc_export
< fw_interface_type > export_type
typedef
tlm_base_initiator_socket_b
< BUSWIDTH,
fw_interface_type,
bw_interface_type > base_initiator_socket_type
typedef
tlm_base_initiator_socket
< BUSWIDTH,
fw_interface_type,
bw_interface_type,
N,POL > initiator_socket_type
typedef
tlm_base_target_socket_b
< BUSWIDTH,
fw_interface_type,
bw_interface_type > base_type
Public Member Functions
tlm_base_target_socket ()
tlm_base_target_socket (const char *name)
unsigned int get_bus_width () const
void bind (base_initiator_socket_type &s)
void operator() (base_initiator_socket_type &s)
void bind (base_type &s)
void operator() (base_type &s)
void bind (fw_interface_type &ifs)
void operator() (fw_interface_type &s)
int size () const
bw_interface_type * operator-> ()
bw_interface_type * operator[] (int i)
virtual
sc_core::sc_port_b
< BW_IF > & get_base_port ()
virtual FW_IF & get_base_interface ()
virtual
sc_core::sc_export
< FW_IF > & get_base_export ()
Protected Attributes
port_type m_port
Friends
class tlm_base_initiator_socket
Detailed Description
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND>
class tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >
Definition at line 61 of file tlm_target_socket.h.
Member Typedef Documentation
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef FW_IF tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >::fw_interface_type
Reimplemented in tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >, tlm_utils::passthrough_target_socket_tagged< MODULE, BUSWIDTH, TYPES >, tlm_utils::simple_target_socket< MODULE, BUSWIDTH, TYPES >, and tlm_utils::simple_target_socket_tagged< MODULE, BUSWIDTH, TYPES >.
Definition at line 65 of file tlm_target_socket.h.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef BW_IF tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >::bw_interface_type
Reimplemented in tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >, tlm_utils::passthrough_target_socket_tagged< MODULE, BUSWIDTH, TYPES >, tlm_utils::simple_target_socket< MODULE, BUSWIDTH, TYPES >, and tlm_utils::simple_target_socket_tagged< MODULE, BUSWIDTH, TYPES >.
Definition at line 66 of file tlm_target_socket.h.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef sc_core::sc_port<bw_interface_type, N , POL > tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >::port_type
Definition at line 71 of file tlm_target_socket.h.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef sc_core::sc_export<fw_interface_type> tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >::export_type
Definition at line 73 of file tlm_target_socket.h.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef tlm_base_initiator_socket_b<BUSWIDTH, fw_interface_type, bw_interface_type> tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >::base_initiator_socket_type
Reimplemented in tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >.
Definition at line 76 of file tlm_target_socket.h.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef tlm_base_initiator_socket<BUSWIDTH, fw_interface_type, bw_interface_type, N ,POL > tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >::initiator_socket_type
Reimplemented in tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >.
Definition at line 85 of file tlm_target_socket.h.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> typedef tlm_base_target_socket_b<BUSWIDTH, fw_interface_type, bw_interface_type> tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >::base_type
Reimplemented in tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >, tlm_utils::multi_target_base< BUSWIDTH, TYPES, N, POL >, tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >, tlm_utils::passthrough_target_socket_tagged< MODULE, BUSWIDTH, TYPES >, tlm_utils::simple_target_socket< MODULE, BUSWIDTH, TYPES >, and tlm_utils::simple_target_socket_tagged< MODULE, BUSWIDTH, TYPES >.
Definition at line 90 of file tlm_target_socket.h.
Constructor & Destructor Documentation
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >::tlm_base_target_socket () [inline]
Definition at line 101 of file tlm_target_socket.h.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >::tlm_base_target_socket (const char * name) [inline, explicit]
Definition at line 107 of file tlm_target_socket.h.
Member Function Documentation
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> unsigned int tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >::get_bus_width () const [inline]
Definition at line 113 of file tlm_target_socket.h.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >::bind (base_initiator_socket_type & s) [inline]
Definition at line 125 of file tlm_target_socket.h.
Referenced by tlm::tlm_base_target_socket< BUSWIDTH, tlm::tlm_fw_transport_if< TYPES >, tlm::tlm_bw_transport_if< TYPES >, 1, sc_core::SC_ONE_OR_MORE_BOUND >::operator()(), tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::passthrough_target_socket(), tlm_utils::passthrough_target_socket_tagged< MODULE, BUSWIDTH, TYPES >::passthrough_target_socket_tagged(), tlm_utils::simple_target_socket< MODULE, BUSWIDTH, TYPES >::simple_target_socket(), and tlm_utils::simple_target_socket_tagged< MODULE, BUSWIDTH, TYPES >::simple_target_socket_tagged().
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >::operator() (base_initiator_socket_type & s) [inline]
Definition at line 133 of file tlm_target_socket.h.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >::bind (base_type & s) [inline]
Reimplemented in tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >.
Definition at line 142 of file tlm_target_socket.h.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >::operator() (base_type & s) [inline]
Reimplemented in tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >.
Definition at line 150 of file tlm_target_socket.h.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >::bind (fw_interface_type & ifs) [inline]
Definition at line 159 of file tlm_target_socket.h.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> void tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >::operator() (fw_interface_type & s) [inline]
Definition at line 164 of file tlm_target_socket.h.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> int tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >::size () const [inline]
Definition at line 172 of file tlm_target_socket.h.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> bw_interface_type* tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >::operator-> () [inline]
Reimplemented in tlm_utils::simple_target_socket< MODULE, BUSWIDTH, TYPES >, and tlm_utils::simple_target_socket_tagged< MODULE, BUSWIDTH, TYPES >.
Definition at line 180 of file tlm_target_socket.h.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> bw_interface_type* tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >::operator[] (int i) [inline]
Reimplemented in tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >.
Definition at line 188 of file tlm_target_socket.h.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> virtual sc_core::sc_port_b<BW_IF>& tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >::get_base_port () [inline, virtual]
Implements tlm::tlm_base_target_socket_b< BUSWIDTH, FW_IF, BW_IF >.
Definition at line 194 of file tlm_target_socket.h.
Referenced by tlm::tlm_base_target_socket< BUSWIDTH, tlm::tlm_fw_transport_if< TYPES >, tlm::tlm_bw_transport_if< TYPES >, 1, sc_core::SC_ONE_OR_MORE_BOUND >::bind().
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> virtual FW_IF& tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >::get_base_interface () [inline, virtual]
Implements tlm::tlm_base_target_socket_b< BUSWIDTH, FW_IF, BW_IF >.
Reimplemented in tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >.
Definition at line 195 of file tlm_target_socket.h.
Referenced by tlm::tlm_base_target_socket< BUSWIDTH, tlm::tlm_fw_transport_if< TYPES >, tlm::tlm_bw_transport_if< TYPES >, 1, sc_core::SC_ONE_OR_MORE_BOUND >::bind().
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> virtual sc_core::sc_export<FW_IF>& tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >::get_base_export () [inline, virtual]
Implements tlm::tlm_base_target_socket_b< BUSWIDTH, FW_IF, BW_IF >.
Reimplemented in tlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >.
Definition at line 196 of file tlm_target_socket.h.
Referenced by tlm::tlm_base_target_socket< BUSWIDTH, tlm::tlm_fw_transport_if< TYPES >, tlm::tlm_bw_transport_if< TYPES >, 1, sc_core::SC_ONE_OR_MORE_BOUND >::bind().
Friends And Related Function Documentation
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> friend class tlm_base_initiator_socket [friend]
Definition at line 98 of file tlm_target_socket.h.
Member Data Documentation
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_transport_if<>, typename BW_IF = tlm_bw_transport_if<>, int N = 1, sc_core::sc_port_policy POL = sc_core::SC_ONE_OR_MORE_BOUND> port_type tlm::tlm_base_target_socket< BUSWIDTH, FW_IF, BW_IF, N, POL >::m_port [protected]
Definition at line 199 of file tlm_target_socket.h.
Referenced by tlm::tlm_base_target_socket< BUSWIDTH, tlm::tlm_fw_transport_if< TYPES >, tlm::tlm_bw_transport_if< TYPES >, 1, sc_core::SC_ONE_OR_MORE_BOUND >::get_base_port(), tlm::tlm_base_target_socket< BUSWIDTH, tlm::tlm_fw_transport_if< TYPES >, tlm::tlm_bw_transport_if< TYPES >, 1, sc_core::SC_ONE_OR_MORE_BOUND >::operator->(), tlm::tlm_base_target_socket< BUSWIDTH, tlm::tlm_fw_transport_if< TYPES >, tlm::tlm_bw_transport_if< TYPES >, 1, sc_core::SC_ONE_OR_MORE_BOUND >::operator[](), and tlm::tlm_base_target_socket< BUSWIDTH, tlm::tlm_fw_transport_if< TYPES >, tlm::tlm_bw_transport_if< TYPES >, 1, sc_core::SC_ONE_OR_MORE_BOUND >::size().
The documentation for this class was generated from the following file:
C:/ESLX/projects/TLMWG/tlm2/include/tlm/tlm_h/tlm_trans/tlm_sockets/tlm_target_socket.h