TLM 2: tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES > Class Template Reference
tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES > Class Template Reference
#include <passthrough_target_socket.h>
Inherits tlm_target_socket< BUSWIDTH, TYPES >.
Classes
class process
Public Types
typedef TYPES::tlm_payload_type transaction_type
typedef TYPES::tlm_phase_type phase_type
typedef tlm::tlm_sync_enum sync_enum_type
typedef
tlm::tlm_fw_transport_if
< TYPES > fw_interface_type
typedef
tlm::tlm_bw_transport_if
< TYPES > bw_interface_type
typedef tlm::tlm_target_socket
< BUSWIDTH, TYPES > base_type
Public Member Functions
passthrough_target_socket ()
passthrough_target_socket (const char *n)
void register_nb_transport_fw (MODULE *mod, sync_enum_type(MODULE::*cb)(transaction_type &, phase_type &, sc_core::sc_time &))
void register_b_transport (MODULE *mod, void(MODULE::*cb)(transaction_type &, sc_core::sc_time &))
void register_transport_dbg (MODULE *mod, unsigned int(MODULE::*cb)(transaction_type &))
void register_get_direct_mem_ptr (MODULE *mod, bool(MODULE::*cb)(transaction_type &, tlm::tlm_dmi &))
Private Attributes
process m_process
Detailed Description
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types>
class tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >
Definition at line 29 of file passthrough_target_socket.h.
Member Typedef Documentation
template<typename MODULE , unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types> typedef tlm::tlm_target_socket<BUSWIDTH, TYPES> tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::base_type
Reimplemented from tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, 1,sc_core::SC_ONE_OR_MORE_BOUND >.
Definition at line 38 of file passthrough_target_socket.h.
template<typename MODULE , unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types> typedef tlm::tlm_bw_transport_if<TYPES> tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::bw_interface_type
Reimplemented from tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, 1,sc_core::SC_ONE_OR_MORE_BOUND >.
Definition at line 37 of file passthrough_target_socket.h.
template<typename MODULE , unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types> typedef tlm::tlm_fw_transport_if<TYPES> tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::fw_interface_type
Reimplemented from tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, 1,sc_core::SC_ONE_OR_MORE_BOUND >.
Definition at line 36 of file passthrough_target_socket.h.
template<typename MODULE , unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types> typedef TYPES::tlm_phase_type tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::phase_type
Definition at line 34 of file passthrough_target_socket.h.
template<typename MODULE , unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types> typedef tlm::tlm_sync_enum tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::sync_enum_type
Definition at line 35 of file passthrough_target_socket.h.
template<typename MODULE , unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types> typedef TYPES::tlm_payload_type tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::transaction_type
Definition at line 33 of file passthrough_target_socket.h.
Constructor & Destructor Documentation
template<typename MODULE , unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types> tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::passthrough_target_socket () [inline]
Definition at line 41 of file passthrough_target_socket.h.
References tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, 1,sc_core::SC_ONE_OR_MORE_BOUND >::bind(), and tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::m_process.
template<typename MODULE , unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types> tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::passthrough_target_socket (const char * n) [inline, explicit]
Definition at line 48 of file passthrough_target_socket.h.
References tlm::tlm_base_target_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, 1,sc_core::SC_ONE_OR_MORE_BOUND >::bind(), and tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::m_process.
Member Function Documentation
template<typename MODULE , unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types> void tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::register_b_transport (MODULE * mod, void(MODULE::*)(transaction_type &, sc_core::sc_time &) cb) [inline]
Definition at line 64 of file passthrough_target_socket.h.
References tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::m_process, and tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::passthrough_target_socket::process::set_b_transport_ptr().
template<typename MODULE , unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types> void tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::register_get_direct_mem_ptr (MODULE * mod, bool(MODULE::*)(transaction_type &, tlm::tlm_dmi &) cb) [inline]
Definition at line 77 of file passthrough_target_socket.h.
References tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::m_process, and tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::passthrough_target_socket::process::set_get_direct_mem_ptr().
template<typename MODULE , unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types> void tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::register_nb_transport_fw (MODULE * mod, sync_enum_type(MODULE::*)(transaction_type &, phase_type &, sc_core::sc_time &) cb) [inline]
Definition at line 56 of file passthrough_target_socket.h.
References tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::m_process, and tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::passthrough_target_socket::process::set_nb_transport_ptr().
template<typename MODULE , unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types> void tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::register_transport_dbg (MODULE * mod, unsigned int(MODULE::*)(transaction_type &) cb) [inline]
Definition at line 71 of file passthrough_target_socket.h.
References tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::m_process, and tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::passthrough_target_socket::process::set_transport_dbg_ptr().
Member Data Documentation
template<typename MODULE , unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types> process tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::m_process [private]
Definition at line 231 of file passthrough_target_socket.h.
Referenced by tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::passthrough_target_socket(), tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::register_b_transport(), tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::register_get_direct_mem_ptr(), tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::register_nb_transport_fw(), and tlm_utils::passthrough_target_socket< MODULE, BUSWIDTH, TYPES >::register_transport_dbg().
The documentation for this class was generated from the following file:
include/tlm/tlm_utils/passthrough_target_socket.h