TLM 2: tlm::tlm_buffer_pool Class Reference
tlm::tlm_buffer_pool
tlm::tlm_buffer_pool Class Reference
#include <tlm_endian_conv.h>
Public Member Functions
tlm_buffer_pool ()
uchar * get_a_buffer (int size)
void return_buffer (uchar *p)
int get_pool_size ()
int get_buffer_size ()
Private Attributes
int max_buffer_size
uchar * pool_head
Detailed Description
Definition at line 153 of file tlm_endian_conv.h.
Constructor & Destructor Documentation
tlm::tlm_buffer_pool::tlm_buffer_pool () [inline]
Definition at line 158 of file tlm_endian_conv.h.
Member Function Documentation
uchar* tlm::tlm_buffer_pool::get_a_buffer (int size) [inline]
Definition at line 160 of file tlm_endian_conv.h.
References max_buffer_size, pool_head, and uchar.
Referenced by tlm::tlm_to_hostendian_aligned(), tlm::tlm_to_hostendian_generic(), and tlm::tlm_to_hostendian_word().
void tlm::tlm_buffer_pool::return_buffer (uchar * p) [inline]
Definition at line 185 of file tlm_endian_conv.h.
References max_buffer_size, pool_head, and uchar.
Referenced by tlm::tlm_from_hostendian_aligned(), tlm::tlm_from_hostendian_generic(), and tlm::tlm_from_hostendian_word().
int tlm::tlm_buffer_pool::get_pool_size () [inline]
Definition at line 198 of file tlm_endian_conv.h.
References pool_head, and uchar.
int tlm::tlm_buffer_pool::get_buffer_size () [inline]
Definition at line 204 of file tlm_endian_conv.h.
References max_buffer_size.
Member Data Documentation
int tlm::tlm_buffer_pool::max_buffer_size [private]
Definition at line 154 of file tlm_endian_conv.h.
Referenced by get_a_buffer(), get_buffer_size(), and return_buffer().
uchar* tlm::tlm_buffer_pool::pool_head [private]
Definition at line 155 of file tlm_endian_conv.h.
Referenced by get_a_buffer(), get_pool_size(), and return_buffer().
The documentation for this class was generated from the following file:
C:/ESLX/projects/TLMWG/tlm2/include/tlm/tlm_h/tlm_trans/tlm_generic_payload/tlm_endian_conv.h