TLM 2: tlm_utils::peq_with_cb_and_phase< OWNER, TYPES > Class Template Reference
tlm_utils::peq_with_cb_and_phase< OWNER, TYPES > Class Template Reference
#include <peq_with_cb_and_phase.h>
Classes
class delta_list
Public Member Functions
peq_with_cb_and_phase (OWNER *_owner, cb _cb)
peq_with_cb_and_phase (const char *_name, OWNER *_owner, cb _cb)
~peq_with_cb_and_phase ()
void notify (tlm_payload_type &t, const tlm_phase_type &p, const sc_core::sc_time &when)
void notify (tlm_payload_type &t, const tlm_phase_type &p)
void cancel_all ()
Private Types
typedef TYPES::tlm_payload_type tlm_payload_type
typedef TYPES::tlm_phase_type tlm_phase_type
typedef std::pair
< tlm_payload_type
*, tlm_phase_type > PAYLOAD
typedef void(OWNER::* cb)(tlm_payload_type &, const tlm_phase_type &)
Private Member Functions
void fec ()
Private Attributes
OWNER * m_owner
cb m_cb
time_ordered_list< PAYLOAD > m_ppq
delta_list m_uneven_delta
delta_list m_even_delta
delta_list m_immediate_yield
sc_core::sc_event m_e
Detailed Description
template<typename OWNER, typename TYPES = tlm::tlm_base_protocol_types>
class tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >
An event queue that can contain any number of pending notifications. Each notification have an associate payload.
Definition at line 145 of file peq_with_cb_and_phase.h.
Member Typedef Documentation
template<typename OWNER , typename TYPES = tlm::tlm_base_protocol_types> typedef void(OWNER::* tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::cb)(tlm_payload_type &, const tlm_phase_type &) [private]
template<typename OWNER , typename TYPES = tlm::tlm_base_protocol_types> typedef std::pair<tlm_payload_type*, tlm_phase_type> tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::PAYLOAD [private]
Definition at line 151 of file peq_with_cb_and_phase.h.
template<typename OWNER , typename TYPES = tlm::tlm_base_protocol_types> typedef TYPES::tlm_payload_type tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::tlm_payload_type [private]
Definition at line 149 of file peq_with_cb_and_phase.h.
template<typename OWNER , typename TYPES = tlm::tlm_base_protocol_types> typedef TYPES::tlm_phase_type tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::tlm_phase_type [private]
Definition at line 150 of file peq_with_cb_and_phase.h.
Constructor & Destructor Documentation
template<typename OWNER , typename TYPES = tlm::tlm_base_protocol_types> tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase (OWNER * _owner, cb _cb) [inline]
Definition at line 189 of file peq_with_cb_and_phase.h.
References tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::fec(), and tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::m_e.
template<typename OWNER , typename TYPES = tlm::tlm_base_protocol_types> tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase (const char * _name, OWNER * _owner, cb _cb) [inline]
Definition at line 202 of file peq_with_cb_and_phase.h.
References tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::fec(), and tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::m_e.
template<typename OWNER , typename TYPES = tlm::tlm_base_protocol_types> tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::~peq_with_cb_and_phase () [inline]
Definition at line 215 of file peq_with_cb_and_phase.h.
Member Function Documentation
template<typename OWNER , typename TYPES = tlm::tlm_base_protocol_types> void tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::cancel_all () [inline]
Definition at line 238 of file peq_with_cb_and_phase.h.
References tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::m_e, tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::m_even_delta, tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::m_immediate_yield, tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::m_ppq, tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::m_uneven_delta, and tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::reset().
template<typename OWNER , typename TYPES = tlm::tlm_base_protocol_types> void tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::fec () [inline, private]
Definition at line 248 of file peq_with_cb_and_phase.h.
References tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::get(), tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::m_cb, tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::m_e, tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::m_even_delta, tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::m_immediate_yield, tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::m_owner, tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::m_ppq, tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::m_uneven_delta, tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::next(), tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::reset(), and tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::size.
Referenced by tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase().
template<typename OWNER , typename TYPES = tlm::tlm_base_protocol_types> void tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::notify (tlm_payload_type & t, const tlm_phase_type & p) [inline]
Definition at line 232 of file peq_with_cb_and_phase.h.
References tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::insert(), tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::m_e, and tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::m_immediate_yield.
template<typename OWNER , typename TYPES = tlm::tlm_base_protocol_types> void tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::notify (tlm_payload_type & t, const tlm_phase_type & p, const sc_core::sc_time & when) [inline]
Definition at line 217 of file peq_with_cb_and_phase.h.
References tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase::delta_list::insert(), tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::m_e, tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::m_even_delta, tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::m_ppq, and tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::m_uneven_delta.
Member Data Documentation
template<typename OWNER , typename TYPES = tlm::tlm_base_protocol_types> cb tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::m_cb [private]
Definition at line 283 of file peq_with_cb_and_phase.h.
Referenced by tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::fec().
template<typename OWNER , typename TYPES = tlm::tlm_base_protocol_types> sc_core::sc_event tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::m_e [private]
Definition at line 290 of file peq_with_cb_and_phase.h.
Referenced by tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::cancel_all(), tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::fec(), tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::notify(), and tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::peq_with_cb_and_phase().
template<typename OWNER , typename TYPES = tlm::tlm_base_protocol_types> delta_list tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::m_even_delta [private]
Definition at line 287 of file peq_with_cb_and_phase.h.
Referenced by tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::cancel_all(), tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::fec(), and tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::notify().
template<typename OWNER , typename TYPES = tlm::tlm_base_protocol_types> delta_list tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::m_immediate_yield [private]
Definition at line 288 of file peq_with_cb_and_phase.h.
Referenced by tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::cancel_all(), tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::fec(), and tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::notify().
template<typename OWNER , typename TYPES = tlm::tlm_base_protocol_types> OWNER* tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::m_owner [private]
Definition at line 282 of file peq_with_cb_and_phase.h.
Referenced by tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::fec().
template<typename OWNER , typename TYPES = tlm::tlm_base_protocol_types> time_ordered_list<PAYLOAD> tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::m_ppq [private]
Definition at line 285 of file peq_with_cb_and_phase.h.
Referenced by tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::cancel_all(), tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::fec(), and tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::notify().
template<typename OWNER , typename TYPES = tlm::tlm_base_protocol_types> delta_list tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::m_uneven_delta [private]
Definition at line 286 of file peq_with_cb_and_phase.h.
Referenced by tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::cancel_all(), tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::fec(), and tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::notify().
The documentation for this class was generated from the following file:
include/tlm/tlm_utils/peq_with_cb_and_phase.h