TLM 2: tlm::tlm_annotated_fifo< T > Class Template Reference
tlm::tlm_annotated_fifo
tlm::tlm_annotated_fifo< T > Class Template Reference
#include <tlm_annotated_fifo.h>
Public Member Functions
tlm_annotated_fifo (sc_core::sc_module_name nm, int size=1)
tlm_annotated_fifo (int size=1)
bool nb_can_put (tlm_tag< T > *t=0) const
bool nb_can_get (tlm_tag< T > *t=0) const
bool nb_can_peek (tlm_tag< T > *t=0) const
virtual bool nb_can_put (const sc_core::sc_time &time, tlm_tag< T > *t=0) const
virtual bool nb_can_get (const sc_core::sc_time &time, tlm_tag< T > *t=0) const
const sc_core::sc_event & ok_to_put (tlm_tag< T > *t=0) const
const sc_core::sc_event & ok_to_get (tlm_tag< T > *t=0) const
const sc_core::sc_event & ok_to_peek (tlm_tag< T > *t=0) const
bool nb_put (const T &t)
bool nb_get (T &t)
bool nb_peek (T &t) const
bool nb_put (const T &transaction, const sc_core::sc_time &time)
virtual bool nb_get (T &transaction, const sc_core::sc_time &time)
void put (const T &t)
T get (tlm_tag< T > *t=0)
T peek (tlm_tag< T > *t=0) const
int size ()
Protected Attributes
tlm_internal_annotated_fifo
< T > m_fifo
tlm_peq< T > m_put_peq
tlm_peq< tlm_tag< T > * > m_get_peq
Private Attributes
int m_size
Detailed Description
template<typename T>
class tlm::tlm_annotated_fifo< T >
Definition at line 55 of file tlm_annotated_fifo.h.
Constructor & Destructor Documentation
template<typename T> tlm::tlm_annotated_fifo< T >::tlm_annotated_fifo (sc_core::sc_module_name nm, int size = 1) [inline]
Definition at line 62 of file tlm_annotated_fifo.h.
References tlm::tlm_annotated_fifo< T >::m_fifo, tlm::tlm_annotated_fifo< T >::m_get_peq, and tlm::tlm_annotated_fifo< T >::m_put_peq.
template<typename T> tlm::tlm_annotated_fifo< T >::tlm_annotated_fifo (int size = 1) [inline]
Definition at line 74 of file tlm_annotated_fifo.h.
References tlm::tlm_annotated_fifo< T >::m_fifo, tlm::tlm_annotated_fifo< T >::m_get_peq, and tlm::tlm_annotated_fifo< T >::m_put_peq.
Member Function Documentation
template<typename T> bool tlm::tlm_annotated_fifo< T >::nb_can_put (tlm_tag< T > * t = 0) const [inline, virtual]
Implements tlm::tlm_nonblocking_put_if< T >.
Definition at line 87 of file tlm_annotated_fifo.h.
References tlm::tlm_annotated_fifo< T >::m_fifo, tlm::tlm_annotated_fifo< T >::m_get_peq, and tlm::tlm_annotated_fifo< T >::m_put_peq.
Referenced by tlm::tlm_annotated_fifo< T >::nb_can_put(), and tlm::tlm_annotated_fifo< T >::nb_put().
template<typename T> bool tlm::tlm_annotated_fifo< T >::nb_can_get (tlm_tag< T > * t = 0) const [inline, virtual]
Implements tlm::tlm_nonblocking_get_if< T >.
Definition at line 91 of file tlm_annotated_fifo.h.
References tlm::tlm_annotated_fifo< T >::m_fifo.
Referenced by tlm::tlm_annotated_fifo< T >::nb_can_get(), and tlm::tlm_annotated_fifo< T >::nb_get().
template<typename T> bool tlm::tlm_annotated_fifo< T >::nb_can_peek (tlm_tag< T > * t = 0) const [inline, virtual]
Implements tlm::tlm_nonblocking_peek_if< T >.
Definition at line 95 of file tlm_annotated_fifo.h.
References tlm::tlm_annotated_fifo< T >::m_fifo.
template<typename T> virtual bool tlm::tlm_annotated_fifo< T >::nb_can_put (const sc_core::sc_time & time, tlm_tag< T > * t = 0) const [inline, virtual]
Implements tlm::tlm_annotated_nonblocking_put_if< T >.
Definition at line 110 of file tlm_annotated_fifo.h.
References tlm::tlm_annotated_fifo< T >::nb_can_put().
template<typename T> virtual bool tlm::tlm_annotated_fifo< T >::nb_can_get (const sc_core::sc_time & time, tlm_tag< T > * t = 0) const [inline, virtual]
Implements tlm::tlm_annotated_nonblocking_get_if< T >.
Definition at line 114 of file tlm_annotated_fifo.h.
References tlm::tlm_annotated_fifo< T >::nb_can_get().
template<typename T> const sc_core::sc_event& tlm::tlm_annotated_fifo< T >::ok_to_put (tlm_tag< T > * t = 0) const [inline, virtual]
Implements tlm::tlm_nonblocking_put_if< T >.
Definition at line 120 of file tlm_annotated_fifo.h.
References tlm::tlm_annotated_fifo< T >::m_fifo.
Referenced by tlm::tlm_annotated_fifo< T >::put().
template<typename T> const sc_core::sc_event& tlm::tlm_annotated_fifo< T >::ok_to_get (tlm_tag< T > * t = 0) const [inline, virtual]
Implements tlm::tlm_nonblocking_get_if< T >.
Definition at line 124 of file tlm_annotated_fifo.h.
References tlm::tlm_annotated_fifo< T >::m_fifo.
Referenced by tlm::tlm_annotated_fifo< T >::get().
template<typename T> const sc_core::sc_event& tlm::tlm_annotated_fifo< T >::ok_to_peek (tlm_tag< T > * t = 0) const [inline, virtual]
Implements tlm::tlm_nonblocking_peek_if< T >.
Definition at line 128 of file tlm_annotated_fifo.h.
References tlm::tlm_annotated_fifo< T >::m_fifo.
template<typename T> bool tlm::tlm_annotated_fifo< T >::nb_put (const T & t) [inline, virtual]
Implements tlm::tlm_nonblocking_put_if< T >.
Definition at line 134 of file tlm_annotated_fifo.h.
References tlm::tlm_annotated_fifo< T >::m_fifo, and tlm::tlm_annotated_fifo< T >::nb_can_put().
Referenced by tlm::tlm_annotated_fifo< T >::put().
template<typename T> bool tlm::tlm_annotated_fifo< T >::nb_get (T & t) [inline, virtual]
Implements tlm::tlm_nonblocking_get_if< T >.
Definition at line 146 of file tlm_annotated_fifo.h.
References tlm::tlm_annotated_fifo< T >::m_fifo, and tlm::tlm_annotated_fifo< T >::nb_can_get().
Referenced by tlm::tlm_annotated_fifo< T >::get().
template<typename T> bool tlm::tlm_annotated_fifo< T >::nb_peek (T & t) const [inline, virtual]
Implements tlm::tlm_nonblocking_peek_if< T >.
Definition at line 158 of file tlm_annotated_fifo.h.
References tlm::tlm_annotated_fifo< T >::m_fifo.
template<typename T> bool tlm::tlm_annotated_fifo< T >::nb_put (const T & transaction, const sc_core::sc_time & time) [inline, virtual]
Implements tlm::tlm_annotated_nonblocking_put_if< T >.
Definition at line 165 of file tlm_annotated_fifo.h.
References tlm::tlm_annotated_fifo< T >::m_put_peq, and tlm::tlm_annotated_fifo< T >::nb_can_put().
template<typename T> virtual bool tlm::tlm_annotated_fifo< T >::nb_get (T & transaction, const sc_core::sc_time & time) [inline, virtual]
Implements tlm::tlm_annotated_nonblocking_get_if< T >.
Definition at line 176 of file tlm_annotated_fifo.h.
References tlm::tlm_annotated_fifo< T >::m_fifo, and tlm::tlm_annotated_fifo< T >::m_get_peq.
template<typename T> void tlm::tlm_annotated_fifo< T >::put (const T & t) [inline, virtual]
Implements tlm::tlm_blocking_put_if< T >.
Definition at line 190 of file tlm_annotated_fifo.h.
References tlm::tlm_annotated_fifo< T >::nb_put(), and tlm::tlm_annotated_fifo< T >::ok_to_put().
template<typename T> T tlm::tlm_annotated_fifo< T >::get (tlm_tag< T > * t = 0) [inline, virtual]
Implements tlm::tlm_blocking_get_if< T >.
Definition at line 196 of file tlm_annotated_fifo.h.
References tlm::tlm_annotated_fifo< T >::nb_get(), and tlm::tlm_annotated_fifo< T >::ok_to_get().
template<typename T> T tlm::tlm_annotated_fifo< T >::peek (tlm_tag< T > * t = 0) const [inline, virtual]
Implements tlm::tlm_blocking_peek_if< T >.
Definition at line 207 of file tlm_annotated_fifo.h.
References tlm::tlm_annotated_fifo< T >::m_fifo.
template<typename T> int tlm::tlm_annotated_fifo< T >::size () [inline]
Definition at line 211 of file tlm_annotated_fifo.h.
References tlm::tlm_annotated_fifo< T >::m_size.
Member Data Documentation
template<typename T> int tlm::tlm_annotated_fifo< T >::m_size [private]
Definition at line 214 of file tlm_annotated_fifo.h.
Referenced by tlm::tlm_annotated_fifo< T >::size().
template<typename T> tlm_internal_annotated_fifo<T> tlm::tlm_annotated_fifo< T >::m_fifo [protected]
Definition at line 218 of file tlm_annotated_fifo.h.
Referenced by tlm::tlm_annotated_fifo< T >::nb_can_get(), tlm::tlm_annotated_fifo< T >::nb_can_peek(), tlm::tlm_annotated_fifo< T >::nb_can_put(), tlm::tlm_annotated_fifo< T >::nb_get(), tlm::tlm_annotated_fifo< T >::nb_peek(), tlm::tlm_annotated_fifo< T >::nb_put(), tlm::tlm_annotated_fifo< T >::ok_to_get(), tlm::tlm_annotated_fifo< T >::ok_to_peek(), tlm::tlm_annotated_fifo< T >::ok_to_put(), tlm::tlm_annotated_fifo< T >::peek(), and tlm::tlm_annotated_fifo< T >::tlm_annotated_fifo().
template<typename T> tlm_peq<T> tlm::tlm_annotated_fifo< T >::m_put_peq [protected]
Definition at line 220 of file tlm_annotated_fifo.h.
Referenced by tlm::tlm_annotated_fifo< T >::nb_can_put(), tlm::tlm_annotated_fifo< T >::nb_put(), and tlm::tlm_annotated_fifo< T >::tlm_annotated_fifo().
template<typename T> tlm_peq< tlm_tag<T> *> tlm::tlm_annotated_fifo< T >::m_get_peq [protected]
Definition at line 221 of file tlm_annotated_fifo.h.
Referenced by tlm::tlm_annotated_fifo< T >::nb_can_put(), tlm::tlm_annotated_fifo< T >::nb_get(), and tlm::tlm_annotated_fifo< T >::tlm_annotated_fifo().
The documentation for this class was generated from the following file:
C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_annotated/tlm_annotated_channels/tlm_annotated_fifo.h