TLM 2: tlm::tlm_internal_annotated_fifo< T > Class Template Reference
tlm::tlm_internal_annotated_fifo
tlm::tlm_internal_annotated_fifo< T > Class Template Reference
#include <tlm_annotated_fifo.h>
Public Types
typedef tlm_tag< T > * my_tag_ptr
Public Member Functions
tlm_internal_annotated_fifo (const char *nm, int size)
void write (const T &t)
void write (const my_tag_ptr &)
Detailed Description
template<typename T>
class tlm::tlm_internal_annotated_fifo< T >
Definition at line 12 of file tlm_annotated_fifo.h.
Member Typedef Documentation
template<typename T> typedef tlm_tag<T>* tlm::tlm_internal_annotated_fifo< T >::my_tag_ptr
Definition at line 18 of file tlm_annotated_fifo.h.
Constructor & Destructor Documentation
template<typename T> tlm::tlm_internal_annotated_fifo< T >::tlm_internal_annotated_fifo (const char * nm, int size) [inline]
Definition at line 20 of file tlm_annotated_fifo.h.
Member Function Documentation
template<typename T> void tlm::tlm_internal_annotated_fifo< T >::write (const T & t) [inline, virtual]
Implements tlm::analysis_if< T >.
Definition at line 23 of file tlm_annotated_fifo.h.
References tlm::tlm_fifo< T >::nb_can_put(), and tlm::tlm_fifo< T >::nb_put().
template<typename T> void tlm::tlm_internal_annotated_fifo< T >::write (const my_tag_ptr &) [inline]
Definition at line 28 of file tlm_annotated_fifo.h.
References tlm::tlm_fifo< T >::read_event().
The documentation for this class was generated from the following file:
C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_annotated/tlm_annotated_channels/tlm_annotated_fifo.h