TLM 2: tlm_fifo< T > Class Template Reference
tlm_fifo< T > Class Template Reference
#include <tlm_fifo.h>
Public Member Functions
tlm_fifo (int size_=1)
tlm_fifo (const char *name_, int size_=1)
virtual ~tlm_fifo ()
T get (tlm_tag< T > *t=0)
bool nb_get (T &)
bool nb_can_get (tlm_tag< T > *t=0) const
const sc_event & ok_to_get (tlm_tag< T > *t=0) const
T peek (tlm_tag< T > *t=0) const
bool nb_peek (T &) const
bool nb_can_peek (tlm_tag< T > *t=0) const
const sc_event & ok_to_peek (tlm_tag< T > *t=0) const
void put (const T &)
bool nb_put (const T &)
bool nb_can_put (tlm_tag< T > *t=0) const
const sc_event & ok_to_put (tlm_tag< T > *t=0) const
void nb_expand (unsigned int n=1)
void nb_unbound (unsigned int n=16)
bool nb_reduce (unsigned int n=1)
bool nb_bound (unsigned int n)
bool nb_peek (T &, int n) const
bool nb_poke (const T &, int n=0)
int used () const
int size () const
void debug () const
const char * kind () const
Static Public Attributes
static const char *const kind_string = "tlm_fifo"
Protected Member Functions
sc_event & read_event (tlm_tag< T > *t=0)
void update ()
void init (int)
Protected Attributes
circular_buffer< T > * buffer
int m_size
int m_num_readable
int m_num_read
int m_num_written
bool m_expand
int m_num_read_no_notify
sc_event m_data_read_event
sc_event m_data_written_event
Private Member Functions
bool nb_can_put (int count, tlm_tag< T > *t=0) const
bool nb_get_no_notify (T &)
tlm_fifo (const tlm_fifo< T > &)
tlm_fifo & operator= (const tlm_fifo< T > &)
bool is_empty () const
bool is_full () const
Friends
class tlm_annotated::tlm_annotated_fifo< T >
Detailed Description
template<class T>
class tlm_fifo< T >
Definition at line 45 of file tlm_fifo.h.
Constructor & Destructor Documentation
template<class T> tlm_fifo< T >::tlm_fifo (int size_ = 1) [inline, explicit]
Definition at line 54 of file tlm_fifo.h.
References tlm_fifo< T >::init().
template<class T> tlm_fifo< T >::tlm_fifo (const char * name_, int size_ = 1) [inline, explicit]
Definition at line 61 of file tlm_fifo.h.
References tlm_fifo< T >::init().
template<class T> virtual tlm_fifo< T >::~tlm_fifo () [inline, virtual]
Definition at line 70 of file tlm_fifo.h.
References tlm_fifo< T >::buffer.
template<class T> tlm_fifo< T >::tlm_fifo (const tlm_fifo< T > &) [private]
Member Function Documentation
template<typename T> T tlm_fifo< T >::get (tlm_tag< T > * t = 0) [inline, virtual]
Implements tlm_blocking_get_if< T >.
Definition at line 36 of file tlm_fifo_put_get.h.
References tlm_fifo< T >::buffer, tlm_fifo< T >::is_empty(), tlm_fifo< T >::m_data_written_event, and tlm_fifo< T >::m_num_read.
template<typename T> bool tlm_fifo< T >::nb_get (T & val_) [inline, virtual]
Implements tlm_nonblocking_get_if< T >.
Definition at line 55 of file tlm_fifo_put_get.h.
References tlm_fifo< T >::buffer, tlm_fifo< T >::is_empty(), and tlm_fifo< T >::m_num_read.
template<typename T> bool tlm_fifo< T >::nb_can_get (tlm_tag< T > * t = 0) const [inline, virtual]
Implements tlm_nonblocking_get_if< T >.
Definition at line 95 of file tlm_fifo_put_get.h.
References tlm_fifo< T >::is_empty().
template<class T> const sc_event& tlm_fifo< T >::ok_to_get (tlm_tag< T > * t = 0) const [inline, virtual]
Implements tlm_nonblocking_get_if< T >.
Definition at line 82 of file tlm_fifo.h.
References tlm_fifo< T >::m_data_written_event.
template<typename T> T tlm_fifo< T >::peek (tlm_tag< T > * t = 0) const [inline, virtual]
Implements tlm_blocking_peek_if< T >.
Definition at line 30 of file tlm_fifo_peek.h.
References tlm_fifo< T >::buffer, tlm_fifo< T >::is_empty(), and tlm_fifo< T >::m_data_written_event.
template<typename T> bool tlm_fifo< T >::nb_peek (T & t) const [inline, virtual]
Implements tlm_nonblocking_peek_if< T >.
Definition at line 48 of file tlm_fifo_peek.h.
References tlm_fifo< T >::buffer, and tlm_fifo< T >::used().
template<typename T> bool tlm_fifo< T >::nb_can_peek (tlm_tag< T > * t = 0) const [inline, virtual]
Implements tlm_nonblocking_peek_if< T >.
Definition at line 80 of file tlm_fifo_peek.h.
References tlm_fifo< T >::is_empty().
template<class T> const sc_event& tlm_fifo< T >::ok_to_peek (tlm_tag< T > * t = 0) const [inline, virtual]
Implements tlm_nonblocking_peek_if< T >.
Definition at line 92 of file tlm_fifo.h.
References tlm_fifo< T >::m_data_written_event.
template<typename T> void tlm_fifo< T >::put (const T & val_) [inline, virtual]
Implements tlm_blocking_put_if< T >.
Definition at line 111 of file tlm_fifo_put_get.h.
References tlm_fifo< T >::buffer, tlm_fifo< T >::is_full(), tlm_fifo< T >::m_data_read_event, and tlm_fifo< T >::m_num_written.
template<typename T> bool tlm_fifo< T >::nb_put (const T & val_) [inline, virtual]
Implements tlm_nonblocking_put_if< T >.
Definition at line 132 of file tlm_fifo_put_get.h.
References tlm_fifo< T >::buffer, tlm_fifo< T >::is_full(), and tlm_fifo< T >::m_num_written.
Referenced by tlm_internal_annotated_fifo< T >::write(), and analysis_fifo< T >::write().
template<typename T> bool tlm_fifo< T >::nb_can_put (tlm_tag< T > * t = 0) const [inline, virtual]
Implements tlm_nonblocking_put_if< T >.
Definition at line 155 of file tlm_fifo_put_get.h.
References tlm_fifo< T >::is_full().
Referenced by tlm_internal_annotated_fifo< T >::write().
template<class T> const sc_event& tlm_fifo< T >::ok_to_put (tlm_tag< T > * t = 0) const [inline, virtual]
Implements tlm_nonblocking_put_if< T >.
Definition at line 103 of file tlm_fifo.h.
References tlm_fifo< T >::m_data_read_event.
template<typename T> void tlm_fifo< T >::nb_expand (unsigned int n = 1) [inline]
Definition at line 36 of file tlm_fifo_resize.h.
References tlm_fifo< T >::m_expand, and tlm_fifo< T >::m_size.
template<typename T> void tlm_fifo< T >::nb_unbound (unsigned int n = 16) [inline]
Definition at line 47 of file tlm_fifo_resize.h.
References tlm_fifo< T >::buffer, tlm_fifo< T >::m_expand, and tlm_fifo< T >::m_size.
template<typename T> bool tlm_fifo< T >::nb_reduce (unsigned int n = 1) [inline]
Definition at line 63 of file tlm_fifo_resize.h.
References tlm_fifo< T >::m_size, tlm_fifo< T >::nb_bound(), and tlm_fifo< T >::size().
template<typename T> bool tlm_fifo< T >::nb_bound (unsigned int n) [inline]
Definition at line 76 of file tlm_fifo_resize.h.
References tlm_fifo< T >::m_size, and tlm_fifo< T >::used().
Referenced by tlm_fifo< T >::nb_reduce().
template<typename T> bool tlm_fifo< T >::nb_peek (T & t, int n) const [inline, virtual]
Implements tlm_fifo_debug_if< T >.
Definition at line 62 of file tlm_fifo_peek.h.
References tlm_fifo< T >::buffer, and tlm_fifo< T >::used().
template<typename T> bool tlm_fifo< T >::nb_poke (const T & t, int n = 0) [inline, virtual]
Implements tlm_fifo_debug_if< T >.
Definition at line 88 of file tlm_fifo_peek.h.
References tlm_fifo< T >::buffer, and tlm_fifo< T >::used().
template<class T> int tlm_fifo< T >::used () const [inline, virtual]
Implements tlm_fifo_debug_if< T >.
Definition at line 120 of file tlm_fifo.h.
References tlm_fifo< T >::m_num_read, and tlm_fifo< T >::m_num_readable.
Referenced by tlm_fifo< T >::debug(), tlm_fifo< T >::is_empty(), tlm_fifo< T >::nb_bound(), tlm_fifo< T >::nb_peek(), and tlm_fifo< T >::nb_poke().
template<class T> int tlm_fifo< T >::size () const [inline, virtual]
Implements tlm_fifo_debug_if< T >.
Definition at line 124 of file tlm_fifo.h.
References tlm_fifo< T >::m_size.
Referenced by tlm_fifo< T >::debug(), tlm_fifo< T >::is_full(), and tlm_fifo< T >::nb_reduce().
template<class T> void tlm_fifo< T >::debug () const [inline, virtual]
Implements tlm_fifo_debug_if< T >.
Definition at line 128 of file tlm_fifo.h.
References tlm_fifo< T >::is_empty(), tlm_fifo< T >::is_full(), tlm_fifo< T >::m_num_read, tlm_fifo< T >::m_num_readable, tlm_fifo< T >::m_num_written, tlm_fifo< T >::size(), and tlm_fifo< T >::used().
template<class T> const char* tlm_fifo< T >::kind () const [inline]
Definition at line 143 of file tlm_fifo.h.
References tlm_fifo< T >::kind_string.
template<class T> bool tlm_fifo< T >::nb_can_put (int count, tlm_tag< T > * t = 0) const [inline, private]
Definition at line 151 of file tlm_fifo.h.
References tlm_fifo< T >::m_num_readable, tlm_fifo< T >::m_num_written, and tlm_fifo< T >::m_size.
template<typename T> bool tlm_fifo< T >::nb_get_no_notify (T & val_) [inline, private]
Definition at line 74 of file tlm_fifo_put_get.h.
References tlm_fifo< T >::buffer, tlm_fifo< T >::is_empty(), tlm_fifo< T >::m_num_read, and tlm_fifo< T >::m_num_read_no_notify.
template<class T> sc_event& tlm_fifo< T >::read_event (tlm_tag< T > * t = 0) [inline, protected]
Definition at line 161 of file tlm_fifo.h.
References tlm_fifo< T >::m_data_read_event.
Referenced by tlm_internal_annotated_fifo< T >::write().
template<typename T> void tlm_fifo< T >::update () [inline, protected]
Definition at line 248 of file tlm_fifo.h.
References tlm_fifo< T >::buffer, tlm_fifo< T >::m_data_read_event, tlm_fifo< T >::m_data_written_event, tlm_fifo< T >::m_expand, tlm_fifo< T >::m_num_read, tlm_fifo< T >::m_num_read_no_notify, tlm_fifo< T >::m_num_readable, and tlm_fifo< T >::m_num_written.
template<typename T> void tlm_fifo< T >::init (int size_) [inline, protected]
Definition at line 222 of file tlm_fifo.h.
References tlm_fifo< T >::buffer, tlm_fifo< T >::m_expand, tlm_fifo< T >::m_num_read, tlm_fifo< T >::m_num_read_no_notify, tlm_fifo< T >::m_num_readable, tlm_fifo< T >::m_num_written, and tlm_fifo< T >::m_size.
Referenced by tlm_fifo< T >::tlm_fifo().
template<class T> tlm_fifo& tlm_fifo< T >::operator= (const tlm_fifo< T > &) [private]
template<class T> bool tlm_fifo< T >::is_empty () const [inline, private]
Definition at line 199 of file tlm_fifo.h.
References tlm_fifo< T >::used().
Referenced by tlm_fifo< T >::debug(), tlm_fifo< T >::get(), tlm_fifo< T >::nb_can_get(), tlm_fifo< T >::nb_can_peek(), tlm_fifo< T >::nb_get(), tlm_fifo< T >::nb_get_no_notify(), and tlm_fifo< T >::peek().
template<class T> bool tlm_fifo< T >::is_full () const [inline, private]
Definition at line 203 of file tlm_fifo.h.
References tlm_fifo< T >::m_num_readable, tlm_fifo< T >::m_num_written, and tlm_fifo< T >::size().
Referenced by tlm_fifo< T >::debug(), tlm_fifo< T >::nb_can_put(), tlm_fifo< T >::nb_put(), and tlm_fifo< T >::put().
Friends And Related Function Documentation
template<class T> friend class tlm_annotated::tlm_annotated_fifo< T > [friend]
Definition at line 147 of file tlm_fifo.h.
Member Data Documentation
template<class T> const char *const tlm_fifo< T >::kind_string = "tlm_fifo" [inline, static]
Definition at line 141 of file tlm_fifo.h.
Referenced by tlm_fifo< T >::kind().
template<class T> circular_buffer<T>* tlm_fifo< T >::buffer [protected]
Definition at line 175 of file tlm_fifo.h.
Referenced by tlm_fifo< T >::get(), tlm_fifo< T >::init(), tlm_fifo< T >::nb_get(), tlm_fifo< T >::nb_get_no_notify(), tlm_fifo< T >::nb_peek(), tlm_fifo< T >::nb_poke(), tlm_fifo< T >::nb_put(), tlm_fifo< T >::nb_unbound(), tlm_fifo< T >::peek(), tlm_fifo< T >::put(), tlm_fifo< T >::update(), and tlm_fifo< T >::~tlm_fifo().
template<class T> int tlm_fifo< T >::m_size [protected]
Definition at line 177 of file tlm_fifo.h.
Referenced by tlm_fifo< T >::init(), tlm_fifo< T >::nb_bound(), tlm_fifo< T >::nb_can_put(), tlm_fifo< T >::nb_expand(), tlm_fifo< T >::nb_reduce(), tlm_fifo< T >::nb_unbound(), and tlm_fifo< T >::size().
template<class T> int tlm_fifo< T >::m_num_readable [protected]
Definition at line 179 of file tlm_fifo.h.
Referenced by tlm_fifo< T >::debug(), tlm_fifo< T >::init(), tlm_fifo< T >::is_full(), tlm_fifo< T >::nb_can_put(), tlm_fifo< T >::update(), and tlm_fifo< T >::used().
template<class T> int tlm_fifo< T >::m_num_read [protected]
Definition at line 180 of file tlm_fifo.h.
Referenced by tlm_fifo< T >::debug(), tlm_fifo< T >::get(), tlm_fifo< T >::init(), tlm_fifo< T >::nb_get(), tlm_fifo< T >::nb_get_no_notify(), tlm_fifo< T >::update(), and tlm_fifo< T >::used().
template<class T> int tlm_fifo< T >::m_num_written [protected]
Definition at line 181 of file tlm_fifo.h.
Referenced by tlm_fifo< T >::debug(), tlm_fifo< T >::init(), tlm_fifo< T >::is_full(), tlm_fifo< T >::nb_can_put(), tlm_fifo< T >::nb_put(), tlm_fifo< T >::put(), and tlm_fifo< T >::update().
template<class T> bool tlm_fifo< T >::m_expand [protected]
Definition at line 182 of file tlm_fifo.h.
Referenced by tlm_fifo< T >::init(), tlm_fifo< T >::nb_expand(), tlm_fifo< T >::nb_unbound(), and tlm_fifo< T >::update().
template<class T> int tlm_fifo< T >::m_num_read_no_notify [protected]
Definition at line 183 of file tlm_fifo.h.
Referenced by tlm_fifo< T >::init(), tlm_fifo< T >::nb_get_no_notify(), and tlm_fifo< T >::update().
template<class T> sc_event tlm_fifo< T >::m_data_read_event [protected]
Definition at line 185 of file tlm_fifo.h.
Referenced by tlm_fifo< T >::ok_to_put(), tlm_fifo< T >::put(), tlm_fifo< T >::read_event(), and tlm_fifo< T >::update().
template<class T> sc_event tlm_fifo< T >::m_data_written_event [protected]
Definition at line 186 of file tlm_fifo.h.
Referenced by tlm_fifo< T >::get(), tlm_fifo< T >::ok_to_get(), tlm_fifo< T >::ok_to_peek(), tlm_fifo< T >::peek(), and tlm_fifo< T >::update().
The documentation for this class was generated from the following files:
C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_core/tlm_fifo/tlm_fifo.h
C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_core/tlm_fifo/tlm_fifo_peek.h
C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_core/tlm_fifo/tlm_fifo_put_get.h
C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_core/tlm_fifo/tlm_fifo_resize.h