TLM 2: tlm::tlm_initiator_port< IF, N > Class Template Reference
tlm::tlm_initiator_port
tlm::tlm_initiator_port< IF, N > Class Template Reference
Class tlm_initiator_port: port to be instantiated on the initiator side.
#include <tlm_initiator_port.h>
Public Member Functions
tlm_initiator_port (const char *name)
sc_port overridden methods
Need to specialize binding operation to support port propagation in transaction recorders. Specialization is done for sc_port/sc_port and sc_port/sc_export Other redefinitions of bindings are just calls to regular bind function
Note: This is due to non virtual definition of SystemC bind method
void before_end_of_elaboration ()
void end_of_elaboration ()
void bind (target_port_type &target_port_)
bind(sc_export) overridden with port registration
template<typename OTHER_IF>
void bind (tlm_target_port< OTHER_IF > &target_port_)
Case of the other port uses another interface as template: works only if OTHER_IF derives from IF.
void operator() (target_port_type &target_port_)
operator() (sc_export) overridden with port registration
template<typename OTHER_IF>
void operator() (tlm_target_port< OTHER_IF > &target_port_)
Case of the other port uses another interface as template: works only if OTHER_IF derives from IF.
void bind (sc_core::sc_port_b< interface_type > &port_)
bind(sc_port) overridden with port registration
void operator() (sc_core::sc_port_b< interface_type > &port_)
operator() (sc_port) overridden with port registration
void bind (interface_type &interface_)
bind(interface_type) overridden with port registration
void operator() (interface_type &interface_)
operator () (interface_type) overridden with port registration
Protected Member Functions
bool is_interface_bound_twice (sc_core::sc_export_base &target_port_)
Private Types
typedef IF interface_type
typedef
tlm_target_port< IF > target_port_type
typedef
tlm_initiator_port
< IF, N > initiator_port_type
typedef
tlm_target_port_base target_port_base_type
typedef
tlm_initiator_port_base initiator_port_base_type
Detailed Description
template<typename IF, int N = 1>
class tlm::tlm_initiator_port< IF, N >
Class tlm_initiator_port: port to be instantiated on the initiator side.
This class could be used as base class for user defined initiator ports (support of user convenience layer).
It provides new binding methods definition:
sc_port to sc_export binding must be identified in order to create target_port_list used for port ID propagation through hierarchical binding.
sc_port to sc_port binding creates two initiator ports lists: one regular list (deep port "knows" other initiator ports through a hierarchy) and a reversed list (the port directly bound to the interface "knows" deeper ports through a hierarchy) used to convey target_port list to deeper ports for target port ID propagation. An error detection is also provided: When the same interface is bound two times to a sc_port, SystemC causes the simulation end. This case could append in test platform (dedicated debug and regular port of a target bound to the same router). The specific binding issues a warning message but let the simulation run.
Definition at line 51 of file tlm_initiator_port.h.
Member Typedef Documentation
template<typename IF, int N = 1> typedef IF tlm::tlm_initiator_port< IF, N >::interface_type [private]
Definition at line 55 of file tlm_initiator_port.h.
template<typename IF, int N = 1> typedef tlm_target_port<IF> tlm::tlm_initiator_port< IF, N >::target_port_type [private]
Reimplemented from tlm::tlm_initiator_port_base.
Definition at line 56 of file tlm_initiator_port.h.
template<typename IF, int N = 1> typedef tlm_initiator_port<IF,N> tlm::tlm_initiator_port< IF, N >::initiator_port_type [private]
Definition at line 57 of file tlm_initiator_port.h.
template<typename IF, int N = 1> typedef tlm_target_port_base tlm::tlm_initiator_port< IF, N >::target_port_base_type [private]
Definition at line 59 of file tlm_initiator_port.h.
template<typename IF, int N = 1> typedef tlm_initiator_port_base tlm::tlm_initiator_port< IF, N >::initiator_port_base_type [private]
Definition at line 60 of file tlm_initiator_port.h.
Constructor & Destructor Documentation
template<typename IF, int N> tlm::tlm_initiator_port< IF, N >::tlm_initiator_port (const char * name) [inline]
Definition at line 159 of file tlm_initiator_port.h.
Member Function Documentation
template<typename IF, int N> void tlm::tlm_initiator_port< IF, N >::before_end_of_elaboration () [inline]
Called just before end of elaboration to propagate registered target ports to all the bound initiator ports (using the reversed initiator port list).
Remark: sc_port_base::complete_binding should be the best place to do that but this method is private !!
Definition at line 199 of file tlm_initiator_port.h.
References tlm::tlm_initiator_port_base::create_port_list(), tlm::tlm_initiator_port_base::get_reversed_initiator_port_list(), tlm::tlm_initiator_port_base::m_target_port_list, and tlm::tlm_initiator_port_base::set_initiator_port_list().
template<typename IF, int N> void tlm::tlm_initiator_port< IF, N >::end_of_elaboration () [inline]
Called at the end of elaboration. Checks target port list: empty target port list is a fatal error as initiator port should be bound at least to one target_port
Definition at line 237 of file tlm_initiator_port.h.
References tlm::tlm_initiator_port_base::get_initiator_port_list(), tlm::tlm_initiator_port_base::get_reversed_initiator_port_list(), and tlm::tlm_initiator_port_base::get_target_port_list().
template<typename IF, int N> void tlm::tlm_initiator_port< IF, N >::bind (target_port_type & target_port_) [inline]
bind(sc_export) overridden with port registration
Definition at line 284 of file tlm_initiator_port.h.
References tlm::tlm_initiator_port< IF, N >::is_interface_bound_twice(), and tlm::tlm_initiator_port_base::register_target_port().
Referenced by tlm::tlm_initiator_port< IF, N >::operator()().
template<typename IF, int N> template<typename OTHER_IF> void tlm::tlm_initiator_port< IF, N >::bind (tlm_target_port< OTHER_IF > & target_port_) [inline]
Case of the other port uses another interface as template: works only if OTHER_IF derives from IF.
Definition at line 297 of file tlm_initiator_port.h.
References tlm::tlm_initiator_port< IF, N >::is_interface_bound_twice().
template<typename IF, int N> void tlm::tlm_initiator_port< IF, N >::operator() (target_port_type & target_port_) [inline]
operator() (sc_export) overridden with port registration
Definition at line 324 of file tlm_initiator_port.h.
References tlm::tlm_initiator_port< IF, N >::bind().
template<typename IF, int N = 1> template<typename OTHER_IF> void tlm::tlm_initiator_port< IF, N >::operator() (tlm_target_port< OTHER_IF > & target_port_) [inline]
Case of the other port uses another interface as template: works only if OTHER_IF derives from IF.
Definition at line 119 of file tlm_initiator_port.h.
template<typename IF, int N> void tlm::tlm_initiator_port< IF, N >::bind (sc_core::sc_port_b< interface_type > & port_) [inline]
bind(sc_port) overridden with port registration
Definition at line 333 of file tlm_initiator_port.h.
References tlm::tlm_initiator_port_base::get_reversed_initiator_port_list(), tlm::tlm_initiator_port_base::register_initiator_port(), and tlm::tlm_initiator_port_base::reversed_register_initiator_port().
template<typename IF, int N> void tlm::tlm_initiator_port< IF, N >::operator() (sc_core::sc_port_b< interface_type > & port_) [inline]
operator() (sc_port) overridden with port registration
Definition at line 353 of file tlm_initiator_port.h.
References tlm::tlm_initiator_port< IF, N >::bind().
template<typename IF, int N> void tlm::tlm_initiator_port< IF, N >::bind (interface_type & interface_) [inline]
bind(interface_type) overridden with port registration
Definition at line 367 of file tlm_initiator_port.h.
template<typename IF, int N> void tlm::tlm_initiator_port< IF, N >::operator() (interface_type & interface_) [inline]
operator () (interface_type) overridden with port registration
Definition at line 377 of file tlm_initiator_port.h.
template<typename IF, int N> bool tlm::tlm_initiator_port< IF, N >::is_interface_bound_twice (sc_core::sc_export_base & target_port_) [inline, protected]
Returns true and issues an error message and return true if the same interface is bound two times throught 2 differents target port.
Returns true and issues an error message if the same interface is bound two times throught 2 differents target port.
Definition at line 168 of file tlm_initiator_port.h.
Referenced by tlm::tlm_initiator_port< IF, N >::bind().
The documentation for this class was generated from the following file:
C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_ports/tlm_initiator_port.h