TLM 2: tlm::tlm_nonblocking_peek_if< T > Class Template Reference
tlm::tlm_nonblocking_peek_if
tlm::tlm_nonblocking_peek_if< T > Class Template Reference
#include <tlm_core_ifs.h>
Public Member Functions
virtual bool nb_peek (T &t) const =0
virtual bool nb_can_peek (tlm_tag< T > *t=0) const =0
virtual const
sc_core::sc_event & ok_to_peek (tlm_tag< T > *t=0) const =0
Detailed Description
template<typename T>
class tlm::tlm_nonblocking_peek_if< T >
Definition at line 111 of file tlm_core_ifs.h.
Member Function Documentation
template<typename T> virtual bool tlm::tlm_nonblocking_peek_if< T >::nb_peek (T & t) const [pure virtual]
Implemented in tlm::tlm_fifo< T >, tlm::tlm_put_get_imp< PUT_DATA, GET_DATA >, tlm::tlm_put_get_imp< REQ, RSP >, and tlm::tlm_put_get_imp< RSP, REQ >.
Referenced by tlm::tlm_put_get_imp< RSP, REQ >::nb_peek().
template<typename T> virtual bool tlm::tlm_nonblocking_peek_if< T >::nb_can_peek (tlm_tag< T > * t = 0) const [pure virtual]
Implemented in tlm::tlm_fifo< T >, tlm::tlm_put_get_imp< PUT_DATA, GET_DATA >, tlm::tlm_put_get_imp< REQ, RSP >, and tlm::tlm_put_get_imp< RSP, REQ >.
Referenced by tlm::tlm_put_get_imp< RSP, REQ >::nb_can_peek().
template<typename T> virtual const sc_core::sc_event& tlm::tlm_nonblocking_peek_if< T >::ok_to_peek (tlm_tag< T > * t = 0) const [pure virtual]
Implemented in tlm::tlm_fifo< T >, tlm::tlm_put_get_imp< PUT_DATA, GET_DATA >, tlm::tlm_put_get_imp< REQ, RSP >, and tlm::tlm_put_get_imp< RSP, REQ >.
Referenced by tlm::tlm_nonblocking_peek_port< T >::ok_to_peek(), and tlm::tlm_put_get_imp< RSP, REQ >::ok_to_peek().
The documentation for this class was generated from the following file:
C:/ESLX/projects/TLMWG/tlm2/include/tlm/tlm_h/tlm_req_rsp/tlm_1_interfaces/tlm_core_ifs.h