TLM 2: tlm::tlm_nonblocking_get_if< T > Class Template Reference
tlm::tlm_nonblocking_get_if
tlm::tlm_nonblocking_get_if< T > Class Template Reference
#include <tlm_core_ifs.h>
Public Member Functions
virtual bool nb_get (T &t)=0
virtual bool nb_can_get (tlm_tag< T > *t=0) const =0
virtual const
sc_core::sc_event & ok_to_get (tlm_tag< T > *t=0) const =0
Detailed Description
template<typename T>
class tlm::tlm_nonblocking_get_if< T >
Definition at line 68 of file tlm_core_ifs.h.
Member Function Documentation
template<typename T> virtual bool tlm::tlm_nonblocking_get_if< T >::nb_get (T & t) [pure virtual]
Implemented in tlm::tlm_fifo< T >, tlm::tlm_put_get_imp< PUT_DATA, GET_DATA >, tlm::tlm_put_get_imp< REQ, RSP >, and tlm::tlm_put_get_imp< RSP, REQ >.
Referenced by tlm::tlm_put_get_imp< RSP, REQ >::nb_get().
template<typename T> virtual bool tlm::tlm_nonblocking_get_if< T >::nb_can_get (tlm_tag< T > * t = 0) const [pure virtual]
Implemented in tlm::tlm_fifo< T >, tlm::tlm_put_get_imp< PUT_DATA, GET_DATA >, tlm::tlm_put_get_imp< REQ, RSP >, and tlm::tlm_put_get_imp< RSP, REQ >.
Referenced by tlm::tlm_put_get_imp< RSP, REQ >::nb_can_get().
template<typename T> virtual const sc_core::sc_event& tlm::tlm_nonblocking_get_if< T >::ok_to_get (tlm_tag< T > * t = 0) const [pure virtual]
Implemented in tlm::tlm_fifo< T >, tlm::tlm_put_get_imp< PUT_DATA, GET_DATA >, tlm::tlm_put_get_imp< REQ, RSP >, and tlm::tlm_put_get_imp< RSP, REQ >.
Referenced by tlm::tlm_nonblocking_get_port< T >::ok_to_get(), and tlm::tlm_put_get_imp< RSP, REQ >::ok_to_get().
The documentation for this class was generated from the following file:
C:/ESLX/projects/TLMWG/tlm2/include/tlm/tlm_h/tlm_req_rsp/tlm_1_interfaces/tlm_core_ifs.h