TLM 2: tlm::tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF > Class Template Reference
tlm::tlm_initiator_socket
tlm::tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF > Class Template Reference
#include <tlm_initiator_socket.h>
Public Types
typedef FW_IF fw_interface_type
typedef BW_IF bw_interface_type
typedef
sc_core::sc_port
< fw_interface_type > port_type
typedef
sc_core::sc_export
< bw_interface_type > export_type
typedef
tlm_target_socket
< BUSWIDTH,
fw_interface_type,
bw_interface_type > target_socket_type
Public Member Functions
tlm_initiator_socket (const char *name)
unsigned int get_bus_width () const
void bind (target_socket_type &s)
void operator() (target_socket_type &s)
void bind (tlm_initiator_socket &s)
void operator() (tlm_initiator_socket &s)
void bind (bw_interface_type &ifs)
void operator() (bw_interface_type &s)
Protected Attributes
export_type mExport
Friends
class tlm_target_socket< BUSWIDTH, fw_interface_type, bw_interface_type >
Detailed Description
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>>
class tlm::tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF >
Definition at line 33 of file tlm_initiator_socket.h.
Member Typedef Documentation
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> typedef FW_IF tlm::tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF >::fw_interface_type
Definition at line 36 of file tlm_initiator_socket.h.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> typedef BW_IF tlm::tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF >::bw_interface_type
Definition at line 37 of file tlm_initiator_socket.h.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> typedef sc_core::sc_port<fw_interface_type> tlm::tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF >::port_type
Definition at line 38 of file tlm_initiator_socket.h.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> typedef sc_core::sc_export<bw_interface_type> tlm::tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF >::export_type
Definition at line 39 of file tlm_initiator_socket.h.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> typedef tlm_target_socket<BUSWIDTH, fw_interface_type, bw_interface_type> tlm::tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF >::target_socket_type
Definition at line 42 of file tlm_initiator_socket.h.
Constructor & Destructor Documentation
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> tlm::tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF >::tlm_initiator_socket (const char * name) [inline]
Definition at line 49 of file tlm_initiator_socket.h.
Member Function Documentation
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> unsigned int tlm::tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF >::get_bus_width () const [inline]
Definition at line 54 of file tlm_initiator_socket.h.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> void tlm::tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF >::bind (target_socket_type & s) [inline]
Definition at line 66 of file tlm_initiator_socket.h.
References tlm::tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF >::mExport, and tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF >::mPort.
Referenced by tlm::tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF >::operator()().
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> void tlm::tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF >::operator() (target_socket_type & s) [inline]
Definition at line 74 of file tlm_initiator_socket.h.
References tlm::tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF >::bind().
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> void tlm::tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF >::bind (tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF > & s) [inline]
Definition at line 83 of file tlm_initiator_socket.h.
References tlm::tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF >::mExport.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> void tlm::tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF >::operator() (tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF > & s) [inline]
Definition at line 91 of file tlm_initiator_socket.h.
References tlm::tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF >::bind().
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> void tlm::tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF >::bind (bw_interface_type & ifs) [inline]
Definition at line 100 of file tlm_initiator_socket.h.
References tlm::tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF >::mExport.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> void tlm::tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF >::operator() (bw_interface_type & s) [inline]
Definition at line 105 of file tlm_initiator_socket.h.
References tlm::tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF >::bind().
Friends And Related Function Documentation
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> friend class tlm_target_socket< BUSWIDTH,fw_interface_type,bw_interface_type > [friend]
Definition at line 46 of file tlm_initiator_socket.h.
Member Data Documentation
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> export_type tlm::tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF >::mExport [protected]
Definition at line 111 of file tlm_initiator_socket.h.
Referenced by tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF >::bind(), and tlm::tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF >::bind().
The documentation for this class was generated from the following file:
C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_ports/tlm_initiator_socket.h