TLM 2: tlm::tlm_initiator_port_base Class Reference
tlm::tlm_initiator_port_base
tlm::tlm_initiator_port_base Class Reference
Class tlm_initiator_port_base: This class is a base class for tlm_initiator port.
#include <tlm_initiator_port_base.h>
Public Member Functions
tlm_initiator_port_base ()
Data members access methods
void register_target_port (target_port_type *target_port)
Register the target port.
std::vector
< target_port_type * > & get_target_port_list ()
Returns the vector of registered target port(s).
void set_target_port_list (std::vector< target_port_type * > &target_port_list)
Sets the vector of registered target port(s) (port propagation).
void register_initiator_port (this_type *initiator_port)
Register the initiator port in the regular list.
std::vector
< this_type * > & get_initiator_port_list ()
Returns the vector of registered initiator port(s).
void set_initiator_port_list (std::vector< this_type * > &initiator_port_list)
Sets the vector of registered initiator port(s) (port propagation).
void reversed_register_initiator_port (this_type *initiator_port)
Register the initiator port in the reversed list.
std::vector
< this_type * > & get_reversed_initiator_port_list ()
Returns the vector of registered initiator port(s), reversed list.
void set_reversed_initiator_port_list (std::vector< this_type * > &initiator_port_list)
Sets the vector of registered initiator port(s) (port propagation) reversed list.
Protected Member Functions
void create_port_list (std::vector< this_type * > &port_list)
Creates the initiator port list from a non NULL initiator_port_type * list.
Protected Attributes
std::vector
< target_port_type * > m_target_port_list
sc_export objects registration
std::vector
< this_type * > m_initiator_port_list
sc_port objects registration
std::vector
< this_type * > m_reversed_initiator_port_list
sc_port objects registration
Private Types
typedef
tlm_initiator_port_base this_type
typedef
tlm_target_port_base target_port_type
Detailed Description
Class tlm_initiator_port_base: This class is a base class for tlm_initiator port.
It provides a container to store registered target ports as pointer list (required for target port ID propagation and transaction recording).
It provides also two containers to store registered initiator ports as pointer list:
The first container registers initiator port from "deeper" initiator port to the the initiator port directly bound to the interface.
The second list, named reversed list, allows the port directly bound to the interface to propagate its target port list to "deeper" initiator ports.
Accessors are provided for all the port lists.
Definition at line 48 of file tlm_initiator_port_base.h.
Member Typedef Documentation
typedef tlm_initiator_port_base tlm::tlm_initiator_port_base::this_type [private]
Definition at line 50 of file tlm_initiator_port_base.h.
typedef tlm_target_port_base tlm::tlm_initiator_port_base::target_port_type [private]
Reimplemented in tlm::tlm_initiator_port< IF, N >.
Definition at line 51 of file tlm_initiator_port_base.h.
Constructor & Destructor Documentation
tlm::tlm_initiator_port_base::tlm_initiator_port_base () [inline]
Definition at line 58 of file tlm_initiator_port_base.h.
References m_reversed_initiator_port_list.
Member Function Documentation
void tlm::tlm_initiator_port_base::register_target_port (target_port_type * target_port) [inline]
Register the target port.
Definition at line 70 of file tlm_initiator_port_base.h.
References m_target_port_list.
Referenced by tlm::tlm_initiator_port< IF, N >::bind().
std::vector<target_port_type *>& tlm::tlm_initiator_port_base::get_target_port_list () [inline]
Returns the vector of registered target port(s).
Definition at line 75 of file tlm_initiator_port_base.h.
References m_target_port_list.
Referenced by tlm::tlm_initiator_port< IF, N >::end_of_elaboration().
void tlm::tlm_initiator_port_base::set_target_port_list (std::vector< target_port_type * > & target_port_list) [inline]
Sets the vector of registered target port(s) (port propagation).
Definition at line 80 of file tlm_initiator_port_base.h.
References m_target_port_list.
void tlm::tlm_initiator_port_base::register_initiator_port (this_type * initiator_port) [inline]
Register the initiator port in the regular list.
Definition at line 87 of file tlm_initiator_port_base.h.
References m_initiator_port_list.
Referenced by tlm::tlm_initiator_port< IF, N >::bind().
std::vector<this_type *>& tlm::tlm_initiator_port_base::get_initiator_port_list () [inline]
Returns the vector of registered initiator port(s).
Definition at line 92 of file tlm_initiator_port_base.h.
References m_initiator_port_list.
Referenced by tlm::tlm_initiator_port< IF, N >::end_of_elaboration().
void tlm::tlm_initiator_port_base::set_initiator_port_list (std::vector< this_type * > & initiator_port_list) [inline]
Sets the vector of registered initiator port(s) (port propagation).
Definition at line 97 of file tlm_initiator_port_base.h.
References m_initiator_port_list.
Referenced by tlm::tlm_initiator_port< IF, N >::before_end_of_elaboration().
void tlm::tlm_initiator_port_base::reversed_register_initiator_port (this_type * initiator_port) [inline]
Register the initiator port in the reversed list.
Definition at line 104 of file tlm_initiator_port_base.h.
References m_reversed_initiator_port_list.
Referenced by tlm::tlm_initiator_port< IF, N >::bind().
std::vector<this_type *>& tlm::tlm_initiator_port_base::get_reversed_initiator_port_list () [inline]
Returns the vector of registered initiator port(s), reversed list.
Definition at line 109 of file tlm_initiator_port_base.h.
References m_reversed_initiator_port_list.
Referenced by tlm::tlm_initiator_port< IF, N >::before_end_of_elaboration(), tlm::tlm_initiator_port< IF, N >::bind(), and tlm::tlm_initiator_port< IF, N >::end_of_elaboration().
void tlm::tlm_initiator_port_base::set_reversed_initiator_port_list (std::vector< this_type * > & initiator_port_list) [inline]
Sets the vector of registered initiator port(s) (port propagation) reversed list.
Definition at line 114 of file tlm_initiator_port_base.h.
References m_reversed_initiator_port_list.
void tlm::tlm_initiator_port_base::create_port_list (std::vector< this_type * > & port_list) [inline, protected]
Creates the initiator port list from a non NULL initiator_port_type * list.
Reentreant function to create the complete list of bound initiator_port
Definition at line 146 of file tlm_initiator_port_base.h.
Referenced by tlm::tlm_initiator_port< IF, N >::before_end_of_elaboration().
Member Data Documentation
std::vector<target_port_type *> tlm::tlm_initiator_port_base::m_target_port_list [protected]
sc_export objects registration
Direct registration of the bound target port(s) into current initiator port
Definition at line 127 of file tlm_initiator_port_base.h.
Referenced by tlm::tlm_initiator_port< IF, N >::before_end_of_elaboration(), get_target_port_list(), register_target_port(), and set_target_port_list().
std::vector<this_type *> tlm::tlm_initiator_port_base::m_initiator_port_list [protected]
sc_port objects registration
Direct registration of the bound initiator port into current initiator port
Definition at line 134 of file tlm_initiator_port_base.h.
Referenced by get_initiator_port_list(), register_initiator_port(), and set_initiator_port_list().
std::vector<this_type *> tlm::tlm_initiator_port_base::m_reversed_initiator_port_list [protected]
sc_port objects registration
Direct registration of the current initiator port into the bound initiator port for port propagation: all bound initiator ports get back the same target_port_list
Definition at line 141 of file tlm_initiator_port_base.h.
Referenced by get_reversed_initiator_port_list(), reversed_register_initiator_port(), set_reversed_initiator_port_list(), and tlm_initiator_port_base().
The documentation for this class was generated from the following file:
C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_ports/tlm_initiator_port_base.h