TLM 2: tlm_target_port< IF > Class Template Reference
tlm_target_port< IF > Class Template Reference
Class tlm_target_port: port to be instantiated on the target side.
#include <tlm_target_port.h>
Public Member Functions
tlm_target_port (const char *name)
sc_export overridden methods
Need to specialize binding operation to support port propagation in transaction recorders. Specialization is done for sc_export/sc_export. Other redefinitions of bindings are just calls to regular bind function
Note: This is due to non virtual definition of SystemC bind
void before_end_of_elaboration ()
void end_of_elaboration ()
void bind (target_port_type &target_port_)
bind(sc_export) with target ports propagation
template<typename OTHER_IF>
void bind (tlm_target_port< OTHER_IF > &target_port_)
Case of the other port uses another interface as template: works only if OTHER_IF derives from IF.
void operator() (target_port_type &target_port_)
operator() (sc_export) overridden: just calls bind(sc_export)
template<typename OTHER_IF>
void operator() (tlm_target_port< OTHER_IF > &target_port_)
Case of the other port uses another interface as template: works only if OTHER_IF derives from IF.
void bind (interface_type &interface_)
bind(interface_type) overridden
void operator() (interface_type &interface_)
operator() (interface_type) overridden
Protected Member Functions
bool is_already_bound (sc_interface *other_if)
Private Types
typedef IF interface_type
typedef
tlm_target_port< IF > target_port_type
typedef
tlm_target_port_base target_port_base_type
Detailed Description
template<typename IF>
class tlm_target_port< IF >
Class tlm_target_port: port to be instantiated on the target side.
This class could be used as base class for user defined target ports (support of user convenience layer).
It provides new binding methods definition: sc_export to sc_export binding must be identified in order create tlm_target_port_base::target_port_list used target port ID propagation through hierarchical binding; the only port ID that makes sense is the port ID of the port directly bound to the interface. An error detection is also provided: multiple interface bind declarations are not detected by sc_export (the interface is just replaced), the new binding definition issues an error message in this case.
Definition at line 43 of file tlm_target_port.h.
Member Typedef Documentation
template<typename IF> typedef IF tlm_target_port< IF >::interface_type [private]
Definition at line 47 of file tlm_target_port.h.
template<typename IF> typedef tlm_target_port<IF> tlm_target_port< IF >::target_port_type [private]
Definition at line 48 of file tlm_target_port.h.
template<typename IF> typedef tlm_target_port_base tlm_target_port< IF >::target_port_base_type [private]
Definition at line 49 of file tlm_target_port.h.
Constructor & Destructor Documentation
template<typename IF> tlm_target_port< IF >::tlm_target_port (const char * name) [inline]
Definition at line 138 of file tlm_target_port.h.
Member Function Documentation
template<typename IF> void tlm_target_port< IF >::before_end_of_elaboration () [inline]
Called just before end of elaboration to propagate the significant target port id: the only valid port id is the one set by the module which implements the tlm core interface.
Remark: sc_port_base::complete_binding should be the best place to do that but this method is private !!
Definition at line 181 of file tlm_target_port.h.
References tlm_target_port_base::get_target_port_list(), and tlm_target_port_base::set_tlm_export_id().
template<typename IF> void tlm_target_port< IF >::end_of_elaboration () [inline]
Called at the end of elaboration. Used to print debug message: content opf the target port list
Definition at line 199 of file tlm_target_port.h.
References tlm_target_port_base::get_target_port_list().
template<typename IF> void tlm_target_port< IF >::bind (target_port_type & target_port_) [inline]
bind(sc_export) with target ports propagation
Definition at line 219 of file tlm_target_port.h.
References tlm_target_port_base::get_target_port_list(), tlm_target_port< IF >::is_already_bound(), and tlm_target_port_base::register_target_port().
Referenced by tlm_target_port< IF >::operator()().
template<typename IF> template<typename OTHER_IF> void tlm_target_port< IF >::bind (tlm_target_port< OTHER_IF > & target_port_) [inline]
Case of the other port uses another interface as template: works only if OTHER_IF derives from IF.
Definition at line 240 of file tlm_target_port.h.
References tlm_target_port_base::get_target_port_list(), tlm_target_port< IF >::is_already_bound(), and tlm_target_port_base::register_target_port().
template<typename IF> void tlm_target_port< IF >::operator() (target_port_type & target_port_) [inline]
operator() (sc_export) overridden: just calls bind(sc_export)
Definition at line 99 of file tlm_target_port.h.
References tlm_target_port< IF >::bind().
template<typename IF> template<typename OTHER_IF> void tlm_target_port< IF >::operator() (tlm_target_port< OTHER_IF > & target_port_) [inline]
Case of the other port uses another interface as template: works only if OTHER_IF derives from IF.
Definition at line 105 of file tlm_target_port.h.
template<typename IF> void tlm_target_port< IF >::bind (interface_type & interface_) [inline]
bind(interface_type) overridden
Definition at line 275 of file tlm_target_port.h.
template<typename IF> void tlm_target_port< IF >::operator() (interface_type & interface_) [inline]
operator() (interface_type) overridden
Definition at line 283 of file tlm_target_port.h.
template<typename IF> bool tlm_target_port< IF >::is_already_bound (sc_interface * other_if) [inline, protected]
Returns true and issues an error message if the port is already bound to an interface during the binding of other_if (called by bind(sc_export))
Definition at line 148 of file tlm_target_port.h.
Referenced by tlm_target_port< IF >::bind().
The documentation for this class was generated from the following file:
C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_ports/tlm_target_port.h