TLM 2: tlm_qk_dummy::tlm_quantumkeeper< Dummy > Class Template Reference
tlm_qk_dummy::tlm_quantumkeeper
tlm_qk_dummy::tlm_quantumkeeper< Dummy > Class Template Reference
#include <tlm_quantumkeeper.h>
Public Member Functions
tlm_quantumkeeper ()
virtual ~tlm_quantumkeeper ()
void inc (const sc_core::sc_time &t)
bool needSync () const
void reset ()
sc_core::sc_time getCurrentTime () const
const sc_core::sc_time & getLocalTime () const
sc_core::sc_time & getLocalTime ()
void sync ()
Static Public Member Functions
static void setGlobalQuantum (const sc_core::sc_time &t)
static const
sc_core::sc_time & getGlobalQuantum ()
Protected Member Functions
virtual void computeLocalQuantum ()
Private Attributes
sc_core::sc_time mLocalQuantum
sc_core::sc_time mLocalTime
Static Private Attributes
static sc_core::sc_time mGlobalQuantum = sc_core::SC_ZERO_TIME
Detailed Description
template<typename Dummy>
class tlm_qk_dummy::tlm_quantumkeeper< Dummy >
Definition at line 24 of file tlm_quantumkeeper.h.
Constructor & Destructor Documentation
template<typename Dummy> tlm_qk_dummy::tlm_quantumkeeper< Dummy >::tlm_quantumkeeper () [inline]
Definition at line 38 of file tlm_quantumkeeper.h.
References tlm_qk_dummy::tlm_quantumkeeper< Dummy >::computeLocalQuantum().
template<typename Dummy> virtual tlm_qk_dummy::tlm_quantumkeeper< Dummy >::~tlm_quantumkeeper () [inline, virtual]
Definition at line 44 of file tlm_quantumkeeper.h.
Member Function Documentation
template<typename Dummy> static void tlm_qk_dummy::tlm_quantumkeeper< Dummy >::setGlobalQuantum (const sc_core::sc_time & t) [inline, static]
Definition at line 27 of file tlm_quantumkeeper.h.
References tlm_qk_dummy::tlm_quantumkeeper< Dummy >::mGlobalQuantum.
template<typename Dummy> static const sc_core::sc_time& tlm_qk_dummy::tlm_quantumkeeper< Dummy >::getGlobalQuantum () [inline, static]
Definition at line 32 of file tlm_quantumkeeper.h.
References tlm_qk_dummy::tlm_quantumkeeper< Dummy >::mGlobalQuantum.
template<typename Dummy> void tlm_qk_dummy::tlm_quantumkeeper< Dummy >::inc (const sc_core::sc_time & t) [inline]
Definition at line 46 of file tlm_quantumkeeper.h.
References tlm_qk_dummy::tlm_quantumkeeper< Dummy >::mLocalTime.
template<typename Dummy> bool tlm_qk_dummy::tlm_quantumkeeper< Dummy >::needSync () const [inline]
Definition at line 51 of file tlm_quantumkeeper.h.
References tlm_qk_dummy::tlm_quantumkeeper< Dummy >::mLocalQuantum, and tlm_qk_dummy::tlm_quantumkeeper< Dummy >::mLocalTime.
template<typename Dummy> void tlm_qk_dummy::tlm_quantumkeeper< Dummy >::reset () [inline]
Definition at line 56 of file tlm_quantumkeeper.h.
References tlm_qk_dummy::tlm_quantumkeeper< Dummy >::computeLocalQuantum(), and tlm_qk_dummy::tlm_quantumkeeper< Dummy >::mLocalTime.
Referenced by tlm_qk_dummy::tlm_quantumkeeper< Dummy >::sync().
template<typename Dummy> sc_core::sc_time tlm_qk_dummy::tlm_quantumkeeper< Dummy >::getCurrentTime () const [inline]
Definition at line 62 of file tlm_quantumkeeper.h.
References tlm_qk_dummy::tlm_quantumkeeper< Dummy >::mLocalTime.
template<typename Dummy> const sc_core::sc_time& tlm_qk_dummy::tlm_quantumkeeper< Dummy >::getLocalTime () const [inline]
Definition at line 67 of file tlm_quantumkeeper.h.
References tlm_qk_dummy::tlm_quantumkeeper< Dummy >::mLocalTime.
template<typename Dummy> sc_core::sc_time& tlm_qk_dummy::tlm_quantumkeeper< Dummy >::getLocalTime () [inline]
Definition at line 72 of file tlm_quantumkeeper.h.
References tlm_qk_dummy::tlm_quantumkeeper< Dummy >::mLocalTime.
template<typename Dummy> void tlm_qk_dummy::tlm_quantumkeeper< Dummy >::sync () [inline]
Definition at line 77 of file tlm_quantumkeeper.h.
References tlm_qk_dummy::tlm_quantumkeeper< Dummy >::mLocalTime, and tlm_qk_dummy::tlm_quantumkeeper< Dummy >::reset().
template<typename Dummy> virtual void tlm_qk_dummy::tlm_quantumkeeper< Dummy >::computeLocalQuantum () [inline, protected, virtual]
Definition at line 84 of file tlm_quantumkeeper.h.
References tlm_qk_dummy::tlm_quantumkeeper< Dummy >::mGlobalQuantum, and tlm_qk_dummy::tlm_quantumkeeper< Dummy >::mLocalQuantum.
Referenced by tlm_qk_dummy::tlm_quantumkeeper< Dummy >::reset(), and tlm_qk_dummy::tlm_quantumkeeper< Dummy >::tlm_quantumkeeper().
Member Data Documentation
template<typename Dummy> sc_core::sc_time tlm_qk_dummy::tlm_quantumkeeper< Dummy >::mGlobalQuantum = sc_core::SC_ZERO_TIME [inline, static, private]
Definition at line 98 of file tlm_quantumkeeper.h.
Referenced by tlm_qk_dummy::tlm_quantumkeeper< Dummy >::computeLocalQuantum(), tlm_qk_dummy::tlm_quantumkeeper< Dummy >::getGlobalQuantum(), and tlm_qk_dummy::tlm_quantumkeeper< Dummy >::setGlobalQuantum().
template<typename Dummy> sc_core::sc_time tlm_qk_dummy::tlm_quantumkeeper< Dummy >::mLocalQuantum [private]
Definition at line 101 of file tlm_quantumkeeper.h.
Referenced by tlm_qk_dummy::tlm_quantumkeeper< Dummy >::computeLocalQuantum(), and tlm_qk_dummy::tlm_quantumkeeper< Dummy >::needSync().
template<typename Dummy> sc_core::sc_time tlm_qk_dummy::tlm_quantumkeeper< Dummy >::mLocalTime [private]
Definition at line 102 of file tlm_quantumkeeper.h.
Referenced by tlm_qk_dummy::tlm_quantumkeeper< Dummy >::getCurrentTime(), tlm_qk_dummy::tlm_quantumkeeper< Dummy >::getLocalTime(), tlm_qk_dummy::tlm_quantumkeeper< Dummy >::inc(), tlm_qk_dummy::tlm_quantumkeeper< Dummy >::needSync(), tlm_qk_dummy::tlm_quantumkeeper< Dummy >::reset(), and tlm_qk_dummy::tlm_quantumkeeper< Dummy >::sync().
The documentation for this class was generated from the following file:
C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_quantum/tlm_quantumkeeper.h