TLM 2: tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF > Class Template Reference
tlm::tlm_target_socket
tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF > Class Template Reference
#include <tlm_target_socket.h>
Public Types
typedef FW_IF fw_interface_type
typedef BW_IF bw_interface_type
typedef
sc_core::sc_port
< bw_interface_type > port_type
typedef
sc_core::sc_export
< fw_interface_type > export_type
typedef
tlm_initiator_socket
< BUSWIDTH,
fw_interface_type,
bw_interface_type > initiator_socket_type
Public Member Functions
tlm_target_socket (const char *name)
unsigned int get_bus_width () const
void bind (initiator_socket_type &s)
void operator() (initiator_socket_type &s)
void bind (tlm_target_socket &s)
void operator() (tlm_target_socket &s)
void bind (fw_interface_type &ifs)
void operator() (fw_interface_type &s)
bw_interface_type * operator-> ()
Protected Attributes
port_type mPort
Friends
class tlm_initiator_socket< BUSWIDTH, fw_interface_type, bw_interface_type >
Detailed Description
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>>
class tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF >
Definition at line 34 of file tlm_target_socket.h.
Member Typedef Documentation
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> typedef FW_IF tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF >::fw_interface_type
Definition at line 37 of file tlm_target_socket.h.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> typedef BW_IF tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF >::bw_interface_type
Definition at line 38 of file tlm_target_socket.h.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> typedef sc_core::sc_port<bw_interface_type> tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF >::port_type
Definition at line 39 of file tlm_target_socket.h.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> typedef sc_core::sc_export<fw_interface_type> tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF >::export_type
Definition at line 40 of file tlm_target_socket.h.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> typedef tlm_initiator_socket<BUSWIDTH, fw_interface_type, bw_interface_type> tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF >::initiator_socket_type
Definition at line 43 of file tlm_target_socket.h.
Constructor & Destructor Documentation
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF >::tlm_target_socket (const char * name) [inline]
Definition at line 50 of file tlm_target_socket.h.
Member Function Documentation
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> unsigned int tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF >::get_bus_width () const [inline]
Definition at line 56 of file tlm_target_socket.h.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> void tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF >::bind (initiator_socket_type & s) [inline]
Definition at line 68 of file tlm_target_socket.h.
References tlm::tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF >::mExport, and tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF >::mPort.
Referenced by tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF >::operator()().
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> void tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF >::operator() (initiator_socket_type & s) [inline]
Definition at line 76 of file tlm_target_socket.h.
References tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF >::bind().
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> void tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF >::bind (tlm_target_socket< BUSWIDTH, FW_IF, BW_IF > & s) [inline]
Definition at line 85 of file tlm_target_socket.h.
References tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF >::mPort.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> void tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF >::operator() (tlm_target_socket< BUSWIDTH, FW_IF, BW_IF > & s) [inline]
Definition at line 93 of file tlm_target_socket.h.
References tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF >::bind().
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> void tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF >::bind (fw_interface_type & ifs) [inline]
Definition at line 102 of file tlm_target_socket.h.
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> void tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF >::operator() (fw_interface_type & s) [inline]
Definition at line 107 of file tlm_target_socket.h.
References tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF >::bind().
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> bw_interface_type* tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF >::operator-> () [inline]
Definition at line 115 of file tlm_target_socket.h.
References tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF >::mPort.
Friends And Related Function Documentation
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> friend class tlm_initiator_socket< BUSWIDTH,fw_interface_type,bw_interface_type > [friend]
Definition at line 47 of file tlm_target_socket.h.
Member Data Documentation
template<unsigned int BUSWIDTH = 32, typename FW_IF = tlm_fw_nb_transport_if<>, typename BW_IF = tlm_bw_nb_transport_if<>> port_type tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF >::mPort [protected]
Definition at line 121 of file tlm_target_socket.h.
Referenced by tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF >::bind(), tlm::tlm_initiator_socket< BUSWIDTH, FW_IF, BW_IF >::bind(), and tlm::tlm_target_socket< BUSWIDTH, FW_IF, BW_IF >::operator->().
The documentation for this class was generated from the following file:
C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_trans/tlm_sockets/tlm_target_socket.h