TLM 2: tlm::tlm_target_port< IF > Class Template Reference
tlm::tlm_target_port
tlm::tlm_target_port< IF > Class Template Reference
Class tlm_target_port: port to be instantiated on the target side.
#include <tlm_target_port.h>
Public Member Functions
tlm_target_port (const char *name)
sc_export overridden methods
Need to specialize binding operation to support port propagation in transaction recorders. Specialization is done for sc_export/sc_export. Other redefinitions of bindings are just calls to regular bind function
Note: This is due to non virtual definition of SystemC bind
void before_end_of_elaboration ()
void end_of_elaboration ()
void bind (target_port_type &target_port_)
bind(sc_export) with target ports propagation
template<typename OTHER_IF>
void bind (tlm_target_port< OTHER_IF > &target_port_)
Case of the other port uses another interface as template: works only if OTHER_IF derives from IF.
void operator() (target_port_type &target_port_)
operator() (sc_export) overridden: just calls bind(sc_export)
template<typename OTHER_IF>
void operator() (tlm_target_port< OTHER_IF > &target_port_)
Case of the other port uses another interface as template: works only if OTHER_IF derives from IF.
void bind (interface_type &interface_)
bind(interface_type) overridden
void operator() (interface_type &interface_)
operator() (interface_type) overridden
Protected Member Functions
bool is_already_bound (sc_core::sc_interface *other_if)
Private Types
typedef IF interface_type
typedef
tlm_target_port< IF > target_port_type
typedef
tlm_target_port_base target_port_base_type
Detailed Description
template<typename IF>
class tlm::tlm_target_port< IF >
Class tlm_target_port: port to be instantiated on the target side.
This class could be used as base class for user defined target ports (support of user convenience layer).
It provides new binding methods definition: sc_export to sc_export binding must be identified in order create tlm_target_port_base::target_port_list used target port ID propagation through hierarchical binding; the only port ID that makes sense is the port ID of the port directly bound to the interface. An error detection is also provided: multiple interface bind declarations are not detected by sc_export (the interface is just replaced), the new binding definition issues an error message in this case.
Definition at line 45 of file tlm_target_port.h.
Member Typedef Documentation
template<typename IF> typedef IF tlm::tlm_target_port< IF >::interface_type [private]
Definition at line 49 of file tlm_target_port.h.
template<typename IF> typedef tlm_target_port<IF> tlm::tlm_target_port< IF >::target_port_type [private]
Definition at line 50 of file tlm_target_port.h.
template<typename IF> typedef tlm_target_port_base tlm::tlm_target_port< IF >::target_port_base_type [private]
Definition at line 51 of file tlm_target_port.h.
Constructor & Destructor Documentation
template<typename IF> tlm::tlm_target_port< IF >::tlm_target_port (const char * name) [inline]
Definition at line 140 of file tlm_target_port.h.
Member Function Documentation
template<typename IF> void tlm::tlm_target_port< IF >::before_end_of_elaboration () [inline]
Called just before end of elaboration to propagate the significant target port id: the only valid port id is the one set by the module which implements the tlm core interface.
Remark: sc_port_base::complete_binding should be the best place to do that but this method is private !!
Definition at line 183 of file tlm_target_port.h.
References tlm::tlm_target_port_base::get_target_port_list(), and tlm::tlm_target_port_base::set_tlm_export_id().
template<typename IF> void tlm::tlm_target_port< IF >::end_of_elaboration () [inline]
Called at the end of elaboration. Used to print debug message: content opf the target port list
Definition at line 201 of file tlm_target_port.h.
References tlm::tlm_target_port_base::get_target_port_list().
template<typename IF> void tlm::tlm_target_port< IF >::bind (target_port_type & target_port_) [inline]
bind(sc_export) with target ports propagation
Definition at line 221 of file tlm_target_port.h.
References tlm::tlm_target_port_base::get_target_port_list(), tlm::tlm_target_port< IF >::is_already_bound(), and tlm::tlm_target_port_base::register_target_port().
Referenced by tlm::tlm_target_port< IF >::operator()().
template<typename IF> template<typename OTHER_IF> void tlm::tlm_target_port< IF >::bind (tlm_target_port< OTHER_IF > & target_port_) [inline]
Case of the other port uses another interface as template: works only if OTHER_IF derives from IF.
Definition at line 242 of file tlm_target_port.h.
References tlm::tlm_target_port_base::get_target_port_list(), tlm::tlm_target_port< IF >::is_already_bound(), and tlm::tlm_target_port_base::register_target_port().
template<typename IF> void tlm::tlm_target_port< IF >::operator() (target_port_type & target_port_) [inline]
operator() (sc_export) overridden: just calls bind(sc_export)
Definition at line 101 of file tlm_target_port.h.
References tlm::tlm_target_port< IF >::bind().
template<typename IF> template<typename OTHER_IF> void tlm::tlm_target_port< IF >::operator() (tlm_target_port< OTHER_IF > & target_port_) [inline]
Case of the other port uses another interface as template: works only if OTHER_IF derives from IF.
Definition at line 107 of file tlm_target_port.h.
template<typename IF> void tlm::tlm_target_port< IF >::bind (interface_type & interface_) [inline]
bind(interface_type) overridden
Definition at line 277 of file tlm_target_port.h.
template<typename IF> void tlm::tlm_target_port< IF >::operator() (interface_type & interface_) [inline]
operator() (interface_type) overridden
Definition at line 285 of file tlm_target_port.h.
template<typename IF> bool tlm::tlm_target_port< IF >::is_already_bound (sc_core::sc_interface * other_if) [inline, protected]
Returns true and issues an error message if the port is already bound to an interface during the binding of other_if (called by bind(sc_export))
Definition at line 150 of file tlm_target_port.h.
Referenced by tlm::tlm_target_port< IF >::bind().
The documentation for this class was generated from the following file:
C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_ports/tlm_target_port.h