TLM 2: tlm_utils::instance_specific_extensions_per_accessor< U > Class Template Reference
tlm_utils::instance_specific_extensions_per_accessor
tlm_utils::instance_specific_extensions_per_accessor< U > Class Template Reference
#include <instance_specific_extensions.h>
Public Types
typedef void(U::* cb)()
Public Member Functions
instance_specific_extensions_per_accessor (U *container, cb inc, cb dec)
template<typename T>
T * set_extension (T *ext)
ispex_base * set_extension (unsigned int index, ispex_base *ext)
template<typename T>
void get_extension (T *&ext) const
ispex_base * get_extension (unsigned int index) const
template<typename T>
void clear_extension (const T *ext)
void clear_extension (unsigned int index)
void resize_extensions ()
Private Attributes
tlm::tlm_array
< ispex_base * > m_extensions
U * m_container
cb m_inc
cb m_dec
Detailed Description
template<typename U>
class tlm_utils::instance_specific_extensions_per_accessor< U >
Definition at line 101 of file instance_specific_extensions.h.
Member Typedef Documentation
template<typename U> typedef void(U::* tlm_utils::instance_specific_extensions_per_accessor< U >::cb)()
Definition at line 104 of file instance_specific_extensions.h.
Constructor & Destructor Documentation
template<typename U> tlm_utils::instance_specific_extensions_per_accessor< U >::instance_specific_extensions_per_accessor (U * container, cb inc, cb dec) [inline]
Definition at line 106 of file instance_specific_extensions.h.
Member Function Documentation
template<typename U> template<typename T> T* tlm_utils::instance_specific_extensions_per_accessor< U >::set_extension (T * ext) [inline]
Definition at line 109 of file instance_specific_extensions.h.
References tlm_utils::instance_specific_extensions_per_accessor< U >::m_container, tlm_utils::instance_specific_extensions_per_accessor< U >::m_extensions, tlm_utils::instance_specific_extensions_per_accessor< U >::m_inc, and tlm_utils::instance_specific_extensions_per_accessor< U >::resize_extensions().
template<typename U> ispex_base* tlm_utils::instance_specific_extensions_per_accessor< U >::set_extension (unsigned int index, ispex_base * ext) [inline]
Definition at line 118 of file instance_specific_extensions.h.
References tlm_utils::instance_specific_extensions_per_accessor< U >::m_container, tlm_utils::instance_specific_extensions_per_accessor< U >::m_extensions, tlm_utils::instance_specific_extensions_per_accessor< U >::m_inc, and tlm_utils::instance_specific_extensions_per_accessor< U >::resize_extensions().
template<typename U> template<typename T> void tlm_utils::instance_specific_extensions_per_accessor< U >::get_extension (T *& ext) const [inline]
Definition at line 129 of file instance_specific_extensions.h.
References tlm_utils::instance_specific_extensions_per_accessor< U >::m_extensions.
template<typename U> ispex_base* tlm_utils::instance_specific_extensions_per_accessor< U >::get_extension (unsigned int index) const [inline]
Definition at line 134 of file instance_specific_extensions.h.
References tlm_utils::instance_specific_extensions_per_accessor< U >::m_extensions.
template<typename U> template<typename T> void tlm_utils::instance_specific_extensions_per_accessor< U >::clear_extension (const T * ext) [inline]
Definition at line 140 of file instance_specific_extensions.h.
References tlm_utils::instance_specific_extensions_per_accessor< U >::m_container, tlm_utils::instance_specific_extensions_per_accessor< U >::m_dec, tlm_utils::instance_specific_extensions_per_accessor< U >::m_extensions, and tlm_utils::instance_specific_extensions_per_accessor< U >::resize_extensions().
template<typename U> void tlm_utils::instance_specific_extensions_per_accessor< U >::clear_extension (unsigned int index) [inline]
Definition at line 147 of file instance_specific_extensions.h.
References tlm_utils::instance_specific_extensions_per_accessor< U >::m_container, tlm_utils::instance_specific_extensions_per_accessor< U >::m_dec, and tlm_utils::instance_specific_extensions_per_accessor< U >::m_extensions.
template<typename U> void tlm_utils::instance_specific_extensions_per_accessor< U >::resize_extensions () [inline]
Definition at line 161 of file instance_specific_extensions.h.
References tlm_utils::instance_specific_extensions_per_accessor< U >::m_extensions, and tlm_utils::max_num_ispex().
Referenced by tlm_utils::instance_specific_extensions_per_accessor< U >::clear_extension(), and tlm_utils::instance_specific_extensions_per_accessor< U >::set_extension().
Member Data Documentation
template<typename U> tlm::tlm_array<ispex_base*> tlm_utils::instance_specific_extensions_per_accessor< U >::m_extensions [private]
Definition at line 167 of file instance_specific_extensions.h.
Referenced by tlm_utils::instance_specific_extensions_per_accessor< U >::clear_extension(), tlm_utils::instance_specific_extensions_per_accessor< U >::get_extension(), tlm_utils::instance_specific_extensions_per_accessor< U >::resize_extensions(), and tlm_utils::instance_specific_extensions_per_accessor< U >::set_extension().
template<typename U> U* tlm_utils::instance_specific_extensions_per_accessor< U >::m_container [private]
Definition at line 168 of file instance_specific_extensions.h.
Referenced by tlm_utils::instance_specific_extensions_per_accessor< U >::clear_extension(), and tlm_utils::instance_specific_extensions_per_accessor< U >::set_extension().
template<typename U> cb tlm_utils::instance_specific_extensions_per_accessor< U >::m_inc [private]
Definition at line 169 of file instance_specific_extensions.h.
Referenced by tlm_utils::instance_specific_extensions_per_accessor< U >::set_extension().
template<typename U> cb tlm_utils::instance_specific_extensions_per_accessor< U >::m_dec [private]
Definition at line 169 of file instance_specific_extensions.h.
Referenced by tlm_utils::instance_specific_extensions_per_accessor< U >::clear_extension().
The documentation for this class was generated from the following file:
C:/ESLX/projects/TLMWG/tlm2/include/tlm/tlm_utils/instance_specific_extensions.h