TLM 2: tlm_utils::simple_initiator_socket_tagged< MODULE, BUSWIDTH, TYPES > Class Template Reference
tlm_utils::simple_initiator_socket_tagged< MODULE, BUSWIDTH, TYPES > Class Template Reference
#include <simple_initiator_socket.h>
Inherits tlm_initiator_socket< BUSWIDTH, TYPES >.
Classes
class process
Public Types
typedef TYPES::tlm_payload_type transaction_type
typedef TYPES::tlm_phase_type phase_type
typedef tlm::tlm_sync_enum sync_enum_type
typedef
tlm::tlm_fw_transport_if
< TYPES > fw_interface_type
typedef
tlm::tlm_bw_transport_if
< TYPES > bw_interface_type
typedef
tlm::tlm_initiator_socket
< BUSWIDTH, TYPES > base_type
Public Member Functions
simple_initiator_socket_tagged ()
simple_initiator_socket_tagged (const char *n)
void register_nb_transport_bw (MODULE *mod, sync_enum_type(MODULE::*cb)(int, transaction_type &, phase_type &, sc_core::sc_time &), int id)
void register_invalidate_direct_mem_ptr (MODULE *mod, void(MODULE::*cb)(int, sc_dt::uint64, sc_dt::uint64), int id)
Private Attributes
process m_process
Detailed Description
template<typename MODULE, unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types>
class tlm_utils::simple_initiator_socket_tagged< MODULE, BUSWIDTH, TYPES >
Definition at line 154 of file simple_initiator_socket.h.
Member Typedef Documentation
template<typename MODULE , unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types> typedef tlm::tlm_initiator_socket<BUSWIDTH, TYPES> tlm_utils::simple_initiator_socket_tagged< MODULE, BUSWIDTH, TYPES >::base_type
Reimplemented from tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, 1,sc_core::SC_ONE_OR_MORE_BOUND >.
Definition at line 163 of file simple_initiator_socket.h.
template<typename MODULE , unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types> typedef tlm::tlm_bw_transport_if<TYPES> tlm_utils::simple_initiator_socket_tagged< MODULE, BUSWIDTH, TYPES >::bw_interface_type
Reimplemented from tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, 1,sc_core::SC_ONE_OR_MORE_BOUND >.
Definition at line 162 of file simple_initiator_socket.h.
template<typename MODULE , unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types> typedef tlm::tlm_fw_transport_if<TYPES> tlm_utils::simple_initiator_socket_tagged< MODULE, BUSWIDTH, TYPES >::fw_interface_type
Reimplemented from tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, 1,sc_core::SC_ONE_OR_MORE_BOUND >.
Definition at line 161 of file simple_initiator_socket.h.
template<typename MODULE , unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types> typedef TYPES::tlm_phase_type tlm_utils::simple_initiator_socket_tagged< MODULE, BUSWIDTH, TYPES >::phase_type
Definition at line 159 of file simple_initiator_socket.h.
template<typename MODULE , unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types> typedef tlm::tlm_sync_enum tlm_utils::simple_initiator_socket_tagged< MODULE, BUSWIDTH, TYPES >::sync_enum_type
Definition at line 160 of file simple_initiator_socket.h.
template<typename MODULE , unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types> typedef TYPES::tlm_payload_type tlm_utils::simple_initiator_socket_tagged< MODULE, BUSWIDTH, TYPES >::transaction_type
Definition at line 158 of file simple_initiator_socket.h.
Constructor & Destructor Documentation
template<typename MODULE , unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types> tlm_utils::simple_initiator_socket_tagged< MODULE, BUSWIDTH, TYPES >::simple_initiator_socket_tagged () [inline]
Definition at line 166 of file simple_initiator_socket.h.
References tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, 1,sc_core::SC_ONE_OR_MORE_BOUND >::m_export, and tlm_utils::simple_initiator_socket_tagged< MODULE, BUSWIDTH, TYPES >::m_process.
template<typename MODULE , unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types> tlm_utils::simple_initiator_socket_tagged< MODULE, BUSWIDTH, TYPES >::simple_initiator_socket_tagged (const char * n) [inline, explicit]
Definition at line 173 of file simple_initiator_socket.h.
References tlm::tlm_base_initiator_socket< BUSWIDTH, tlm_fw_transport_if< TYPES >, tlm_bw_transport_if< TYPES >, 1,sc_core::SC_ONE_OR_MORE_BOUND >::m_export, and tlm_utils::simple_initiator_socket_tagged< MODULE, BUSWIDTH, TYPES >::m_process.
Member Function Documentation
template<typename MODULE , unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types> void tlm_utils::simple_initiator_socket_tagged< MODULE, BUSWIDTH, TYPES >::register_invalidate_direct_mem_ptr (MODULE * mod, void(MODULE::*)(int, sc_dt::uint64, sc_dt::uint64) cb, int id) [inline]
Definition at line 191 of file simple_initiator_socket.h.
References tlm_utils::simple_initiator_socket_tagged< MODULE, BUSWIDTH, TYPES >::m_process, tlm_utils::simple_initiator_socket_tagged< MODULE, BUSWIDTH, TYPES >::simple_initiator_socket_tagged::process::set_invalidate_direct_mem_ptr(), and tlm_utils::simple_initiator_socket_tagged< MODULE, BUSWIDTH, TYPES >::simple_initiator_socket_tagged::process::set_invalidate_dmi_user_id().
template<typename MODULE , unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types> void tlm_utils::simple_initiator_socket_tagged< MODULE, BUSWIDTH, TYPES >::register_nb_transport_bw (MODULE * mod, sync_enum_type(MODULE::*)(int, transaction_type &, phase_type &, sc_core::sc_time &) cb, int id) [inline]
Definition at line 180 of file simple_initiator_socket.h.
References tlm_utils::simple_initiator_socket_tagged< MODULE, BUSWIDTH, TYPES >::m_process, tlm_utils::simple_initiator_socket_tagged< MODULE, BUSWIDTH, TYPES >::simple_initiator_socket_tagged::process::set_transport_ptr(), and tlm_utils::simple_initiator_socket_tagged< MODULE, BUSWIDTH, TYPES >::simple_initiator_socket_tagged::process::set_transport_user_id().
Member Data Documentation
template<typename MODULE , unsigned int BUSWIDTH = 32, typename TYPES = tlm::tlm_base_protocol_types> process tlm_utils::simple_initiator_socket_tagged< MODULE, BUSWIDTH, TYPES >::m_process [private]
Definition at line 285 of file simple_initiator_socket.h.
Referenced by tlm_utils::simple_initiator_socket_tagged< MODULE, BUSWIDTH, TYPES >::register_invalidate_direct_mem_ptr(), tlm_utils::simple_initiator_socket_tagged< MODULE, BUSWIDTH, TYPES >::register_nb_transport_bw(), and tlm_utils::simple_initiator_socket_tagged< MODULE, BUSWIDTH, TYPES >::simple_initiator_socket_tagged().
The documentation for this class was generated from the following file:
include/tlm/tlm_utils/simple_initiator_socket.h