TLM 2: tlm::tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL > Class Template Reference
tlm::tlm_transport_channel
tlm::tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL > Class Template Reference
#include <tlm_req_rsp_channels.h>
Public Member Functions
tlm_transport_channel ()
tlm_transport_channel (sc_core::sc_module_name nm)
Public Attributes
sc_core::sc_export
< tlm_transport_if
< REQ, RSP > > target_export
sc_core::sc_export
< tlm_fifo_get_if
< REQ > > get_request_export
sc_core::sc_export
< tlm_fifo_put_if
< RSP > > put_response_export
sc_core::sc_export
< tlm_slave_if< REQ,
RSP > > slave_export
Private Member Functions
void do_binding ()
Private Attributes
tlm_req_rsp_channel
< REQ, RSP,
REQ_CHANNEL,
RSP_CHANNEL > req_rsp
tlm_transport_to_master
< REQ, RSP > t2m
Detailed Description
template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_fifo<REQ>, typename RSP_CHANNEL = tlm_fifo<RSP>>
class tlm::tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >
Definition at line 100 of file tlm_req_rsp_channels.h.
Constructor & Destructor Documentation
template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_fifo<REQ>, typename RSP_CHANNEL = tlm_fifo<RSP>> tlm::tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::tlm_transport_channel () [inline]
Definition at line 115 of file tlm_req_rsp_channels.h.
References tlm::tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::do_binding().
template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_fifo<REQ>, typename RSP_CHANNEL = tlm_fifo<RSP>> tlm::tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::tlm_transport_channel (sc_core::sc_module_name nm) [inline]
Definition at line 124 of file tlm_req_rsp_channels.h.
References tlm::tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::do_binding().
Member Function Documentation
template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_fifo<REQ>, typename RSP_CHANNEL = tlm_fifo<RSP>> void tlm::tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::do_binding () [inline, private]
Definition at line 134 of file tlm_req_rsp_channels.h.
References tlm::tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::get_request_export, tlm::tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::put_response_export, tlm::tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::req_rsp, tlm::tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::slave_export, tlm::tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::t2m, and tlm::tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::target_export.
Referenced by tlm::tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::tlm_transport_channel().
Member Data Documentation
template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_fifo<REQ>, typename RSP_CHANNEL = tlm_fifo<RSP>> sc_core::sc_export< tlm_transport_if< REQ , RSP > > tlm::tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::target_export
Definition at line 106 of file tlm_req_rsp_channels.h.
Referenced by tlm::tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::do_binding().
template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_fifo<REQ>, typename RSP_CHANNEL = tlm_fifo<RSP>> sc_core::sc_export< tlm_fifo_get_if< REQ > > tlm::tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::get_request_export
Definition at line 110 of file tlm_req_rsp_channels.h.
Referenced by tlm::tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::do_binding().
template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_fifo<REQ>, typename RSP_CHANNEL = tlm_fifo<RSP>> sc_core::sc_export< tlm_fifo_put_if< RSP > > tlm::tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::put_response_export
Definition at line 111 of file tlm_req_rsp_channels.h.
Referenced by tlm::tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::do_binding().
template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_fifo<REQ>, typename RSP_CHANNEL = tlm_fifo<RSP>> sc_core::sc_export< tlm_slave_if< REQ , RSP > > tlm::tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::slave_export
Definition at line 113 of file tlm_req_rsp_channels.h.
Referenced by tlm::tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::do_binding().
template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_fifo<REQ>, typename RSP_CHANNEL = tlm_fifo<RSP>> tlm_req_rsp_channel< REQ , RSP , REQ_CHANNEL , RSP_CHANNEL > tlm::tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::req_rsp [private]
Definition at line 146 of file tlm_req_rsp_channels.h.
Referenced by tlm::tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::do_binding().
template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_fifo<REQ>, typename RSP_CHANNEL = tlm_fifo<RSP>> tlm_transport_to_master< REQ , RSP > tlm::tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::t2m [private]
Definition at line 147 of file tlm_req_rsp_channels.h.
Referenced by tlm::tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::do_binding().
The documentation for this class was generated from the following file:
C:/ESLX/projects/TLMWG/tlm2/include/tlm/tlm_h/tlm_req_rsp/tlm_channels/tlm_req_rsp_channels/tlm_req_rsp_channels.h