TLM 2: tlm::tlm_target_port_base Class Reference
tlm::tlm_target_port_base
tlm::tlm_target_port_base Class Reference
Class tlm_target_port_base: This class is a base class for tlm_target port class.
#include <tlm_target_port_base.h>
Public Member Functions
tlm_target_port_base ()
Data members access methods
int get_tlm_export_id () const
Returns the port id.
void set_tlm_export_id (int tlm_export_id)
Sets the port id.
void register_target_port (this_type *target_port)
Register the target port.
std::vector
< this_type * > & get_target_port_list ()
Returns the vector of registered target port(s).
void set_target_port_list (std::vector< this_type * > &target_port_list)
Sets the vector of registered target port(s) (port propagation).
Protected Attributes
int m_tlm_export_id
Port instance ID.
std::vector
< this_type * > m_target_port_list
target port objects registration
Private Types
typedef
tlm_target_port_base this_type
Detailed Description
Class tlm_target_port_base: This class is a base class for tlm_target port class.
It provides a container to store registered target ports as pointer list.
In addition, it provides a target port ID used by to identify the input export port. This ID is injected in the request structure by the initiator at run time.
Accessors are provided for the port list and port ID.
Definition at line 42 of file tlm_target_port_base.h.
Member Typedef Documentation
typedef tlm_target_port_base tlm::tlm_target_port_base::this_type [private]
Definition at line 44 of file tlm_target_port_base.h.
Constructor & Destructor Documentation
tlm::tlm_target_port_base::tlm_target_port_base () [inline]
Definition at line 51 of file tlm_target_port_base.h.
References m_target_port_list.
Member Function Documentation
int tlm::tlm_target_port_base::get_tlm_export_id () const [inline]
Returns the port id.
Definition at line 62 of file tlm_target_port_base.h.
References m_tlm_export_id.
void tlm::tlm_target_port_base::set_tlm_export_id (int tlm_export_id) [inline]
Sets the port id.
Definition at line 67 of file tlm_target_port_base.h.
References m_tlm_export_id.
Referenced by tlm::tlm_target_port< IF >::before_end_of_elaboration().
void tlm::tlm_target_port_base::register_target_port (this_type * target_port) [inline]
Register the target port.
Definition at line 75 of file tlm_target_port_base.h.
References m_target_port_list.
Referenced by tlm::tlm_target_port< IF >::bind().
std::vector<this_type *>& tlm::tlm_target_port_base::get_target_port_list () [inline]
Returns the vector of registered target port(s).
Definition at line 80 of file tlm_target_port_base.h.
References m_target_port_list.
Referenced by tlm::tlm_target_port< IF >::before_end_of_elaboration(), tlm::tlm_target_port< IF >::bind(), and tlm::tlm_target_port< IF >::end_of_elaboration().
void tlm::tlm_target_port_base::set_target_port_list (std::vector< this_type * > & target_port_list) [inline]
Sets the vector of registered target port(s) (port propagation).
Definition at line 85 of file tlm_target_port_base.h.
References m_target_port_list.
Member Data Documentation
int tlm::tlm_target_port_base::m_tlm_export_id [protected]
Port instance ID.
Definition at line 95 of file tlm_target_port_base.h.
Referenced by get_tlm_export_id(), and set_tlm_export_id().
std::vector<this_type *> tlm::tlm_target_port_base::m_target_port_list [protected]
target port objects registration
Direct registration of the target port(s) into current target port.
Used for transaction recording and target port id propagation in case of target port binding through a module hierarchy
Definition at line 103 of file tlm_target_port_base.h.
Referenced by get_target_port_list(), register_target_port(), set_target_port_list(), and tlm_target_port_base().
The documentation for this class was generated from the following file:
C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_ports/tlm_target_port_base.h