TLM 2: tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy > Class Template Reference
tlm::tlm_qk_internal::tlm_quantumkeeper
tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy > Class Template Reference
#include <tlm_quantumkeeper.h>
Public Member Functions
tlm_quantumkeeper ()
virtual ~tlm_quantumkeeper ()
void inc (const sc_core::sc_time &t)
bool need_sync () const
void sync ()
void reset ()
sc_core::sc_time get_current_time () const
const sc_core::sc_time & get_local_time () const
sc_core::sc_time & get_local_time ()
Static Public Member Functions
static void set_global_quantum (const sc_core::sc_time &t)
static const
sc_core::sc_time & get_global_quantum ()
Protected Member Functions
virtual sc_core::sc_time compute_local_quantum ()
Protected Attributes
sc_core::sc_time mLocalQuantum
sc_core::sc_time mLocalTime
Static Private Attributes
static sc_core::sc_time mGlobalQuantum = sc_core::SC_ZERO_TIME
Detailed Description
template<typename Dummy>
class tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >
Definition at line 44 of file tlm_quantumkeeper.h.
Constructor & Destructor Documentation
template<typename Dummy> tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::tlm_quantumkeeper () [inline]
Definition at line 65 of file tlm_quantumkeeper.h.
References tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::compute_local_quantum(), and tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::mLocalQuantum.
template<typename Dummy> virtual tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::~tlm_quantumkeeper () [inline, virtual]
Definition at line 71 of file tlm_quantumkeeper.h.
Member Function Documentation
template<typename Dummy> static void tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::set_global_quantum (const sc_core::sc_time & t) [inline, static]
Definition at line 54 of file tlm_quantumkeeper.h.
References tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::mGlobalQuantum.
template<typename Dummy> static const sc_core::sc_time& tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::get_global_quantum () [inline, static]
Definition at line 59 of file tlm_quantumkeeper.h.
References tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::mGlobalQuantum.
template<typename Dummy> void tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::inc (const sc_core::sc_time & t) [inline]
Definition at line 78 of file tlm_quantumkeeper.h.
References tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::mLocalTime.
template<typename Dummy> bool tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::need_sync () const [inline]
Definition at line 88 of file tlm_quantumkeeper.h.
References tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::mLocalQuantum, and tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::mLocalTime.
template<typename Dummy> void tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::sync () [inline]
Definition at line 98 of file tlm_quantumkeeper.h.
References tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::mLocalTime, and tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::reset().
template<typename Dummy> void tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::reset () [inline]
Definition at line 110 of file tlm_quantumkeeper.h.
References tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::compute_local_quantum(), tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::mLocalQuantum, and tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::mLocalTime.
Referenced by tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::sync().
template<typename Dummy> sc_core::sc_time tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::get_current_time () const [inline]
Definition at line 122 of file tlm_quantumkeeper.h.
References tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::mLocalTime.
template<typename Dummy> const sc_core::sc_time& tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::get_local_time () const [inline]
Definition at line 132 of file tlm_quantumkeeper.h.
References tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::mLocalTime.
template<typename Dummy> sc_core::sc_time& tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::get_local_time () [inline]
Definition at line 137 of file tlm_quantumkeeper.h.
References tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::mLocalTime.
template<typename Dummy> virtual sc_core::sc_time tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::compute_local_quantum () [inline, protected, virtual]
Definition at line 155 of file tlm_quantumkeeper.h.
References tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::mGlobalQuantum.
Referenced by tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::reset(), and tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::tlm_quantumkeeper().
Member Data Documentation
template<typename Dummy> sc_core::sc_time tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::mGlobalQuantum = sc_core::SC_ZERO_TIME [inline, static, private]
Definition at line 171 of file tlm_quantumkeeper.h.
Referenced by tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::compute_local_quantum(), tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::get_global_quantum(), and tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::set_global_quantum().
template<typename Dummy> sc_core::sc_time tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::mLocalQuantum [protected]
Definition at line 174 of file tlm_quantumkeeper.h.
Referenced by tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::need_sync(), tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::reset(), and tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::tlm_quantumkeeper().
template<typename Dummy> sc_core::sc_time tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::mLocalTime [protected]
Definition at line 175 of file tlm_quantumkeeper.h.
Referenced by tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::get_current_time(), tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::get_local_time(), tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::inc(), tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::need_sync(), tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::reset(), and tlm::tlm_qk_internal::tlm_quantumkeeper< Dummy >::sync().
The documentation for this class was generated from the following file:
C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_quantum/tlm_quantumkeeper.h