TLM 2: tlm_array< T > Class Template Reference
tlm_array< T > Class Template Reference
#include <tlm_array.h>
Public Member Functions
tlm_array (unsigned int size=0, T default_value=0)
tlm_array (const tlm_array &orig)
~tlm_array ()
T & operator[] (const unsigned int index)
const T & operator[] (const unsigned int index) const
unsigned int size () const
void expand (unsigned int new_size)
const char * kind () const
Static Public Attributes
static const char *const kind_string = "tlm_array"
Protected Member Functions
tlm_array & operator= (const tlm_array< T > &)
void report_error (std::exception &e)
Protected Attributes
T * m_data
unsigned int m_size
T m_default
Detailed Description
template<typename T>
class tlm_array< T >
Definition at line 44 of file tlm_array.h.
Constructor & Destructor Documentation
template<typename T> tlm_array< T >::tlm_array (unsigned int size = 0, T default_value = 0) [inline]
Definition at line 49 of file tlm_array.h.
template<typename T> tlm_array< T >::tlm_array (const tlm_array< T > & orig) [inline]
Definition at line 58 of file tlm_array.h.
template<typename T> tlm_array< T >::~tlm_array () [inline]
Definition at line 77 of file tlm_array.h.
Member Function Documentation
template<typename T> T& tlm_array< T >::operator[] (const unsigned int index) [inline]
Definition at line 84 of file tlm_array.h.
template<typename T> const T& tlm_array< T >::operator[] (const unsigned int index) const [inline]
Definition at line 89 of file tlm_array.h.
template<typename T> unsigned int tlm_array< T >::size () const [inline]
Definition at line 96 of file tlm_array.h.
Referenced by tlm_generic_payload::clear_extension(), and tlm_array< tlm_extension_base * >::tlm_array().
template<typename T> void tlm_array< T >::expand (unsigned int new_size) [inline]
Definition at line 99 of file tlm_array.h.
Referenced by tlm_generic_payload::resize_extensions(), and tlm_array< tlm_extension_base * >::tlm_array().
template<typename T> const char* tlm_array< T >::kind () const [inline]
Definition at line 142 of file tlm_array.h.
template<typename T> tlm_array& tlm_array< T >::operator= (const tlm_array< T > &) [protected]
template<typename T> void tlm_array< T >::report_error (std::exception & e) [inline, protected]
Definition at line 153 of file tlm_array.h.
Referenced by tlm_array< tlm_extension_base * >::expand(), and tlm_array< tlm_extension_base * >::tlm_array().
Member Data Documentation
template<typename T> const char *const tlm_array< T >::kind_string = "tlm_array" [inline, static]
Definition at line 141 of file tlm_array.h.
Referenced by tlm_array< tlm_extension_base * >::kind(), and tlm_array< tlm_extension_base * >::report_error().
template<typename T> T* tlm_array< T >::m_data [protected]
Definition at line 145 of file tlm_array.h.
Referenced by tlm_array< tlm_extension_base * >::expand(), tlm_array< tlm_extension_base * >::operator[](), tlm_array< tlm_extension_base * >::tlm_array(), and tlm_array< tlm_extension_base * >::~tlm_array().
template<typename T> unsigned int tlm_array< T >::m_size [protected]
Definition at line 146 of file tlm_array.h.
Referenced by tlm_array< tlm_extension_base * >::expand(), tlm_array< tlm_extension_base * >::size(), tlm_array< tlm_extension_base * >::tlm_array(), and tlm_array< tlm_extension_base * >::~tlm_array().
template<typename T> T tlm_array< T >::m_default [protected]
Definition at line 147 of file tlm_array.h.
Referenced by tlm_array< tlm_extension_base * >::expand().
The documentation for this class was generated from the following file:
C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_generic_payload/tlm_array.h