TLM 2: tlm_annotated_fifo< T > Class Template Reference
tlm_annotated_fifo< T > Class Template Reference
#include <tlm_annotated_fifo.h>
Public Member Functions
tlm_annotated_fifo (sc_module_name nm, int size=1)
tlm_annotated_fifo (int size=1)
bool nb_can_put (tlm_tag< T > *t=0) const
bool nb_can_get (tlm_tag< T > *t=0) const
bool nb_can_peek (tlm_tag< T > *t=0) const
virtual bool nb_can_put (const sc_time &time, tlm_tag< T > *t=0) const
virtual bool nb_can_get (const sc_time &time, tlm_tag< T > *t=0) const
const sc_event & ok_to_put (tlm_tag< T > *t=0) const
const sc_event & ok_to_get (tlm_tag< T > *t=0) const
const sc_event & ok_to_peek (tlm_tag< T > *t=0) const
bool nb_put (const T &t)
bool nb_get (T &t)
bool nb_peek (T &t) const
bool nb_put (const T &transaction, const sc_time &time)
virtual bool nb_get (T &transaction, const sc_time &time)
void put (const T &t)
T get (tlm_tag< T > *t=0)
T peek (tlm_tag< T > *t=0) const
int size ()
Protected Attributes
tlm_internal_annotated_fifo
< T > m_fifo
tlm_peq< T > m_put_peq
tlm_peq< tlm_tag< T > * > m_get_peq
Private Attributes
int m_size
Detailed Description
template<typename T>
class tlm_annotated_fifo< T >
Definition at line 60 of file tlm_annotated_fifo.h.
Constructor & Destructor Documentation
template<typename T> tlm_annotated_fifo< T >::tlm_annotated_fifo (sc_module_name nm, int size = 1) [inline]
Definition at line 67 of file tlm_annotated_fifo.h.
References tlm_peq< T >::ap, tlm_annotated_fifo< T >::m_fifo, tlm_annotated_fifo< T >::m_get_peq, and tlm_annotated_fifo< T >::m_put_peq.
template<typename T> tlm_annotated_fifo< T >::tlm_annotated_fifo (int size = 1) [inline]
Definition at line 79 of file tlm_annotated_fifo.h.
References tlm_peq< T >::ap, tlm_annotated_fifo< T >::m_fifo, tlm_annotated_fifo< T >::m_get_peq, and tlm_annotated_fifo< T >::m_put_peq.
Member Function Documentation
template<typename T> bool tlm_annotated_fifo< T >::nb_can_put (tlm_tag< T > * t = 0) const [inline, virtual]
Implements tlm_core::tlm_nonblocking_put_if< T >.
Definition at line 92 of file tlm_annotated_fifo.h.
References tlm_annotated_fifo< T >::m_fifo, tlm_annotated_fifo< T >::m_get_peq, tlm_annotated_fifo< T >::m_put_peq, and tlm_peq< T >::size().
Referenced by tlm_annotated_fifo< T >::nb_can_put(), and tlm_annotated_fifo< T >::nb_put().
template<typename T> bool tlm_annotated_fifo< T >::nb_can_get (tlm_tag< T > * t = 0) const [inline, virtual]
Implements tlm_core::tlm_nonblocking_get_if< T >.
Definition at line 96 of file tlm_annotated_fifo.h.
References tlm_annotated_fifo< T >::m_fifo.
Referenced by tlm_annotated_fifo< T >::nb_can_get(), and tlm_annotated_fifo< T >::nb_get().
template<typename T> bool tlm_annotated_fifo< T >::nb_can_peek (tlm_tag< T > * t = 0) const [inline, virtual]
Implements tlm_core::tlm_nonblocking_peek_if< T >.
Definition at line 100 of file tlm_annotated_fifo.h.
References tlm_annotated_fifo< T >::m_fifo.
template<typename T> virtual bool tlm_annotated_fifo< T >::nb_can_put (const sc_time & time, tlm_tag< T > * t = 0) const [inline, virtual]
Implements tlm_annotated_nonblocking_put_if< T >.
Definition at line 115 of file tlm_annotated_fifo.h.
References tlm_annotated_fifo< T >::nb_can_put().
template<typename T> virtual bool tlm_annotated_fifo< T >::nb_can_get (const sc_time & time, tlm_tag< T > * t = 0) const [inline, virtual]
Implements tlm_annotated_nonblocking_get_if< T >.
Definition at line 119 of file tlm_annotated_fifo.h.
References tlm_annotated_fifo< T >::nb_can_get().
template<typename T> const sc_event& tlm_annotated_fifo< T >::ok_to_put (tlm_tag< T > * t = 0) const [inline, virtual]
Implements tlm_core::tlm_nonblocking_put_if< T >.
Definition at line 125 of file tlm_annotated_fifo.h.
References tlm_annotated_fifo< T >::m_fifo.
Referenced by tlm_annotated_fifo< T >::put().
template<typename T> const sc_event& tlm_annotated_fifo< T >::ok_to_get (tlm_tag< T > * t = 0) const [inline, virtual]
Implements tlm_core::tlm_nonblocking_get_if< T >.
Definition at line 129 of file tlm_annotated_fifo.h.
References tlm_annotated_fifo< T >::m_fifo.
Referenced by tlm_annotated_fifo< T >::get().
template<typename T> const sc_event& tlm_annotated_fifo< T >::ok_to_peek (tlm_tag< T > * t = 0) const [inline, virtual]
Implements tlm_core::tlm_nonblocking_peek_if< T >.
Definition at line 133 of file tlm_annotated_fifo.h.
References tlm_annotated_fifo< T >::m_fifo.
template<typename T> bool tlm_annotated_fifo< T >::nb_put (const T & t) [inline, virtual]
Implements tlm_core::tlm_nonblocking_put_if< T >.
Definition at line 139 of file tlm_annotated_fifo.h.
References tlm_annotated_fifo< T >::m_fifo, and tlm_annotated_fifo< T >::nb_can_put().
Referenced by tlm_annotated_fifo< T >::put().
template<typename T> bool tlm_annotated_fifo< T >::nb_get (T & t) [inline, virtual]
Implements tlm_core::tlm_nonblocking_get_if< T >.
Definition at line 151 of file tlm_annotated_fifo.h.
References tlm_annotated_fifo< T >::m_fifo, and tlm_annotated_fifo< T >::nb_can_get().
Referenced by tlm_annotated_fifo< T >::get().
template<typename T> bool tlm_annotated_fifo< T >::nb_peek (T & t) const [inline, virtual]
Implements tlm_core::tlm_nonblocking_peek_if< T >.
Definition at line 163 of file tlm_annotated_fifo.h.
References tlm_annotated_fifo< T >::m_fifo.
template<typename T> bool tlm_annotated_fifo< T >::nb_put (const T & transaction, const sc_time & time) [inline, virtual]
Implements tlm_annotated_nonblocking_put_if< T >.
Definition at line 170 of file tlm_annotated_fifo.h.
References tlm_annotated_fifo< T >::m_put_peq, and tlm_annotated_fifo< T >::nb_can_put().
template<typename T> virtual bool tlm_annotated_fifo< T >::nb_get (T & transaction, const sc_time & time) [inline, virtual]
Implements tlm_annotated_nonblocking_get_if< T >.
Definition at line 181 of file tlm_annotated_fifo.h.
References tlm_annotated_fifo< T >::m_fifo, tlm_annotated_fifo< T >::m_get_peq, and tlm_peq< T >::write().
template<typename T> void tlm_annotated_fifo< T >::put (const T & t) [inline, virtual]
Implements tlm_core::tlm_blocking_put_if< T >.
Definition at line 195 of file tlm_annotated_fifo.h.
References tlm_annotated_fifo< T >::nb_put(), and tlm_annotated_fifo< T >::ok_to_put().
template<typename T> T tlm_annotated_fifo< T >::get (tlm_tag< T > * t = 0) [inline, virtual]
Implements tlm_core::tlm_blocking_get_if< T >.
Definition at line 201 of file tlm_annotated_fifo.h.
References tlm_annotated_fifo< T >::nb_get(), and tlm_annotated_fifo< T >::ok_to_get().
template<typename T> T tlm_annotated_fifo< T >::peek (tlm_tag< T > * t = 0) const [inline, virtual]
Implements tlm_core::tlm_blocking_peek_if< T >.
Definition at line 212 of file tlm_annotated_fifo.h.
References tlm_annotated_fifo< T >::m_fifo.
template<typename T> int tlm_annotated_fifo< T >::size () [inline]
Definition at line 216 of file tlm_annotated_fifo.h.
References tlm_annotated_fifo< T >::m_size.
Member Data Documentation
template<typename T> int tlm_annotated_fifo< T >::m_size [private]
Definition at line 219 of file tlm_annotated_fifo.h.
Referenced by tlm_annotated_fifo< T >::size().
template<typename T> tlm_internal_annotated_fifo<T> tlm_annotated_fifo< T >::m_fifo [protected]
Definition at line 223 of file tlm_annotated_fifo.h.
Referenced by tlm_annotated_fifo< T >::nb_can_get(), tlm_annotated_fifo< T >::nb_can_peek(), tlm_annotated_fifo< T >::nb_can_put(), tlm_annotated_fifo< T >::nb_get(), tlm_annotated_fifo< T >::nb_peek(), tlm_annotated_fifo< T >::nb_put(), tlm_annotated_fifo< T >::ok_to_get(), tlm_annotated_fifo< T >::ok_to_peek(), tlm_annotated_fifo< T >::ok_to_put(), tlm_annotated_fifo< T >::peek(), and tlm_annotated_fifo< T >::tlm_annotated_fifo().
template<typename T> tlm_peq<T> tlm_annotated_fifo< T >::m_put_peq [protected]
Definition at line 225 of file tlm_annotated_fifo.h.
Referenced by tlm_annotated_fifo< T >::nb_can_put(), tlm_annotated_fifo< T >::nb_put(), and tlm_annotated_fifo< T >::tlm_annotated_fifo().
template<typename T> tlm_peq< tlm_tag<T> *> tlm_annotated_fifo< T >::m_get_peq [protected]
Definition at line 226 of file tlm_annotated_fifo.h.
Referenced by tlm_annotated_fifo< T >::nb_can_put(), tlm_annotated_fifo< T >::nb_get(), and tlm_annotated_fifo< T >::tlm_annotated_fifo().
The documentation for this class was generated from the following file:
C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_annotated/tlm_annotated_channels/tlm_annotated_fifo.h