TLM 2: tlm_utils::instance_specific_extension_container_pool Class Reference
tlm_utils::instance_specific_extension_container_pool
tlm_utils::instance_specific_extension_container_pool Class Reference
#include <instance_specific_extensions.h>
Private Member Functions
instance_specific_extension_container_pool ()
~instance_specific_extension_container_pool ()
instance_specific_extension_container * create ()
void free (instance_specific_extension_container *)
Static Private Member Functions
static
instance_specific_extension_container_pool & get_ispexcont_pool ()
Private Attributes
instance_specific_extension_container * unused
Friends
class instance_specific_extension_carrier
class instance_specific_extension_container
Detailed Description
Definition at line 177 of file instance_specific_extensions.h.
Constructor & Destructor Documentation
tlm_utils::instance_specific_extension_container_pool::instance_specific_extension_container_pool () [inline, private]
Definition at line 180 of file instance_specific_extensions.h.
tlm_utils::instance_specific_extension_container_pool::~instance_specific_extension_container_pool () [inline, private]
Definition at line 229 of file instance_specific_extensions.h.
References tlm_utils::instance_specific_extension_container::next, and unused.
Member Function Documentation
static instance_specific_extension_container_pool& tlm_utils::instance_specific_extension_container_pool::get_ispexcont_pool () [inline, static, private]
Definition at line 182 of file instance_specific_extensions.h.
Referenced by tlm_utils::instance_specific_extension_container::dec_use_count(), and tlm_utils::instance_specific_extension_carrier::instance_specific_extension_carrier().
instance_specific_extension_container * tlm_utils::instance_specific_extension_container_pool::create () [inline, private]
Definition at line 233 of file instance_specific_extensions.h.
References instance_specific_extension_container, tlm_utils::instance_specific_extension_container::next, and unused.
Referenced by tlm_utils::instance_specific_extension_carrier::instance_specific_extension_carrier().
void tlm_utils::instance_specific_extension_container_pool::free (instance_specific_extension_container * cont) [inline, private]
Definition at line 240 of file instance_specific_extensions.h.
References tlm_utils::instance_specific_extension_container::next, and unused.
Referenced by tlm_utils::instance_specific_extension_container::dec_use_count().
Friends And Related Function Documentation
friend class instance_specific_extension_carrier [friend]
Definition at line 178 of file instance_specific_extensions.h.
friend class instance_specific_extension_container [friend]
Definition at line 179 of file instance_specific_extensions.h.
Referenced by create().
Member Data Documentation
instance_specific_extension_container* tlm_utils::instance_specific_extension_container_pool::unused [private]
Definition at line 186 of file instance_specific_extensions.h.
Referenced by create(), free(), and ~instance_specific_extension_container_pool().
The documentation for this class was generated from the following file:
C:/ESLX/projects/TLMWG/tlm2/include/tlm/tlm_utils/instance_specific_extensions.h