TLM 2: circular_buffer< T > Class Template Reference
circular_buffer< T > Class Template Reference
#include <circular_buffer.h>
Public Member Functions
circular_buffer (int size)
circular_buffer< T > & operator= (const circular_buffer< T > &)
~circular_buffer ()
void resize (int size)
const T & read ()
void write (const T &)
bool is_empty () const
bool is_full () const
int size () const
int used () const
int free () const
T & write_data ()
const T & read_data () const
const T & peek_data (int i) const
T & poke_data (int i)
void increment_write_pos (int i=1)
void increment_read_pos (int i=1)
void init ()
void debug () const
Private Member Functions
circular_buffer (const circular_buffer< T > &b)
void copy (const circular_buffer< T > &b)
Private Attributes
int m_size
T * m_buf
int m_free
int m_used
int m_ri
int m_wi
Detailed Description
template<typename T>
class circular_buffer< T >
Definition at line 32 of file circular_buffer.h.
Constructor & Destructor Documentation
template<typename T> circular_buffer< T >::circular_buffer (int size) [inline]
Definition at line 114 of file circular_buffer.h.
References circular_buffer< T >::init(), circular_buffer< T >::m_buf, and circular_buffer< T >::m_size.
template<typename T> circular_buffer< T >::~circular_buffer () [inline]
Definition at line 39 of file circular_buffer.h.
References circular_buffer< T >::m_buf.
template<typename T> circular_buffer< T >::circular_buffer (const circular_buffer< T > & b) [private]
Member Function Documentation
template<typename T> circular_buffer< T > & circular_buffer< T >::operator= (const circular_buffer< T > & b) [inline]
Definition at line 125 of file circular_buffer.h.
References circular_buffer< T >::init(), circular_buffer< T >::peek_data(), circular_buffer< T >::size(), circular_buffer< T >::used(), and circular_buffer< T >::write().
template<typename T> void circular_buffer< T >::resize (int size) [inline]
Definition at line 141 of file circular_buffer.h.
References circular_buffer< T >::m_buf, circular_buffer< T >::m_free, circular_buffer< T >::m_ri, circular_buffer< T >::m_size, circular_buffer< T >::m_used, circular_buffer< T >::m_wi, circular_buffer< T >::peek_data(), and circular_buffer< T >::used().
template<typename T> const T & circular_buffer< T >::read () [inline]
Definition at line 193 of file circular_buffer.h.
References circular_buffer< T >::increment_read_pos(), and circular_buffer< T >::read_data().
template<typename T> void circular_buffer< T >::write (const T & t) [inline]
Definition at line 206 of file circular_buffer.h.
References circular_buffer< T >::increment_write_pos(), and circular_buffer< T >::write_data().
Referenced by circular_buffer< T >::operator=().
template<typename T> bool circular_buffer< T >::is_empty () const [inline]
Definition at line 46 of file circular_buffer.h.
References circular_buffer< T >::used().
Referenced by circular_buffer< T >::debug().
template<typename T> bool circular_buffer< T >::is_full () const [inline]
Definition at line 47 of file circular_buffer.h.
References circular_buffer< T >::free().
Referenced by circular_buffer< T >::debug().
template<typename T> int circular_buffer< T >::size () const [inline]
Definition at line 49 of file circular_buffer.h.
References circular_buffer< T >::m_size.
Referenced by circular_buffer< T >::debug(), circular_buffer< T >::operator=(), circular_buffer< T >::peek_data(), and circular_buffer< T >::poke_data().
template<typename T> int circular_buffer< T >::used () const [inline]
Definition at line 50 of file circular_buffer.h.
References circular_buffer< T >::m_used.
Referenced by circular_buffer< T >::debug(), circular_buffer< T >::is_empty(), circular_buffer< T >::operator=(), and circular_buffer< T >::resize().
template<typename T> int circular_buffer< T >::free () const [inline]
Definition at line 51 of file circular_buffer.h.
References circular_buffer< T >::m_free.
Referenced by circular_buffer< T >::debug(), and circular_buffer< T >::is_full().
template<typename T> T& circular_buffer< T >::write_data () [inline]
Definition at line 53 of file circular_buffer.h.
References circular_buffer< T >::m_buf, and circular_buffer< T >::m_wi.
Referenced by circular_buffer< T >::write().
template<typename T> const T& circular_buffer< T >::read_data () const [inline]
Definition at line 54 of file circular_buffer.h.
References circular_buffer< T >::m_buf, and circular_buffer< T >::m_ri.
Referenced by circular_buffer< T >::read().
template<typename T> const T& circular_buffer< T >::peek_data (int i) const [inline]
Definition at line 56 of file circular_buffer.h.
References circular_buffer< T >::m_buf, circular_buffer< T >::m_ri, and circular_buffer< T >::size().
Referenced by circular_buffer< T >::debug(), circular_buffer< T >::operator=(), and circular_buffer< T >::resize().
template<typename T> T& circular_buffer< T >::poke_data (int i) [inline]
Definition at line 57 of file circular_buffer.h.
References circular_buffer< T >::m_buf, circular_buffer< T >::m_ri, and circular_buffer< T >::size().
template<typename T> void circular_buffer< T >::increment_write_pos (int i = 1) [inline]
Definition at line 217 of file circular_buffer.h.
References circular_buffer< T >::m_free, circular_buffer< T >::m_size, circular_buffer< T >::m_used, and circular_buffer< T >::m_wi.
Referenced by circular_buffer< T >::write().
template<typename T> void circular_buffer< T >::increment_read_pos (int i = 1) [inline]
Definition at line 227 of file circular_buffer.h.
References circular_buffer< T >::m_free, circular_buffer< T >::m_ri, circular_buffer< T >::m_size, and circular_buffer< T >::m_used.
Referenced by circular_buffer< T >::read().
template<typename T> void circular_buffer< T >::init () [inline]
Definition at line 168 of file circular_buffer.h.
References circular_buffer< T >::m_free, circular_buffer< T >::m_ri, circular_buffer< T >::m_size, circular_buffer< T >::m_used, and circular_buffer< T >::m_wi.
Referenced by circular_buffer< T >::circular_buffer(), and circular_buffer< T >::operator=().
template<typename T> void circular_buffer< T >::debug () const [inline]
Definition at line 82 of file circular_buffer.h.
References circular_buffer< T >::free(), circular_buffer< T >::is_empty(), circular_buffer< T >::is_full(), circular_buffer< T >::m_ri, circular_buffer< T >::m_wi, circular_buffer< T >::peek_data(), circular_buffer< T >::size(), and circular_buffer< T >::used().
template<typename T> void circular_buffer< T >::copy (const circular_buffer< T > & b) [inline, private]
Definition at line 179 of file circular_buffer.h.
References circular_buffer< T >::m_buf, circular_buffer< T >::m_free, circular_buffer< T >::m_ri, circular_buffer< T >::m_size, circular_buffer< T >::m_used, and circular_buffer< T >::m_wi.
Member Data Documentation
template<typename T> int circular_buffer< T >::m_size [private]
Definition at line 71 of file circular_buffer.h.
Referenced by circular_buffer< T >::circular_buffer(), circular_buffer< T >::copy(), circular_buffer< T >::increment_read_pos(), circular_buffer< T >::increment_write_pos(), circular_buffer< T >::init(), circular_buffer< T >::resize(), and circular_buffer< T >::size().
template<typename T> T* circular_buffer< T >::m_buf [private]
Definition at line 72 of file circular_buffer.h.
Referenced by circular_buffer< T >::circular_buffer(), circular_buffer< T >::copy(), circular_buffer< T >::peek_data(), circular_buffer< T >::poke_data(), circular_buffer< T >::read_data(), circular_buffer< T >::resize(), circular_buffer< T >::write_data(), and circular_buffer< T >::~circular_buffer().
template<typename T> int circular_buffer< T >::m_free [private]
Definition at line 73 of file circular_buffer.h.
Referenced by circular_buffer< T >::copy(), circular_buffer< T >::free(), circular_buffer< T >::increment_read_pos(), circular_buffer< T >::increment_write_pos(), circular_buffer< T >::init(), and circular_buffer< T >::resize().
template<typename T> int circular_buffer< T >::m_used [private]
Definition at line 74 of file circular_buffer.h.
Referenced by circular_buffer< T >::copy(), circular_buffer< T >::increment_read_pos(), circular_buffer< T >::increment_write_pos(), circular_buffer< T >::init(), circular_buffer< T >::resize(), and circular_buffer< T >::used().
template<typename T> int circular_buffer< T >::m_ri [private]
Definition at line 75 of file circular_buffer.h.
Referenced by circular_buffer< T >::copy(), circular_buffer< T >::debug(), circular_buffer< T >::increment_read_pos(), circular_buffer< T >::init(), circular_buffer< T >::peek_data(), circular_buffer< T >::poke_data(), circular_buffer< T >::read_data(), and circular_buffer< T >::resize().
template<typename T> int circular_buffer< T >::m_wi [private]
Definition at line 76 of file circular_buffer.h.
Referenced by circular_buffer< T >::copy(), circular_buffer< T >::debug(), circular_buffer< T >::increment_write_pos(), circular_buffer< T >::init(), circular_buffer< T >::resize(), and circular_buffer< T >::write_data().
The documentation for this class was generated from the following file:
C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_core/tlm_fifo/circular_buffer.h