TLM 2: tlm Namespace Reference
tlm Namespace Reference
Classes
class tlm_analysis_fifo
class tlm_analysis_if
class tlm_delayed_analysis_if
class tlm_analysis_port
struct tlm_analysis_triple
class tlm_peq
class tlm_write_if
class tlm_delayed_write_if
class tlm_transport_if
class tlm_blocking_get_if
class tlm_blocking_put_if
class tlm_nonblocking_get_if
class tlm_nonblocking_put_if
class tlm_get_if
class tlm_put_if
class tlm_blocking_peek_if
class tlm_nonblocking_peek_if
class tlm_peek_if
class tlm_blocking_get_peek_if
class tlm_nonblocking_get_peek_if
class tlm_get_peek_if
class tlm_fifo_debug_if
class tlm_fifo_put_if
class tlm_fifo_get_if
class tlm_fifo_config_size_if
class tlm_blocking_master_if
class tlm_blocking_slave_if
class tlm_nonblocking_master_if
class tlm_nonblocking_slave_if
class tlm_master_if
class tlm_slave_if
class tlm_tag
class tlm_transport_to_master
class tlm_slave_to_transport
class circular_buffer
class tlm_fifo
class tlm_put_get_imp
class tlm_master_imp
class tlm_slave_imp
class tlm_req_rsp_channel
class tlm_transport_channel
class tlm_event_finder_t
class tlm_nonblocking_get_port
class tlm_nonblocking_peek_port
class tlm_nonblocking_put_port
class tlm_nonblocking_transport_if
class tlm_blocking_transport_if
class tlm_fw_direct_mem_if
class tlm_bw_direct_mem_if
class tlm_transport_dbg_if
struct tlm_generic_payload_types
class tlm_fw_nb_transport_if
class tlm_bw_nb_transport_if
class tlm_fw_transport_if
class tlm_bw_transport_if
class tlm_array
class tlm_debug_payload
class tlm_dmi_mode
class tlm_dmi
class tlm_extension_base
class tlm_extension
class tlm_generic_payload
class tlm_initiator_socket
class tlm_target_socket
Namespaces
namespace tlm_qk_internal
Typedefs
typedef
tlm_qk_internal::tlm_quantumkeeper
< tlm_qk_internal::tlm_dummy > tlm_quantumkeeper
Enumerations
enum tlm_phase { BEGIN_REQ, END_REQ, BEGIN_RESP, END_RESP }
enum tlm_sync_enum { TLM_REJECTED, TLM_SYNC, TLM_SYNC_CONTINUE, TLM_COMPLETED }
enum tlm_command { TLM_READ_COMMAND, TLM_WRITE_COMMAND, TLM_IGNORE_COMMAND }
enum tlm_response_status {
TLM_OK_RESPONSE = 1, TLM_INCOMPLETE_RESPONSE = 0, TLM_GENERIC_ERROR_RESPONSE = -1, TLM_ADDRESS_ERROR_RESPONSE = -2,
TLM_COMMAND_ERROR_RESPONSE = -3, TLM_BURST_ERROR_RESPONSE = -4, TLM_BYTE_ENABLE_ERROR_RESPONSE = -5
}
enum tlm_endianness { TLM_UNKNOWN_ENDIAN, TLM_LITTLE_ENDIAN, TLM_BIG_ENDIAN }
Functions
unsigned int get_subword_offset (sc_dt::int64 address, unsigned int bus_width, unsigned int subword_size, tlm_endianness endianness)
template<class T>
void copy_word_from_array (T &data_word, unsigned int offset, unsigned int nr_bytes, unsigned char *m_data, bool *m_be, unsigned int m_be_length)
template<class T>
void copy_word_to_array (T &data_word, unsigned int offset, unsigned int nr_bytes, unsigned char *m_data, bool *m_be, unsigned int m_be_length)
void copy_word_from_array (unsigned char *data_word, unsigned int offset, unsigned int nr_bytes, unsigned char *m_data, bool *m_be, unsigned int m_be_length)
void copy_word_to_array (unsigned char *data_word, unsigned int offset, unsigned int nr_bytes, unsigned char *m_data, bool *m_be, unsigned int m_be_length)
unsigned int max_num_extensions (bool increment=false)
bool hostHasLittleEndianness ()
bool hasHostEndianness (tlm_endianness endianness)
unsigned char swap_bytes (unsigned char rhs)
char swap_bytes (char rhs)
signed char swap_bytes (signed char rhs)
unsigned short swap_bytes (unsigned short rhs)
signed short swap_bytes (signed short rhs)
unsigned int swap_bytes (unsigned int rhs)
signed int swap_bytes (signed int rhs)
unsigned long swap_bytes (unsigned long rhs)
signed long swap_bytes (signed long rhs)
unsigned long long swap_bytes (unsigned long long rhs)
signed long long swap_bytes (signed long long rhs)
void copy_data (const unsigned char *src, unsigned char *dest, unsigned int nrOfBytes, tlm_endianness endianness)
template<typename DT>
DT swapIfNeeded (DT word, tlm_endianness endianness)
Typedef Documentation
typedef tlm_qk_internal::tlm_quantumkeeper< tlm_qk_internal::tlm_dummy > tlm::tlm_quantumkeeper
Definition at line 185 of file tlm_quantumkeeper.h.
Enumeration Type Documentation
enum tlm::tlm_command
Enumerator:
TLM_READ_COMMAND
TLM_WRITE_COMMAND
TLM_IGNORE_COMMAND
Definition at line 74 of file tlm_gp.h.
enum tlm::tlm_endianness
Enumerator:
TLM_UNKNOWN_ENDIAN
TLM_LITTLE_ENDIAN
TLM_BIG_ENDIAN
Definition at line 26 of file tlm_helpers.h.
enum tlm::tlm_phase
Enumerator:
BEGIN_REQ
END_REQ
BEGIN_RESP
END_RESP
Definition at line 26 of file tlm_fw_bw_ifs.h.
enum tlm::tlm_response_status
Enumerator:
TLM_OK_RESPONSE
TLM_INCOMPLETE_RESPONSE
TLM_GENERIC_ERROR_RESPONSE
TLM_ADDRESS_ERROR_RESPONSE
TLM_COMMAND_ERROR_RESPONSE
TLM_BURST_ERROR_RESPONSE
TLM_BYTE_ENABLE_ERROR_RESPONSE
Definition at line 80 of file tlm_gp.h.
enum tlm::tlm_sync_enum
Enumerator:
TLM_REJECTED
TLM_SYNC
TLM_SYNC_CONTINUE
TLM_COMPLETED
Definition at line 27 of file tlm_fw_bw_ifs.h.
Function Documentation
void tlm::copy_data (const unsigned char * src, unsigned char * dest, unsigned int nrOfBytes, tlm_endianness endianness) [inline]
Definition at line 77 of file tlm_helpers.h.
References hasHostEndianness().
void tlm::copy_word_from_array (unsigned char * data_word, unsigned int offset, unsigned int nr_bytes, unsigned char * m_data, bool * m_be, unsigned int m_be_length) [inline]
Definition at line 212 of file tlm_data_serializers.h.
template<class T> void tlm::copy_word_from_array (T & data_word, unsigned int offset, unsigned int nr_bytes, unsigned char * m_data, bool * m_be, unsigned int m_be_length) [inline]
Definition at line 99 of file tlm_data_serializers.h.
void tlm::copy_word_to_array (unsigned char * data_word, unsigned int offset, unsigned int nr_bytes, unsigned char * m_data, bool * m_be, unsigned int m_be_length) [inline]
Definition at line 228 of file tlm_data_serializers.h.
template<class T> void tlm::copy_word_to_array (T & data_word, unsigned int offset, unsigned int nr_bytes, unsigned char * m_data, bool * m_be, unsigned int m_be_length) [inline]
Definition at line 118 of file tlm_data_serializers.h.
unsigned int tlm::get_subword_offset (sc_dt::int64 address, unsigned int bus_width, unsigned int subword_size, tlm_endianness endianness) [inline]
Definition at line 39 of file tlm_data_serializers.h.
References hasHostEndianness().
bool tlm::hasHostEndianness (tlm_endianness endianness) [inline]
Definition at line 45 of file tlm_helpers.h.
References hostHasLittleEndianness(), TLM_BIG_ENDIAN, and TLM_LITTLE_ENDIAN.
Referenced by copy_data(), get_subword_offset(), and swapIfNeeded().
bool tlm::hostHasLittleEndianness () [inline]
Definition at line 28 of file tlm_helpers.h.
References TLM_UNKNOWN_ENDIAN.
Referenced by hasHostEndianness().
unsigned int tlm::max_num_extensions (bool increment = false) [inline]
Definition at line 31 of file tlm_gp.h.
Referenced by tlm::tlm_extension_base::register_extension(), and tlm::tlm_generic_payload::resize_extensions().
signed long long tlm::swap_bytes (signed long long rhs) [inline]
Definition at line 69 of file tlm_helpers.h.
References swap_bytes().
unsigned long long tlm::swap_bytes (unsigned long long rhs) [inline]
Definition at line 68 of file tlm_helpers.h.
References swap_bytes().
signed long tlm::swap_bytes (signed long rhs) [inline]
Definition at line 66 of file tlm_helpers.h.
References swap_bytes().
unsigned long tlm::swap_bytes (unsigned long rhs) [inline]
Definition at line 65 of file tlm_helpers.h.
signed int tlm::swap_bytes (signed int rhs) [inline]
Definition at line 63 of file tlm_helpers.h.
References swap_bytes().
unsigned int tlm::swap_bytes (unsigned int rhs) [inline]
Definition at line 62 of file tlm_helpers.h.
signed short tlm::swap_bytes (signed short rhs) [inline]
Definition at line 60 of file tlm_helpers.h.
References swap_bytes().
unsigned short tlm::swap_bytes (unsigned short rhs) [inline]
Definition at line 59 of file tlm_helpers.h.
signed char tlm::swap_bytes (signed char rhs) [inline]
Definition at line 57 of file tlm_helpers.h.
char tlm::swap_bytes (char rhs) [inline]
Definition at line 56 of file tlm_helpers.h.
unsigned char tlm::swap_bytes (unsigned char rhs) [inline]
Definition at line 55 of file tlm_helpers.h.
Referenced by swap_bytes(), and swapIfNeeded().
template<typename DT> DT tlm::swapIfNeeded (DT word, tlm_endianness endianness) [inline]
Definition at line 94 of file tlm_helpers.h.
References hasHostEndianness(), and swap_bytes().