TLM 2: tlm_utils Namespace Reference
tlm_utils Namespace Reference
Classes
class ispex_base
class instance_specific_extension
class instance_specific_extensions_per_accessor
class instance_specific_extension_container_pool
class instance_specific_extension_container
class instance_specific_extension_carrier
class instance_specific_extension_accessor
class multi_passthrough_initiator_socket
class multi_passthrough_target_socket
class callback_binder_fw
class callback_binder_bw
class multi_init_base
class multi_target_base
class multi_to_multi_bind_base
class passthrough_target_socket
class passthrough_target_socket_tagged
class time_ordered_list
class peq_with_cb_and_phase
class peq_with_get
class simple_initiator_socket
class simple_initiator_socket_tagged
class simple_target_socket
class simple_target_socket_tagged
class tlm_quantumkeeper
Functions
unsigned int max_num_ispex_accessors (bool increment=false)
unsigned int max_num_ispex (bool increment=false)
Function Documentation
unsigned int tlm_utils::max_num_ispex (bool increment = false) [inline]
Definition at line 62 of file instance_specific_extensions.h.
Referenced by tlm_utils::ispex_base::register_private_extension(), and tlm_utils::instance_specific_extensions_per_accessor< U >::resize_extensions().
unsigned int tlm_utils::max_num_ispex_accessors (bool increment = false) [inline]
Definition at line 54 of file instance_specific_extensions.h.
Referenced by tlm_utils::instance_specific_extension_container::resize().