TLM 2: C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_generic_payload/tlm_helpers.h File Reference
C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_generic_payload/tlm_helpers.h File Reference
Enumerations
enum tlm_endianness { TLM_LITTLE_ENDIAN, TLM_BIG_ENDIAN }
Functions
bool hostHasLittleEndianness ()
bool hasHostEndianness (tlm_endianness endianness)
unsigned char swap_bytes (unsigned char rhs)
char swap_bytes (char rhs)
signed char swap_bytes (signed char rhs)
unsigned short swap_bytes (unsigned short rhs)
signed short swap_bytes (signed short rhs)
unsigned int swap_bytes (unsigned int rhs)
signed int swap_bytes (signed int rhs)
unsigned long swap_bytes (unsigned long rhs)
signed long swap_bytes (signed long rhs)
unsigned long long swap_bytes (unsigned long long rhs)
signed long long swap_bytes (signed long long rhs)
void copy_data (const unsigned char *src, unsigned char *dest, unsigned int nrOfBytes, tlm_endianness endianness)
template<typename DT>
DT swapIfNeeded (DT word, tlm_endianness endianness)
Enumeration Type Documentation
enum tlm_endianness
Enumerator:
TLM_LITTLE_ENDIAN
TLM_BIG_ENDIAN
Definition at line 7 of file tlm_helpers.h.
Function Documentation
void copy_data (const unsigned char * src, unsigned char * dest, unsigned int nrOfBytes, tlm_endianness endianness) [inline]
Definition at line 59 of file tlm_helpers.h.
References hasHostEndianness().
bool hasHostEndianness (tlm_endianness endianness) [inline]
Definition at line 27 of file tlm_helpers.h.
References hostHasLittleEndianness(), TLM_BIG_ENDIAN, and TLM_LITTLE_ENDIAN.
Referenced by copy_data(), and swapIfNeeded().
bool hostHasLittleEndianness () [inline]
Definition at line 9 of file tlm_helpers.h.
Referenced by copy_from_array(), copy_to_array(), and hasHostEndianness().
signed long long swap_bytes (signed long long rhs) [inline]
Definition at line 51 of file tlm_helpers.h.
References swap_bytes().
unsigned long long swap_bytes (unsigned long long rhs) [inline]
Definition at line 50 of file tlm_helpers.h.
References swap_bytes().
signed long swap_bytes (signed long rhs) [inline]
Definition at line 48 of file tlm_helpers.h.
References swap_bytes().
unsigned long swap_bytes (unsigned long rhs) [inline]
Definition at line 47 of file tlm_helpers.h.
signed int swap_bytes (signed int rhs) [inline]
Definition at line 45 of file tlm_helpers.h.
References swap_bytes().
unsigned int swap_bytes (unsigned int rhs) [inline]
Definition at line 44 of file tlm_helpers.h.
signed short swap_bytes (signed short rhs) [inline]
Definition at line 42 of file tlm_helpers.h.
References swap_bytes().
unsigned short swap_bytes (unsigned short rhs) [inline]
Definition at line 41 of file tlm_helpers.h.
signed char swap_bytes (signed char rhs) [inline]
Definition at line 39 of file tlm_helpers.h.
char swap_bytes (char rhs) [inline]
Definition at line 38 of file tlm_helpers.h.
unsigned char swap_bytes (unsigned char rhs) [inline]
Definition at line 37 of file tlm_helpers.h.
Referenced by swap_bytes(), and swapIfNeeded().
template<typename DT> DT swapIfNeeded (DT word, tlm_endianness endianness) [inline]
Definition at line 76 of file tlm_helpers.h.
References hasHostEndianness(), and swap_bytes().