.TH "analysis_if" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
analysis_if \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_analysis_if.h>\fP
.PP
Inherits \fBsc_interface\fP.
.PP
Inherited by \fBanalysis_fifo< T >\fP\fC [virtual]\fP, and \fBanalysis_port< T >\fP\fC [virtual]\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBwrite\fP (const T &t)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T> class analysis_if< T >"

.PP
Definition at line 8 of file tlm_analysis_if.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T> virtual void \fBanalysis_if\fP< T >::write (const T & t)\fC [pure virtual]\fP"
.PP
Implemented in \fBanalysis_fifo< T >\fP, \fBanalysis_fifo< T >\fP, and \fBanalysis_port< T >\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
