.TH "analysis::analysis_triple" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
analysis::analysis_triple \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_analysis.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBanalysis_triple\fP ()"
.br
.ti -1c
.RI "\fBanalysis_triple\fP (const \fBanalysis_triple\fP &triple)"
.br
.ti -1c
.RI "\fBanalysis_triple\fP (const T &t)"
.br
.ti -1c
.RI "\fBoperator T\fP ()"
.br
.ti -1c
.RI "\fBoperator const T &\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "sc_time \fBstart_time\fP"
.br
.ti -1c
.RI "T \fBtransaction\fP"
.br
.ti -1c
.RI "sc_time \fBend_time\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T> struct analysis::analysis_triple< T >"

.PP
Definition at line 41 of file tlm_analysis.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> \fBanalysis::analysis_triple\fP< T >::\fBanalysis_triple\fP ()\fC [inline]\fP"
.PP
Definition at line 47 of file tlm_analysis.h.
.SS "template<typename T> \fBanalysis::analysis_triple\fP< T >::\fBanalysis_triple\fP (const \fBanalysis_triple\fP< T > & triple)\fC [inline]\fP"
.PP
Definition at line 49 of file tlm_analysis.h.
.SS "template<typename T> \fBanalysis::analysis_triple\fP< T >::\fBanalysis_triple\fP (const T & t)\fC [inline]\fP"
.PP
Definition at line 55 of file tlm_analysis.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T> \fBanalysis::analysis_triple\fP< T >::operator T ()\fC [inline]\fP"
.PP
Definition at line 59 of file tlm_analysis.h.
.SS "template<typename T> \fBanalysis::analysis_triple\fP< T >::operator const T & () const\fC [inline]\fP"
.PP
Definition at line 60 of file tlm_analysis.h.
.SH "Member Data Documentation"
.PP 
.SS "template<typename T> sc_time \fBanalysis::analysis_triple\fP< T >::\fBstart_time\fP"
.PP
Definition at line 43 of file tlm_analysis.h.
.SS "template<typename T> T \fBanalysis::analysis_triple\fP< T >::\fBtransaction\fP"
.PP
Definition at line 44 of file tlm_analysis.h.
.SS "template<typename T> sc_time \fBanalysis::analysis_triple\fP< T >::\fBend_time\fP"
.PP
Definition at line 45 of file tlm_analysis.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
