.TH "analysis_fifo" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
analysis_fifo \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_analysis_fifo.h>\fP
.PP
Inherits \fBtlm_fifo< T >< T >\fP, \fBanalysis_if< T >< T >\fP, and \fBanalysis_if< analysis_triple< T > >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBanalysis_fifo\fP (const char *nm)"
.br
.ti -1c
.RI "\fBanalysis_fifo\fP ()"
.br
.ti -1c
.RI "void \fBwrite\fP (const \fBanalysis_triple\fP< T > &t)"
.br
.ti -1c
.RI "void \fBwrite\fP (const T &t)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T> class analysis_fifo< T >"

.PP
Definition at line 13 of file tlm_analysis_fifo.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> \fBanalysis_fifo\fP< T >::\fBanalysis_fifo\fP (const char * nm)\fC [inline]\fP"
.PP
Definition at line 22 of file tlm_analysis_fifo.h.
.SS "template<typename T> \fBanalysis_fifo\fP< T >::\fBanalysis_fifo\fP ()\fC [inline]\fP"
.PP
Definition at line 23 of file tlm_analysis_fifo.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T> void \fBanalysis_fifo\fP< T >::write (const \fBanalysis_triple\fP< T > & t)\fC [inline, virtual]\fP"
.PP
Implements \fBanalysis_if< analysis_triple< T > >\fP.
.PP
Definition at line 25 of file tlm_analysis_fifo.h.
.PP
References tlm_fifo< T >::nb_put().
.SS "template<typename T> void \fBanalysis_fifo\fP< T >::write (const T & t)\fC [inline, virtual]\fP"
.PP
Implements \fBanalysis_if< T >\fP.
.PP
Definition at line 29 of file tlm_analysis_fifo.h.
.PP
References tlm_fifo< T >::nb_put().

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
