.TH "analysis_port" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
analysis_port \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_analysis_port.h>\fP
.PP
Inherits \fBsc_object\fP, and \fBanalysis_if< T >< T >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBanalysis_port\fP ()"
.br
.ti -1c
.RI "\fBanalysis_port\fP (const char *nm)"
.br
.ti -1c
.RI "void \fBbind\fP (\fBanalysis_if\fP< T > &_if)"
.br
.ti -1c
.RI "void \fBoperator()\fP (\fBanalysis_if\fP< T > &_if)"
.br
.ti -1c
.RI "bool \fBunbind\fP (\fBanalysis_if\fP< T > &_if)"
.br
.ti -1c
.RI "void \fBwrite\fP (const T &t)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::deque< \fBanalysis_if\fP< T > * > \fBm_interfaces\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T> class analysis_port< T >"

.PP
Definition at line 10 of file tlm_analysis_port.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> \fBanalysis_port\fP< T >::\fBanalysis_port\fP ()\fC [inline]\fP"
.PP
Definition at line 15 of file tlm_analysis_port.h.
.SS "template<typename T> \fBanalysis_port\fP< T >::\fBanalysis_port\fP (const char * nm)\fC [inline]\fP"
.PP
Definition at line 16 of file tlm_analysis_port.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T> void \fBanalysis_port\fP< T >::bind (\fBanalysis_if\fP< T > & _if)\fC [inline]\fP"
.PP
Definition at line 21 of file tlm_analysis_port.h.
.PP
References analysis_port< T >::m_interfaces.
.PP
Referenced by analysis_port< T >::operator()().
.SS "template<typename T> void \fBanalysis_port\fP< T >::operator() (\fBanalysis_if\fP< T > & _if)\fC [inline]\fP"
.PP
Definition at line 25 of file tlm_analysis_port.h.
.PP
References analysis_port< T >::bind().
.SS "template<typename T> bool \fBanalysis_port\fP< T >::unbind (\fBanalysis_if\fP< T > & _if)\fC [inline]\fP"
.PP
Definition at line 27 of file tlm_analysis_port.h.
.PP
References analysis_port< T >::m_interfaces.
.SS "template<typename T> void \fBanalysis_port\fP< T >::write (const T & t)\fC [inline, virtual]\fP"
.PP
Implements \fBanalysis_if< T >\fP.
.PP
Definition at line 48 of file tlm_analysis_port.h.
.PP
References analysis_port< T >::m_interfaces.
.SH "Member Data Documentation"
.PP 
.SS "template<typename T> std::deque< \fBanalysis_if\fP<T> * > \fBanalysis_port\fP< T >::\fBm_interfaces\fP\fC [private]\fP"
.PP
Definition at line 62 of file tlm_analysis_port.h.
.PP
Referenced by analysis_port< T >::bind(), analysis_port< T >::unbind(), and analysis_port< T >::write().

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
