.TH "circular_buffer" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
circular_buffer \- 
.SH SYNOPSIS
.br
.PP
\fC#include <circular_buffer.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcircular_buffer\fP (int size)"
.br
.ti -1c
.RI "\fBcircular_buffer\fP< T > & \fBoperator=\fP (const \fBcircular_buffer\fP< T > &)"
.br
.ti -1c
.RI "\fB~circular_buffer\fP ()"
.br
.ti -1c
.RI "void \fBresize\fP (int size)"
.br
.ti -1c
.RI "const T & \fBread\fP ()"
.br
.ti -1c
.RI "void \fBwrite\fP (const T &)"
.br
.ti -1c
.RI "bool \fBis_empty\fP () const "
.br
.ti -1c
.RI "bool \fBis_full\fP () const "
.br
.ti -1c
.RI "int \fBsize\fP () const "
.br
.ti -1c
.RI "int \fBused\fP () const "
.br
.ti -1c
.RI "int \fBfree\fP () const "
.br
.ti -1c
.RI "T & \fBwrite_data\fP ()"
.br
.ti -1c
.RI "const T & \fBread_data\fP () const "
.br
.ti -1c
.RI "const T & \fBpeek_data\fP (int i) const "
.br
.ti -1c
.RI "T & \fBpoke_data\fP (int i)"
.br
.ti -1c
.RI "void \fBincrement_write_pos\fP (int i=1)"
.br
.ti -1c
.RI "void \fBincrement_read_pos\fP (int i=1)"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBdebug\fP () const "
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBcircular_buffer\fP (const \fBcircular_buffer\fP< T > &b)"
.br
.ti -1c
.RI "void \fBcopy\fP (const \fBcircular_buffer\fP< T > &b)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBm_size\fP"
.br
.ti -1c
.RI "T * \fBm_buf\fP"
.br
.ti -1c
.RI "int \fBm_free\fP"
.br
.ti -1c
.RI "int \fBm_used\fP"
.br
.ti -1c
.RI "int \fBm_ri\fP"
.br
.ti -1c
.RI "int \fBm_wi\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T> class circular_buffer< T >"

.PP
Definition at line 32 of file circular_buffer.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> \fBcircular_buffer\fP< T >::\fBcircular_buffer\fP (int size)\fC [inline]\fP"
.PP
Definition at line 114 of file circular_buffer.h.
.PP
References circular_buffer< T >::init(), circular_buffer< T >::m_buf, and circular_buffer< T >::m_size.
.SS "template<typename T> \fBcircular_buffer\fP< T >::~\fBcircular_buffer\fP ()\fC [inline]\fP"
.PP
Definition at line 39 of file circular_buffer.h.
.PP
References circular_buffer< T >::m_buf.
.SS "template<typename T> \fBcircular_buffer\fP< T >::\fBcircular_buffer\fP (const \fBcircular_buffer\fP< T > & b)\fC [private]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "template<typename T> \fBcircular_buffer\fP< T > & \fBcircular_buffer\fP< T >::operator= (const \fBcircular_buffer\fP< T > & b)\fC [inline]\fP"
.PP
Definition at line 125 of file circular_buffer.h.
.PP
References circular_buffer< T >::init(), circular_buffer< T >::peek_data(), circular_buffer< T >::size(), circular_buffer< T >::used(), and circular_buffer< T >::write().
.SS "template<typename T> void \fBcircular_buffer\fP< T >::resize (int size)\fC [inline]\fP"
.PP
Definition at line 141 of file circular_buffer.h.
.PP
References circular_buffer< T >::m_buf, circular_buffer< T >::m_free, circular_buffer< T >::m_ri, circular_buffer< T >::m_size, circular_buffer< T >::m_used, circular_buffer< T >::m_wi, circular_buffer< T >::peek_data(), and circular_buffer< T >::used().
.SS "template<typename T> const T & \fBcircular_buffer\fP< T >::read ()\fC [inline]\fP"
.PP
Definition at line 193 of file circular_buffer.h.
.PP
References circular_buffer< T >::increment_read_pos(), and circular_buffer< T >::read_data().
.SS "template<typename T> void \fBcircular_buffer\fP< T >::write (const T & t)\fC [inline]\fP"
.PP
Definition at line 206 of file circular_buffer.h.
.PP
References circular_buffer< T >::increment_write_pos(), and circular_buffer< T >::write_data().
.PP
Referenced by circular_buffer< T >::operator=().
.SS "template<typename T> bool \fBcircular_buffer\fP< T >::is_empty () const\fC [inline]\fP"
.PP
Definition at line 46 of file circular_buffer.h.
.PP
References circular_buffer< T >::used().
.PP
Referenced by circular_buffer< T >::debug().
.SS "template<typename T> bool \fBcircular_buffer\fP< T >::is_full () const\fC [inline]\fP"
.PP
Definition at line 47 of file circular_buffer.h.
.PP
References circular_buffer< T >::free().
.PP
Referenced by circular_buffer< T >::debug().
.SS "template<typename T> int \fBcircular_buffer\fP< T >::size () const\fC [inline]\fP"
.PP
Definition at line 49 of file circular_buffer.h.
.PP
References circular_buffer< T >::m_size.
.PP
Referenced by circular_buffer< T >::debug(), circular_buffer< T >::operator=(), circular_buffer< T >::peek_data(), and circular_buffer< T >::poke_data().
.SS "template<typename T> int \fBcircular_buffer\fP< T >::used () const\fC [inline]\fP"
.PP
Definition at line 50 of file circular_buffer.h.
.PP
References circular_buffer< T >::m_used.
.PP
Referenced by circular_buffer< T >::debug(), circular_buffer< T >::is_empty(), circular_buffer< T >::operator=(), and circular_buffer< T >::resize().
.SS "template<typename T> int \fBcircular_buffer\fP< T >::free () const\fC [inline]\fP"
.PP
Definition at line 51 of file circular_buffer.h.
.PP
References circular_buffer< T >::m_free.
.PP
Referenced by circular_buffer< T >::debug(), and circular_buffer< T >::is_full().
.SS "template<typename T> T& \fBcircular_buffer\fP< T >::write_data ()\fC [inline]\fP"
.PP
Definition at line 53 of file circular_buffer.h.
.PP
References circular_buffer< T >::m_buf, and circular_buffer< T >::m_wi.
.PP
Referenced by circular_buffer< T >::write().
.SS "template<typename T> const T& \fBcircular_buffer\fP< T >::read_data () const\fC [inline]\fP"
.PP
Definition at line 54 of file circular_buffer.h.
.PP
References circular_buffer< T >::m_buf, and circular_buffer< T >::m_ri.
.PP
Referenced by circular_buffer< T >::read().
.SS "template<typename T> const T& \fBcircular_buffer\fP< T >::peek_data (int i) const\fC [inline]\fP"
.PP
Definition at line 56 of file circular_buffer.h.
.PP
References circular_buffer< T >::m_buf, circular_buffer< T >::m_ri, and circular_buffer< T >::size().
.PP
Referenced by circular_buffer< T >::debug(), circular_buffer< T >::operator=(), and circular_buffer< T >::resize().
.SS "template<typename T> T& \fBcircular_buffer\fP< T >::poke_data (int i)\fC [inline]\fP"
.PP
Definition at line 57 of file circular_buffer.h.
.PP
References circular_buffer< T >::m_buf, circular_buffer< T >::m_ri, and circular_buffer< T >::size().
.SS "template<typename T> void \fBcircular_buffer\fP< T >::increment_write_pos (int i = \fC1\fP)\fC [inline]\fP"
.PP
Definition at line 217 of file circular_buffer.h.
.PP
References circular_buffer< T >::m_free, circular_buffer< T >::m_size, circular_buffer< T >::m_used, and circular_buffer< T >::m_wi.
.PP
Referenced by circular_buffer< T >::write().
.SS "template<typename T> void \fBcircular_buffer\fP< T >::increment_read_pos (int i = \fC1\fP)\fC [inline]\fP"
.PP
Definition at line 227 of file circular_buffer.h.
.PP
References circular_buffer< T >::m_free, circular_buffer< T >::m_ri, circular_buffer< T >::m_size, and circular_buffer< T >::m_used.
.PP
Referenced by circular_buffer< T >::read().
.SS "template<typename T> void \fBcircular_buffer\fP< T >::init ()\fC [inline]\fP"
.PP
Definition at line 168 of file circular_buffer.h.
.PP
References circular_buffer< T >::m_free, circular_buffer< T >::m_ri, circular_buffer< T >::m_size, circular_buffer< T >::m_used, and circular_buffer< T >::m_wi.
.PP
Referenced by circular_buffer< T >::circular_buffer(), and circular_buffer< T >::operator=().
.SS "template<typename T> void \fBcircular_buffer\fP< T >::debug () const\fC [inline]\fP"
.PP
Definition at line 82 of file circular_buffer.h.
.PP
References circular_buffer< T >::free(), circular_buffer< T >::is_empty(), circular_buffer< T >::is_full(), circular_buffer< T >::m_ri, circular_buffer< T >::m_wi, circular_buffer< T >::peek_data(), circular_buffer< T >::size(), and circular_buffer< T >::used().
.SS "template<typename T> void \fBcircular_buffer\fP< T >::copy (const \fBcircular_buffer\fP< T > & b)\fC [inline, private]\fP"
.PP
Definition at line 179 of file circular_buffer.h.
.PP
References circular_buffer< T >::m_buf, circular_buffer< T >::m_free, circular_buffer< T >::m_ri, circular_buffer< T >::m_size, circular_buffer< T >::m_used, and circular_buffer< T >::m_wi.
.SH "Member Data Documentation"
.PP 
.SS "template<typename T> int \fBcircular_buffer\fP< T >::\fBm_size\fP\fC [private]\fP"
.PP
Definition at line 71 of file circular_buffer.h.
.PP
Referenced by circular_buffer< T >::circular_buffer(), circular_buffer< T >::copy(), circular_buffer< T >::increment_read_pos(), circular_buffer< T >::increment_write_pos(), circular_buffer< T >::init(), circular_buffer< T >::resize(), and circular_buffer< T >::size().
.SS "template<typename T> T* \fBcircular_buffer\fP< T >::\fBm_buf\fP\fC [private]\fP"
.PP
Definition at line 72 of file circular_buffer.h.
.PP
Referenced by circular_buffer< T >::circular_buffer(), circular_buffer< T >::copy(), circular_buffer< T >::peek_data(), circular_buffer< T >::poke_data(), circular_buffer< T >::read_data(), circular_buffer< T >::resize(), circular_buffer< T >::write_data(), and circular_buffer< T >::~circular_buffer().
.SS "template<typename T> int \fBcircular_buffer\fP< T >::\fBm_free\fP\fC [private]\fP"
.PP
Definition at line 73 of file circular_buffer.h.
.PP
Referenced by circular_buffer< T >::copy(), circular_buffer< T >::free(), circular_buffer< T >::increment_read_pos(), circular_buffer< T >::increment_write_pos(), circular_buffer< T >::init(), and circular_buffer< T >::resize().
.SS "template<typename T> int \fBcircular_buffer\fP< T >::\fBm_used\fP\fC [private]\fP"
.PP
Definition at line 74 of file circular_buffer.h.
.PP
Referenced by circular_buffer< T >::copy(), circular_buffer< T >::increment_read_pos(), circular_buffer< T >::increment_write_pos(), circular_buffer< T >::init(), circular_buffer< T >::resize(), and circular_buffer< T >::used().
.SS "template<typename T> int \fBcircular_buffer\fP< T >::\fBm_ri\fP\fC [private]\fP"
.PP
Definition at line 75 of file circular_buffer.h.
.PP
Referenced by circular_buffer< T >::copy(), circular_buffer< T >::debug(), circular_buffer< T >::increment_read_pos(), circular_buffer< T >::init(), circular_buffer< T >::peek_data(), circular_buffer< T >::poke_data(), circular_buffer< T >::read_data(), and circular_buffer< T >::resize().
.SS "template<typename T> int \fBcircular_buffer\fP< T >::\fBm_wi\fP\fC [private]\fP"
.PP
Definition at line 76 of file circular_buffer.h.
.PP
Referenced by circular_buffer< T >::copy(), circular_buffer< T >::debug(), circular_buffer< T >::increment_write_pos(), circular_buffer< T >::init(), circular_buffer< T >::resize(), and circular_buffer< T >::write_data().

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
