.TH "sc_module" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_module \- 
.SH SYNOPSIS
.br
.PP
Inherited by \fBtlm_annotated::tlm_annotated_fifo< T >\fP, \fBtlm_annotated::tlm_annotated_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >\fP, \fBtlm_annotated::tlm_peq< T >\fP, \fBtlm_annotated::tlm_peq< tlm_tag< T > * >\fP, \fBtlm_annotated_fifo< T >\fP, \fBtlm_annotated_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >\fP, \fBtlm_core::tlm_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >\fP, \fBtlm_core::tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >\fP, \fBtlm_peq< T >\fP, \fBtlm_peq< tlm_tag< T > * >\fP, \fBtlm_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >\fP, \fBtlm_slave_to_transport< REQ, RSP >\fP, \fBtlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >\fP, and \fBtlm_transport_to_master< REQ, RSP >\fP.
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
