.TH "sc_object" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_object \- 
.SH SYNOPSIS
.br
.PP
Inherited by \fBanalysis::analysis_port< T >\fP, \fBanalysis::analysis_port< tlm_tag< T > * >\fP, and \fBanalysis_port< T >\fP.
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
