.TH "tlm_core::tlm_blocking_master_if" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_core::tlm_blocking_master_if \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_core.h>\fP
.PP
Inherits \fBtlm_core::tlm_blocking_put_if< T >< REQ >\fP, and \fBtlm_core::tlm_blocking_get_peek_if< RSP >\fP.
.PP
Inherited by \fBtlm_core::tlm_master_if< REQ, RSP >\fP\fC [virtual]\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename REQ, typename RSP> class tlm_core::tlm_blocking_master_if< REQ, RSP >"

.PP
Definition at line 213 of file tlm_core.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
