.TH "tlm_annotated_slave_if" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_annotated_slave_if \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_annotated_master_slave_ifs.h>\fP
.PP
Inherits \fBtlm_annotated_put_if< RSP >\fP, \fBtlm_annotated_get_peek_if< REQ >\fP, \fBtlm_annotated_nonblocking_slave_if< REQ, RSP >< REQ, RSP >\fP, and \fBtlm_core::tlm_slave_if< REQ, RSP >< REQ, RSP >\fP.
.PP
Inherited by \fBtlm_annotated_slave_imp< REQ, RSP >\fP\fC [virtual]\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename REQ, typename RSP> class tlm_annotated_slave_if< REQ, RSP >"

.PP
Definition at line 59 of file tlm_annotated_master_slave_ifs.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
