.TH "C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_generic_payload/tlm_data_serializers.h" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_generic_payload/tlm_data_serializers.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'tlm_helpers.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBTLM_COPY_FROM_ARRAY\fP(otype)"
.br
.ti -1c
.RI "#define \fBTLM_COPY_TO_ARRAY\fP(otype)"
.br
.ti -1c
.RI "#define \fBTLM_COPY_FROM_ARRAY\fP(otype)"
.br
.ti -1c
.RI "#define \fBTLM_COPY_TO_ARRAY\fP(otype)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class T> void \fBcopy_from_array\fP (T &data, unsigned int index, unsigned char *m_data)"
.br
.ti -1c
.RI "template<class T> void \fBcopy_to_array\fP (const T &data, unsigned int index, unsigned char *m_data)"
.br
.ti -1c
.RI "\fBTLM_COPY_FROM_ARRAY\fP (signed char)"
.br
.ti -1c
.RI "\fBTLM_COPY_FROM_ARRAY\fP (signed long long)"
.br
.ti -1c
.RI "\fBTLM_COPY_FROM_ARRAY\fP (unsigned char)"
.br
.ti -1c
.RI "\fBTLM_COPY_FROM_ARRAY\fP (unsigned long)"
.br
.ti -1c
.RI "\fBTLM_COPY_FROM_ARRAY\fP (unsigned long long)"
.br
.ti -1c
.RI "\fBTLM_COPY_TO_ARRAY\fP (signed char)"
.br
.ti -1c
.RI "\fBTLM_COPY_TO_ARRAY\fP (signed long long)"
.br
.ti -1c
.RI "\fBTLM_COPY_TO_ARRAY\fP (unsigned char)"
.br
.ti -1c
.RI "\fBTLM_COPY_TO_ARRAY\fP (unsigned long)"
.br
.ti -1c
.RI "\fBTLM_COPY_TO_ARRAY\fP (unsigned long long)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define TLM_COPY_FROM_ARRAY(otype)"
.PP
\fBValue:\fP
.PP
.nf
template<> inline \
  void copy_from_array( otype& data, unsigned int index, unsigned char* m_data) \
  { \
    data = reinterpret_cast<otype*>(m_data)[index]; \
  }
.fi
.PP
Definition at line 720 of file tlm_generic_payload.h.
.SS "#define TLM_COPY_FROM_ARRAY(otype)"
.PP
\fBValue:\fP
.PP
.nf
template<> inline \
  void copy_from_array( otype& data, unsigned int index, unsigned char* m_data) \
  { \
    data = reinterpret_cast<otype*>(m_data)[index]; \
  }
.fi
.PP
Definition at line 73 of file tlm_data_serializers.h.
.SS "#define TLM_COPY_TO_ARRAY(otype)"
.PP
\fBValue:\fP
.PP
.nf
template<> inline \
  void copy_to_array( const otype& data, unsigned int index, unsigned char* m_data) \
  { \
    reinterpret_cast<otype*>(m_data)[index] = data; \
  }
.fi
.PP
Definition at line 727 of file tlm_generic_payload.h.
.SS "#define TLM_COPY_TO_ARRAY(otype)"
.PP
\fBValue:\fP
.PP
.nf
template<> inline \
  void copy_to_array( const otype& data, unsigned int index, unsigned char* m_data) \
  { \
    reinterpret_cast<otype*>(m_data)[index] = data; \
  }
.fi
.PP
Definition at line 80 of file tlm_data_serializers.h.
.SH "Function Documentation"
.PP 
.SS "template<class T> void copy_from_array (T & data, unsigned int index, unsigned char * m_data)\fC [inline]\fP"
.PP
Definition at line 34 of file tlm_data_serializers.h.
.PP
References hostHasLittleEndianness().
.SS "template<class T> void copy_to_array (const T & data, unsigned int index, unsigned char * m_data)\fC [inline]\fP"
.PP
Definition at line 51 of file tlm_data_serializers.h.
.PP
References hostHasLittleEndianness().
.SS "TLM_COPY_FROM_ARRAY (unsigned long long)"
.PP
.SS "TLM_COPY_FROM_ARRAY (unsigned long)"
.PP
.SS "tlm_generic_payload::TLM_COPY_FROM_ARRAY (unsigned char)"
.PP
.SS "TLM_COPY_FROM_ARRAY (signed long long)"
.PP
.SS "tlm_generic_payload::TLM_COPY_FROM_ARRAY (signed char)"
.PP
.SS "TLM_COPY_TO_ARRAY (unsigned long long)"
.PP
.SS "TLM_COPY_TO_ARRAY (unsigned long)"
.PP
.SS "tlm_generic_payload::TLM_COPY_TO_ARRAY (unsigned char)"
.PP
.SS "TLM_COPY_TO_ARRAY (signed long long)"
.PP
.SS "tlm_generic_payload::TLM_COPY_TO_ARRAY (signed char)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
