.TH "tlm_generic_payload::tlm_extension_base" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_generic_payload::tlm_extension_base \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_generic_payload.h>\fP
.PP
Inherited by \fBtlm_generic_payload::tlm_extension< T >\fP.
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static unsigned int \fBregister_extension\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 314 of file tlm_generic_payload.h.
.SH "Member Function Documentation"
.PP 
.SS "static unsigned int tlm_generic_payload::tlm_extension_base::register_extension ()\fC [inline, static]\fP"
.PP
Definition at line 317 of file tlm_generic_payload.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
