.TH "tlm_nonblocking_get_port" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_nonblocking_get_port \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_nonblocking_port.h>\fP
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBtlm_nonblocking_get_if\fP< T > \fBget_if_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtlm_nonblocking_get_port\fP (const char *port_name)"
.br
.ti -1c
.RI "sc_event_finder & \fBok_to_get\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T> class tlm_nonblocking_get_port< T >"

.PP
Definition at line 26 of file tlm_nonblocking_port.h.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T> typedef \fBtlm_nonblocking_get_if\fP<T> \fBtlm_nonblocking_get_port\fP< T >::\fBget_if_type\fP"
.PP
Definition at line 30 of file tlm_nonblocking_port.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> \fBtlm_nonblocking_get_port\fP< T >::\fBtlm_nonblocking_get_port\fP (const char * port_name)\fC [inline]\fP"
.PP
Definition at line 32 of file tlm_nonblocking_port.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T> sc_event_finder& \fBtlm_nonblocking_get_port\fP< T >::ok_to_get () const\fC [inline]\fP"
.PP
Definition at line 35 of file tlm_nonblocking_port.h.
.PP
References tlm_nonblocking_get_if< T >::ok_to_get().

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
