.TH "tlm_put_get_imp" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_put_get_imp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_put_get_imp.h>\fP
.PP
Inherits \fBtlm_put_if< PUT_DATA >\fP, and \fBtlm_get_peek_if< GET_DATA >\fP.
.PP
Inherited by \fBtlm_annotated_put_get_imp< PUT_DATA, GET_DATA >\fP\fC [private]\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtlm_put_get_imp\fP (\fBtlm_put_if\fP< PUT_DATA > &p, \fBtlm_get_peek_if\fP< GET_DATA > &g)"
.br
.ti -1c
.RI "void \fBput\fP (const PUT_DATA &t)"
.br
.ti -1c
.RI "bool \fBnb_put\fP (const PUT_DATA &t)"
.br
.ti -1c
.RI "bool \fBnb_can_put\fP (\fBtlm_tag\fP< PUT_DATA > *t=0) const "
.br
.ti -1c
.RI "const sc_event & \fBok_to_put\fP (\fBtlm_tag\fP< PUT_DATA > *t=0) const "
.br
.ti -1c
.RI "GET_DATA \fBget\fP (\fBtlm_tag\fP< GET_DATA > *t=0)"
.br
.ti -1c
.RI "bool \fBnb_get\fP (GET_DATA &t)"
.br
.ti -1c
.RI "bool \fBnb_can_get\fP (\fBtlm_tag\fP< GET_DATA > *t=0) const "
.br
.ti -1c
.RI "virtual const sc_event & \fBok_to_get\fP (\fBtlm_tag\fP< GET_DATA > *t=0) const "
.br
.ti -1c
.RI "GET_DATA \fBpeek\fP (\fBtlm_tag\fP< GET_DATA > *t=0) const "
.br
.ti -1c
.RI "bool \fBnb_peek\fP (GET_DATA &t) const "
.br
.ti -1c
.RI "bool \fBnb_can_peek\fP (\fBtlm_tag\fP< GET_DATA > *t=0) const "
.br
.ti -1c
.RI "virtual const sc_event & \fBok_to_peek\fP (\fBtlm_tag\fP< GET_DATA > *t=0) const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBtlm_put_if\fP< PUT_DATA > & \fBput_fifo\fP"
.br
.ti -1c
.RI "\fBtlm_get_peek_if\fP< GET_DATA > & \fBget_fifo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename PUT_DATA, typename GET_DATA> class tlm_put_get_imp< PUT_DATA, GET_DATA >"

.PP
Definition at line 29 of file tlm_put_get_imp.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename PUT_DATA, typename GET_DATA> \fBtlm_put_get_imp\fP< PUT_DATA, GET_DATA >::\fBtlm_put_get_imp\fP (\fBtlm_put_if\fP< PUT_DATA > & p, \fBtlm_get_peek_if\fP< GET_DATA > & g)\fC [inline]\fP"
.PP
Definition at line 34 of file tlm_put_get_imp.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename PUT_DATA, typename GET_DATA> void \fBtlm_put_get_imp\fP< PUT_DATA, GET_DATA >::put (const PUT_DATA & t)\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_blocking_put_if< PUT_DATA >\fP.
.PP
Definition at line 40 of file tlm_put_get_imp.h.
.SS "template<typename PUT_DATA, typename GET_DATA> bool \fBtlm_put_get_imp\fP< PUT_DATA, GET_DATA >::nb_put (const PUT_DATA & t)\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_nonblocking_put_if< PUT_DATA >\fP.
.PP
Definition at line 42 of file tlm_put_get_imp.h.
.SS "template<typename PUT_DATA, typename GET_DATA> bool \fBtlm_put_get_imp\fP< PUT_DATA, GET_DATA >::nb_can_put (\fBtlm_tag\fP< PUT_DATA > * t = \fC0\fP) const\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_nonblocking_put_if< PUT_DATA >\fP.
.PP
Definition at line 43 of file tlm_put_get_imp.h.
.SS "template<typename PUT_DATA, typename GET_DATA> const sc_event& \fBtlm_put_get_imp\fP< PUT_DATA, GET_DATA >::ok_to_put (\fBtlm_tag\fP< PUT_DATA > * t = \fC0\fP) const\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_nonblocking_put_if< PUT_DATA >\fP.
.PP
Definition at line 46 of file tlm_put_get_imp.h.
.SS "template<typename PUT_DATA, typename GET_DATA> GET_DATA \fBtlm_put_get_imp\fP< PUT_DATA, GET_DATA >::get (\fBtlm_tag\fP< GET_DATA > * t = \fC0\fP)\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_blocking_get_if< GET_DATA >\fP.
.PP
Definition at line 52 of file tlm_put_get_imp.h.
.SS "template<typename PUT_DATA, typename GET_DATA> bool \fBtlm_put_get_imp\fP< PUT_DATA, GET_DATA >::nb_get (GET_DATA & t)\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_nonblocking_get_if< GET_DATA >\fP.
.PP
Definition at line 54 of file tlm_put_get_imp.h.
.SS "template<typename PUT_DATA, typename GET_DATA> bool \fBtlm_put_get_imp\fP< PUT_DATA, GET_DATA >::nb_can_get (\fBtlm_tag\fP< GET_DATA > * t = \fC0\fP) const\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_nonblocking_get_if< GET_DATA >\fP.
.PP
Definition at line 56 of file tlm_put_get_imp.h.
.SS "template<typename PUT_DATA, typename GET_DATA> virtual const sc_event& \fBtlm_put_get_imp\fP< PUT_DATA, GET_DATA >::ok_to_get (\fBtlm_tag\fP< GET_DATA > * t = \fC0\fP) const\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_nonblocking_get_if< GET_DATA >\fP.
.PP
Definition at line 60 of file tlm_put_get_imp.h.
.SS "template<typename PUT_DATA, typename GET_DATA> GET_DATA \fBtlm_put_get_imp\fP< PUT_DATA, GET_DATA >::peek (\fBtlm_tag\fP< GET_DATA > * t = \fC0\fP) const\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_blocking_peek_if< GET_DATA >\fP.
.PP
Definition at line 66 of file tlm_put_get_imp.h.
.SS "template<typename PUT_DATA, typename GET_DATA> bool \fBtlm_put_get_imp\fP< PUT_DATA, GET_DATA >::nb_peek (GET_DATA & t) const\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_nonblocking_peek_if< GET_DATA >\fP.
.PP
Definition at line 68 of file tlm_put_get_imp.h.
.SS "template<typename PUT_DATA, typename GET_DATA> bool \fBtlm_put_get_imp\fP< PUT_DATA, GET_DATA >::nb_can_peek (\fBtlm_tag\fP< GET_DATA > * t = \fC0\fP) const\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_nonblocking_peek_if< GET_DATA >\fP.
.PP
Definition at line 70 of file tlm_put_get_imp.h.
.SS "template<typename PUT_DATA, typename GET_DATA> virtual const sc_event& \fBtlm_put_get_imp\fP< PUT_DATA, GET_DATA >::ok_to_peek (\fBtlm_tag\fP< GET_DATA > * t = \fC0\fP) const\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_nonblocking_peek_if< GET_DATA >\fP.
.PP
Definition at line 74 of file tlm_put_get_imp.h.
.SH "Member Data Documentation"
.PP 
.SS "template<typename PUT_DATA, typename GET_DATA> \fBtlm_put_if\fP<PUT_DATA>& \fBtlm_put_get_imp\fP< PUT_DATA, GET_DATA >::\fBput_fifo\fP\fC [private]\fP"
.PP
Definition at line 79 of file tlm_put_get_imp.h.
.PP
Referenced by tlm_put_get_imp< RSP, REQ >::nb_can_put(), tlm_put_get_imp< RSP, REQ >::nb_put(), tlm_put_get_imp< RSP, REQ >::ok_to_put(), and tlm_put_get_imp< RSP, REQ >::put().
.SS "template<typename PUT_DATA, typename GET_DATA> \fBtlm_get_peek_if\fP<GET_DATA>& \fBtlm_put_get_imp\fP< PUT_DATA, GET_DATA >::\fBget_fifo\fP\fC [private]\fP"
.PP
Definition at line 80 of file tlm_put_get_imp.h.
.PP
Referenced by tlm_put_get_imp< RSP, REQ >::get(), tlm_put_get_imp< RSP, REQ >::nb_can_get(), tlm_put_get_imp< RSP, REQ >::nb_can_peek(), tlm_put_get_imp< RSP, REQ >::nb_get(), tlm_put_get_imp< RSP, REQ >::nb_peek(), tlm_put_get_imp< RSP, REQ >::ok_to_get(), tlm_put_get_imp< RSP, REQ >::ok_to_peek(), and tlm_put_get_imp< RSP, REQ >::peek().

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
