.TH "tlm_master_if" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_master_if \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_master_slave_ifs.h>\fP
.PP
Inherits \fBtlm_put_if< REQ >\fP, \fBtlm_get_peek_if< RSP >\fP, \fBtlm_blocking_master_if< REQ, RSP >< REQ, RSP >\fP, and \fBtlm_nonblocking_master_if< REQ, RSP >< REQ, RSP >\fP.
.PP
Inherited by \fBtlm_master_imp< REQ, RSP >\fP\fC [virtual]\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename REQ, typename RSP> class tlm_master_if< REQ, RSP >"

.PP
Definition at line 56 of file tlm_master_slave_ifs.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
