.TH "tlm_extension_base" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_extension_base \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_gp.h>\fP
.PP
Inherited by \fBtlm_extension< T >\fP.
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static unsigned int \fBregister_extension\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file tlm_gp.h.
.SH "Member Function Documentation"
.PP 
.SS "static unsigned int tlm_extension_base::register_extension ()\fC [inline, static]\fP"
.PP
Definition at line 41 of file tlm_gp.h.
.PP
References max_num_extensions().

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
