.TH "tlm_annotated" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_annotated \- TLM annotated header sub group.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtlm_delayed_transport_if\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated_transport_if\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated_nonblocking_get_if\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated_nonblocking_put_if\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated_get_if\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated_put_if\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated_nonblocking_get_peek_if\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated_get_peek_if\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated_nonblocking_master_if\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated_nonblocking_slave_if\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated_master_if\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated_slave_if\fP"
.br
.ti -1c
.RI "class \fBtlm_nonblocking_transport_if\fP"
.br
.ti -1c
.RI "class \fBtlm_peq\fP"
.br
.ti -1c
.RI "class \fBtlm_internal_annotated_fifo\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated_fifo\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated_req_rsp_channel\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBtlm_phase\fP { \fBBEGIN_REQ\fP, \fBEND_REQ\fP, \fBBEGIN_RESP\fP, \fBEND_RESP\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
TLM annotated header sub group. 

TLM annotated namespace. 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBtlm_annotated::tlm_phase\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIBEGIN_REQ \fP\fP
.TP
\fB\fIEND_REQ \fP\fP
.TP
\fB\fIBEGIN_RESP \fP\fP
.TP
\fB\fIEND_RESP \fP\fP

.PP
Definition at line 199 of file tlm_annotated.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
