.TH "tlm_generic_payload::tlm_extension" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_generic_payload::tlm_extension \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_generic_payload.h>\fP
.PP
Inherits \fBtlm_generic_payload::tlm_extension_base\fP.
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const unsigned int \fBID\fP = tlm_extension_base::register_extension()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T> class tlm_generic_payload::tlm_extension< T >"

.PP
Definition at line 332 of file tlm_generic_payload.h.
.SH "Member Data Documentation"
.PP 
.SS "template<typename T> const unsigned int \fBtlm_generic_payload::tlm_extension\fP< T >::\fBID\fP = tlm_extension_base::register_extension()\fC [inline, static]\fP"
.PP
Definition at line 335 of file tlm_generic_payload.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
