.TH "tlm_annotated_get_if" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_annotated_get_if \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_annotated_ifs.h>\fP
.PP
Inherits \fBtlm_core::tlm_blocking_get_if< T >< T >\fP, \fBtlm_annotated_nonblocking_get_if< T >< T >\fP, and \fBtlm_core::tlm_get_if< T >< T >\fP.
.PP
Inherited by \fBtlm_annotated_get_peek_if< T >\fP\fC [virtual]\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename T> class tlm_annotated_get_if< T >"

.PP
Definition at line 72 of file tlm_annotated_ifs.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
