.TH "tlm_fifo_config_size_if" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_fifo_config_size_if \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_fifo_ifs.h>\fP
.PP
Inherits \fBsc_interface\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBnb_expand\fP (unsigned int n=1)=0"
.br
.ti -1c
.RI "virtual void \fBnb_unbound\fP (unsigned int n=16)=0"
.br
.ti -1c
.RI "virtual bool \fBnb_reduce\fP (unsigned int n=1)=0"
.br
.ti -1c
.RI "virtual bool \fBnb_bound\fP (unsigned int n)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 68 of file tlm_fifo_ifs.h.
.SH "Member Function Documentation"
.PP 
.SS "virtual void tlm_fifo_config_size_if::nb_expand (unsigned int n = \fC1\fP)\fC [pure virtual]\fP"
.PP
.SS "virtual void tlm_fifo_config_size_if::nb_unbound (unsigned int n = \fC16\fP)\fC [pure virtual]\fP"
.PP
.SS "virtual bool tlm_fifo_config_size_if::nb_reduce (unsigned int n = \fC1\fP)\fC [pure virtual]\fP"
.PP
.SS "virtual bool tlm_fifo_config_size_if::nb_bound (unsigned int n)\fC [pure virtual]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
