.TH "tlm_annotated_nonblocking_get_if" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_annotated_nonblocking_get_if \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_annotated_ifs.h>\fP
.PP
Inherits \fBtlm_core::tlm_nonblocking_get_if< T >< T >\fP.
.PP
Inherited by \fBtlm_annotated_get_if< T >\fP\fC [virtual]\fP, and \fBtlm_annotated_nonblocking_get_peek_if< T >\fP\fC [virtual]\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBnb_get\fP (T &, const sc_time &)=0"
.br
.ti -1c
.RI "virtual bool \fBnb_can_get\fP (const sc_time &, \fBtlm_tag\fP< T > *t=0) const =0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T> class tlm_annotated_nonblocking_get_if< T >"

.PP
Definition at line 46 of file tlm_annotated_ifs.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T> virtual bool \fBtlm_annotated_nonblocking_get_if\fP< T >::nb_get (T &, const sc_time &)\fC [pure virtual]\fP"
.PP
Implemented in \fBtlm_annotated_fifo< T >\fP, \fBtlm_annotated_put_get_imp< PUT_DATA, GET_DATA >\fP, \fBtlm_annotated_put_get_imp< REQ, RSP >\fP, and \fBtlm_annotated_put_get_imp< RSP, REQ >\fP.
.PP
Referenced by tlm_annotated_put_get_imp< RSP, REQ >::nb_get().
.SS "template<typename T> virtual bool \fBtlm_annotated_nonblocking_get_if\fP< T >::nb_can_get (const sc_time &, \fBtlm_tag\fP< T > * t = \fC0\fP) const\fC [pure virtual]\fP"
.PP
Implemented in \fBtlm_annotated_fifo< T >\fP, \fBtlm_annotated_put_get_imp< PUT_DATA, GET_DATA >\fP, \fBtlm_annotated_put_get_imp< REQ, RSP >\fP, and \fBtlm_annotated_put_get_imp< RSP, REQ >\fP.
.PP
Referenced by tlm_annotated_put_get_imp< RSP, REQ >::nb_can_get().

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
