.TH "tlm_core::tlm_blocking_peek_if" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_core::tlm_blocking_peek_if \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_core.h>\fP
.PP
Inherits \fBsc_interface\fP.
.PP
Inherited by \fBtlm_core::tlm_blocking_get_peek_if< T >\fP\fC [virtual]\fP, \fBtlm_core::tlm_blocking_get_peek_if< RSP >\fP\fC [virtual]\fP, and \fBtlm_core::tlm_peek_if< T >\fP\fC [virtual]\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual T \fBpeek\fP (\fBtlm_tag\fP< T > *t=0) const =0"
.br
.ti -1c
.RI "virtual void \fBpeek\fP (T &t) const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T> class tlm_core::tlm_blocking_peek_if< T >"

.PP
Definition at line 137 of file tlm_core.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T> virtual T \fBtlm_core::tlm_blocking_peek_if\fP< T >::peek (\fBtlm_tag\fP< T > * t = \fC0\fP) const\fC [pure virtual]\fP"
.PP
Implemented in \fBtlm_annotated::tlm_annotated_fifo< T >\fP, and \fBtlm_annotated_fifo< T >\fP.
.SS "template<typename T> virtual void \fBtlm_core::tlm_blocking_peek_if\fP< T >::peek (T & t) const\fC [inline, virtual]\fP"
.PP
Definition at line 141 of file tlm_core.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
