.TH "tlm_transport_channel" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_transport_channel \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_req_rsp_channels.h>\fP
.PP
Inherits \fBsc_module\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtlm_transport_channel\fP ()"
.br
.ti -1c
.RI "\fBtlm_transport_channel\fP (sc_module_name nm)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "sc_export< \fBtlm_transport_if\fP< REQ, RSP > > \fBtarget_export\fP"
.br
.ti -1c
.RI "sc_export< \fBtlm_fifo_get_if\fP< REQ > > \fBget_request_export\fP"
.br
.ti -1c
.RI "sc_export< \fBtlm_fifo_put_if\fP< RSP > > \fBput_response_export\fP"
.br
.ti -1c
.RI "sc_export< \fBtlm_slave_if\fP< REQ, RSP > > \fBslave_export\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBdo_binding\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBtlm_req_rsp_channel\fP< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL > \fBreq_rsp\fP"
.br
.ti -1c
.RI "\fBtlm_transport_to_master\fP< REQ, RSP > \fBt2m\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_fifo<REQ>, typename RSP_CHANNEL = tlm_fifo<RSP>> class tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >"

.PP
Definition at line 99 of file tlm_req_rsp_channels.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_fifo<REQ>, typename RSP_CHANNEL = tlm_fifo<RSP>> \fBtlm_transport_channel\fP< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::\fBtlm_transport_channel\fP ()\fC [inline]\fP"
.PP
Definition at line 114 of file tlm_req_rsp_channels.h.
.PP
References tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::do_binding().
.SS "template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_fifo<REQ>, typename RSP_CHANNEL = tlm_fifo<RSP>> \fBtlm_transport_channel\fP< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::\fBtlm_transport_channel\fP (sc_module_name nm)\fC [inline]\fP"
.PP
Definition at line 123 of file tlm_req_rsp_channels.h.
.PP
References tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::do_binding().
.SH "Member Function Documentation"
.PP 
.SS "template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_fifo<REQ>, typename RSP_CHANNEL = tlm_fifo<RSP>> void \fBtlm_transport_channel\fP< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::do_binding ()\fC [inline, private]\fP"
.PP
Definition at line 133 of file tlm_req_rsp_channels.h.
.PP
References tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::get_request_export, tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::put_response_export, tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::req_rsp, tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::slave_export, tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::t2m, and tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::target_export.
.PP
Referenced by tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::tlm_transport_channel().
.SH "Member Data Documentation"
.PP 
.SS "template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_fifo<REQ>, typename RSP_CHANNEL = tlm_fifo<RSP>> sc_export< \fBtlm_transport_if\fP< REQ , RSP > > \fBtlm_transport_channel\fP< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::\fBtarget_export\fP"
.PP
Definition at line 105 of file tlm_req_rsp_channels.h.
.PP
Referenced by tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::do_binding().
.SS "template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_fifo<REQ>, typename RSP_CHANNEL = tlm_fifo<RSP>> sc_export< \fBtlm_fifo_get_if\fP< REQ > > \fBtlm_transport_channel\fP< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::\fBget_request_export\fP"
.PP
Definition at line 109 of file tlm_req_rsp_channels.h.
.PP
Referenced by tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::do_binding().
.SS "template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_fifo<REQ>, typename RSP_CHANNEL = tlm_fifo<RSP>> sc_export< \fBtlm_fifo_put_if\fP< RSP > > \fBtlm_transport_channel\fP< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::\fBput_response_export\fP"
.PP
Definition at line 110 of file tlm_req_rsp_channels.h.
.PP
Referenced by tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::do_binding().
.SS "template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_fifo<REQ>, typename RSP_CHANNEL = tlm_fifo<RSP>> sc_export< \fBtlm_slave_if\fP< REQ , RSP > > \fBtlm_transport_channel\fP< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::\fBslave_export\fP"
.PP
Definition at line 112 of file tlm_req_rsp_channels.h.
.PP
Referenced by tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::do_binding().
.SS "template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_fifo<REQ>, typename RSP_CHANNEL = tlm_fifo<RSP>> \fBtlm_req_rsp_channel\fP< REQ , RSP , REQ_CHANNEL , RSP_CHANNEL > \fBtlm_transport_channel\fP< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::\fBreq_rsp\fP\fC [private]\fP"
.PP
Definition at line 145 of file tlm_req_rsp_channels.h.
.PP
Referenced by tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::do_binding().
.SS "template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_fifo<REQ>, typename RSP_CHANNEL = tlm_fifo<RSP>> \fBtlm_transport_to_master\fP< REQ , RSP > \fBtlm_transport_channel\fP< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::\fBt2m\fP\fC [private]\fP"
.PP
Definition at line 146 of file tlm_req_rsp_channels.h.
.PP
Referenced by tlm_transport_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::do_binding().

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
