.TH "tlm_core::tlm_put_if" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_core::tlm_put_if \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_core.h>\fP
.PP
Inherits \fBtlm_core::tlm_blocking_put_if< T >< T >\fP, and \fBtlm_core::tlm_nonblocking_put_if< T >< T >\fP.
.PP
Inherited by \fBtlm_annotated::tlm_annotated_put_if< T >\fP\fC [virtual]\fP, \fBtlm_annotated::tlm_annotated_put_if< REQ >\fP\fC [virtual]\fP, \fBtlm_annotated::tlm_annotated_put_if< RSP >\fP\fC [virtual]\fP, \fBtlm_annotated_put_if< T >\fP\fC [virtual]\fP, and \fBtlm_core::tlm_slave_if< REQ, RSP >\fP\fC [virtual]\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename T> class tlm_core::tlm_put_if< T >"

.PP
Definition at line 129 of file tlm_core.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
