.TH "C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_ports/tlm_ports.h" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_ports/tlm_ports.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'tlm_initiator_port.h'\fP
.br
\fC#include 'tlm_target_port.h'\fP
.br
\fC#include 'tlm_master_socket.h'\fP
.br
\fC#include 'tlm_slave_socket.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtlm_ports\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtlm_ports::tlm_target_port_base\fP"
.br
.RI "\fIClass \fBtlm_target_port_base\fP: This class is a base class for tlm_target port class. \fP"
.ti -1c
.RI "class \fBtlm_ports::tlm_initiator_port_base\fP"
.br
.RI "\fIClass \fBtlm_initiator_port_base\fP: This class is a base class for tlm_initiator port. \fP"
.ti -1c
.RI "class \fBtlm_ports::tlm_target_port< IF >\fP"
.br
.RI "\fIClass \fBtlm_target_port\fP: port to be instantiated on the target side. \fP"
.ti -1c
.RI "class \fBtlm_ports::tlm_initiator_port< IF, N >\fP"
.br
.RI "\fIClass \fBtlm_initiator_port\fP: port to be instantiated on the initiator side. \fP"
.ti -1c
.RI "class \fBtlm_ports::tlm_master_socket< IF >\fP"
.br
.ti -1c
.RI "class \fBtlm_ports::tlm_slave_socket< IF >\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
