.TH "tlm_core::tlm_blocking_put_if" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_core::tlm_blocking_put_if \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_core.h>\fP
.PP
Inherits \fBsc_interface\fP.
.PP
Inherited by \fBtlm_annotated::tlm_annotated_put_if< T >\fP\fC [virtual]\fP, \fBtlm_annotated::tlm_annotated_put_if< REQ >\fP\fC [virtual]\fP, \fBtlm_annotated::tlm_annotated_put_if< RSP >\fP\fC [virtual]\fP, \fBtlm_annotated_put_if< T >\fP\fC [virtual]\fP, \fBtlm_core::tlm_blocking_master_if< REQ, RSP >\fP\fC [virtual]\fP, and \fBtlm_core::tlm_put_if< T >\fP\fC [virtual]\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBput\fP (const T &t)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T> class tlm_core::tlm_blocking_put_if< T >"

.PP
Definition at line 94 of file tlm_core.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T> virtual void \fBtlm_core::tlm_blocking_put_if\fP< T >::put (const T & t)\fC [pure virtual]\fP"
.PP
Implemented in \fBtlm_annotated::tlm_annotated_fifo< T >\fP, and \fBtlm_annotated_fifo< T >\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
