.TH "tlm_annotated::tlm_annotated_transport_if" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_annotated::tlm_annotated_transport_if \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_annotated.h>\fP
.PP
Inherits \fBtlm_core::tlm_transport_if< REQ, RSP >< REQ, RSP >\fP, and \fBtlm_annotated::tlm_delayed_transport_if< REQ, RSP >< REQ, RSP >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename REQ, typename RSP> class tlm_annotated::tlm_annotated_transport_if< REQ, RSP >"

.PP
Definition at line 47 of file tlm_annotated.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
