.TH "C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_core/tlm_platform.h" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_core/tlm_platform.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB__TLM_PLATFORM_H__\fP"
.br
.ti -1c
.RI "#define \fB_INT64_T\fP"
.br
.RI "\fIstandard scalar data types \fP"
.ti -1c
.RI "#define \fB_UINT64_T\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef long long \fBint64_t\fP"
.br
.ti -1c
.RI "typedef unsigned long long \fBuint64_t\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define __TLM_PLATFORM_H__"
.PP
Definition at line 22 of file tlm_platform.h.
.SS "#define _INT64_T"
.PP
standard scalar data types 
.PP
Definition at line 32 of file tlm_platform.h.
.SS "#define _UINT64_T"
.PP
Definition at line 37 of file tlm_platform.h.
.SH "Typedef Documentation"
.PP 
.SS "typedef long long \fBint64_t\fP"
.PP
Definition at line 33 of file tlm_platform.h.
.SS "typedef unsigned long long \fBuint64_t\fP"
.PP
Definition at line 38 of file tlm_platform.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
