.TH "C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_core/tlm_req_rsp/tlm_put_get_imp.h" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_core/tlm_req_rsp/tlm_put_get_imp.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'tlm_h/tlm_core/tlm_interfaces/tlm_master_slave_ifs.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtlm_put_get_imp< PUT_DATA, GET_DATA >\fP"
.br
.ti -1c
.RI "class \fBtlm_master_imp< REQ, RSP >\fP"
.br
.ti -1c
.RI "class \fBtlm_slave_imp< REQ, RSP >\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
