.TH "tlm_core::tlm_nonblocking_slave_if" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_core::tlm_nonblocking_slave_if \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_core.h>\fP
.PP
Inherits \fBtlm_core::tlm_nonblocking_put_if< RSP >\fP, and \fBtlm_core::tlm_nonblocking_get_peek_if< REQ >\fP.
.PP
Inherited by \fBtlm_annotated::tlm_annotated_nonblocking_slave_if< REQ, RSP >\fP\fC [virtual]\fP, \fBtlm_annotated_nonblocking_slave_if< REQ, RSP >\fP\fC [virtual]\fP, and \fBtlm_core::tlm_slave_if< REQ, RSP >\fP\fC [virtual]\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename REQ, typename RSP> class tlm_core::tlm_nonblocking_slave_if< REQ, RSP >"

.PP
Definition at line 230 of file tlm_core.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
