.TH "tlm_annotated::tlm_nonblocking_transport_if" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_annotated::tlm_nonblocking_transport_if \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_annotated.h>\fP
.PP
Inherits \fBsc_interface\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBnb_transport\fP (TRANS &trans, \fBtlm_phase\fP &phase, sc_time &t)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename TRANS> class tlm_annotated::tlm_nonblocking_transport_if< TRANS >"

.PP
Definition at line 202 of file tlm_annotated.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename TRANS> virtual bool \fBtlm_annotated::tlm_nonblocking_transport_if\fP< TRANS >::nb_transport (TRANS & trans, \fBtlm_phase\fP & phase, sc_time & t)\fC [pure virtual]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
