.TH "tlm_ports" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_ports \- TLM ports header group.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtlm_target_port_base\fP"
.br
.RI "\fIClass \fBtlm_target_port_base\fP: This class is a base class for tlm_target port class. \fP"
.ti -1c
.RI "class \fBtlm_initiator_port_base\fP"
.br
.RI "\fIClass \fBtlm_initiator_port_base\fP: This class is a base class for tlm_initiator port. \fP"
.ti -1c
.RI "class \fBtlm_target_port\fP"
.br
.RI "\fIClass \fBtlm_target_port\fP: port to be instantiated on the target side. \fP"
.ti -1c
.RI "class \fBtlm_initiator_port\fP"
.br
.RI "\fIClass \fBtlm_initiator_port\fP: port to be instantiated on the initiator side. \fP"
.ti -1c
.RI "class \fBtlm_master_socket\fP"
.br
.ti -1c
.RI "class \fBtlm_slave_socket\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
TLM ports header group. 
.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
