.TH "tlm_annotated_master_imp" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_annotated_master_imp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_annotated_put_get_imp.h>\fP
.PP
Inherits \fBtlm_annotated_put_get_imp< REQ, RSP >\fP, and \fBtlm_annotated_master_if< REQ, RSP >< REQ, RSP >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtlm_annotated_master_imp\fP (\fBtlm_annotated_put_if\fP< REQ > &req, \fBtlm_annotated_get_peek_if\fP< RSP > &rsp)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename REQ, typename RSP> class tlm_annotated_master_imp< REQ, RSP >"

.PP
Definition at line 67 of file tlm_annotated_put_get_imp.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename REQ, typename RSP> \fBtlm_annotated_master_imp\fP< REQ, RSP >::\fBtlm_annotated_master_imp\fP (\fBtlm_annotated_put_if\fP< REQ > & req, \fBtlm_annotated_get_peek_if\fP< RSP > & rsp)\fC [inline]\fP"
.PP
Definition at line 73 of file tlm_annotated_put_get_imp.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
