.TH "tlm_annotated::tlm_annotated_fifo" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_annotated::tlm_annotated_fifo \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_annotated.h>\fP
.PP
Inherits \fBsc_module\fP, \fBtlm_annotated::tlm_annotated_put_if< T >< T >\fP, and \fBtlm_annotated::tlm_annotated_get_peek_if< T >< T >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtlm_annotated_fifo\fP (sc_module_name nm, int size=1)"
.br
.ti -1c
.RI "\fBtlm_annotated_fifo\fP (int size=1)"
.br
.ti -1c
.RI "bool \fBnb_can_put\fP (tlm_tag< T > *t=0) const "
.br
.ti -1c
.RI "bool \fBnb_can_get\fP (tlm_tag< T > *t=0) const "
.br
.ti -1c
.RI "bool \fBnb_can_peek\fP (tlm_tag< T > *t=0) const "
.br
.ti -1c
.RI "virtual bool \fBnb_can_put\fP (const sc_time &time, tlm_tag< T > *t=0) const "
.br
.ti -1c
.RI "virtual bool \fBnb_can_get\fP (const sc_time &time, tlm_tag< T > *t=0) const "
.br
.ti -1c
.RI "const sc_event & \fBok_to_put\fP (tlm_tag< T > *t=0) const "
.br
.ti -1c
.RI "const sc_event & \fBok_to_get\fP (tlm_tag< T > *t=0) const "
.br
.ti -1c
.RI "const sc_event & \fBok_to_peek\fP (tlm_tag< T > *t=0) const "
.br
.ti -1c
.RI "bool \fBnb_put\fP (const T &t)"
.br
.ti -1c
.RI "bool \fBnb_get\fP (T &t)"
.br
.ti -1c
.RI "bool \fBnb_peek\fP (T &t) const "
.br
.ti -1c
.RI "bool \fBnb_put\fP (const T &transaction, const sc_time &time)"
.br
.ti -1c
.RI "virtual bool \fBnb_get\fP (T &transaction, const sc_time &time)"
.br
.ti -1c
.RI "void \fBput\fP (const T &t)"
.br
.ti -1c
.RI "T \fBget\fP (tlm_tag< T > *t=0)"
.br
.ti -1c
.RI "T \fBpeek\fP (tlm_tag< T > *t=0) const "
.br
.ti -1c
.RI "int \fBsize\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBtlm_internal_annotated_fifo\fP< T > \fBm_fifo\fP"
.br
.ti -1c
.RI "\fBtlm_peq\fP< T > \fBm_put_peq\fP"
.br
.ti -1c
.RI "\fBtlm_peq\fP< tlm_tag< T > * > \fBm_get_peq\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBm_size\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T> class tlm_annotated::tlm_annotated_fifo< T >"

.PP
Definition at line 539 of file tlm_annotated.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> \fBtlm_annotated::tlm_annotated_fifo\fP< T >::\fBtlm_annotated_fifo\fP (sc_module_name nm, int size = \fC1\fP)\fC [inline]\fP"
.PP
Definition at line 546 of file tlm_annotated.h.
.SS "template<typename T> \fBtlm_annotated::tlm_annotated_fifo\fP< T >::\fBtlm_annotated_fifo\fP (int size = \fC1\fP)\fC [inline]\fP"
.PP
Definition at line 558 of file tlm_annotated.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T> bool \fBtlm_annotated::tlm_annotated_fifo\fP< T >::nb_can_put (tlm_tag< T > * t = \fC0\fP) const\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_core::tlm_nonblocking_put_if< T >\fP.
.PP
Definition at line 571 of file tlm_annotated.h.
.SS "template<typename T> bool \fBtlm_annotated::tlm_annotated_fifo\fP< T >::nb_can_get (tlm_tag< T > * t = \fC0\fP) const\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_core::tlm_nonblocking_get_if< T >\fP.
.PP
Definition at line 575 of file tlm_annotated.h.
.SS "template<typename T> bool \fBtlm_annotated::tlm_annotated_fifo\fP< T >::nb_can_peek (tlm_tag< T > * t = \fC0\fP) const\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_core::tlm_nonblocking_peek_if< T >\fP.
.PP
Definition at line 579 of file tlm_annotated.h.
.SS "template<typename T> virtual bool \fBtlm_annotated::tlm_annotated_fifo\fP< T >::nb_can_put (const sc_time & time, tlm_tag< T > * t = \fC0\fP) const\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_annotated::tlm_annotated_nonblocking_put_if< T >\fP.
.PP
Definition at line 594 of file tlm_annotated.h.
.SS "template<typename T> virtual bool \fBtlm_annotated::tlm_annotated_fifo\fP< T >::nb_can_get (const sc_time & time, tlm_tag< T > * t = \fC0\fP) const\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_annotated::tlm_annotated_nonblocking_get_if< T >\fP.
.PP
Definition at line 598 of file tlm_annotated.h.
.SS "template<typename T> const sc_event& \fBtlm_annotated::tlm_annotated_fifo\fP< T >::ok_to_put (tlm_tag< T > * t = \fC0\fP) const\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_core::tlm_nonblocking_put_if< T >\fP.
.PP
Definition at line 604 of file tlm_annotated.h.
.SS "template<typename T> const sc_event& \fBtlm_annotated::tlm_annotated_fifo\fP< T >::ok_to_get (tlm_tag< T > * t = \fC0\fP) const\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_core::tlm_nonblocking_get_if< T >\fP.
.PP
Definition at line 608 of file tlm_annotated.h.
.SS "template<typename T> const sc_event& \fBtlm_annotated::tlm_annotated_fifo\fP< T >::ok_to_peek (tlm_tag< T > * t = \fC0\fP) const\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_core::tlm_nonblocking_peek_if< T >\fP.
.PP
Definition at line 612 of file tlm_annotated.h.
.SS "template<typename T> bool \fBtlm_annotated::tlm_annotated_fifo\fP< T >::nb_put (const T & t)\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_core::tlm_nonblocking_put_if< T >\fP.
.PP
Definition at line 618 of file tlm_annotated.h.
.SS "template<typename T> bool \fBtlm_annotated::tlm_annotated_fifo\fP< T >::nb_get (T & t)\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_core::tlm_nonblocking_get_if< T >\fP.
.PP
Definition at line 630 of file tlm_annotated.h.
.SS "template<typename T> bool \fBtlm_annotated::tlm_annotated_fifo\fP< T >::nb_peek (T & t) const\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_core::tlm_nonblocking_peek_if< T >\fP.
.PP
Definition at line 642 of file tlm_annotated.h.
.SS "template<typename T> bool \fBtlm_annotated::tlm_annotated_fifo\fP< T >::nb_put (const T & transaction, const sc_time & time)\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_annotated::tlm_annotated_nonblocking_put_if< T >\fP.
.PP
Definition at line 649 of file tlm_annotated.h.
.SS "template<typename T> virtual bool \fBtlm_annotated::tlm_annotated_fifo\fP< T >::nb_get (T & transaction, const sc_time & time)\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_annotated::tlm_annotated_nonblocking_get_if< T >\fP.
.PP
Definition at line 660 of file tlm_annotated.h.
.SS "template<typename T> void \fBtlm_annotated::tlm_annotated_fifo\fP< T >::put (const T & t)\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_core::tlm_blocking_put_if< T >\fP.
.PP
Definition at line 674 of file tlm_annotated.h.
.SS "template<typename T> T \fBtlm_annotated::tlm_annotated_fifo\fP< T >::get (tlm_tag< T > * t = \fC0\fP)\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_core::tlm_blocking_get_if< T >\fP.
.PP
Definition at line 680 of file tlm_annotated.h.
.SS "template<typename T> T \fBtlm_annotated::tlm_annotated_fifo\fP< T >::peek (tlm_tag< T > * t = \fC0\fP) const\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_core::tlm_blocking_peek_if< T >\fP.
.PP
Definition at line 691 of file tlm_annotated.h.
.SS "template<typename T> int \fBtlm_annotated::tlm_annotated_fifo\fP< T >::size ()\fC [inline]\fP"
.PP
Definition at line 695 of file tlm_annotated.h.
.SH "Member Data Documentation"
.PP 
.SS "template<typename T> int \fBtlm_annotated::tlm_annotated_fifo\fP< T >::\fBm_size\fP\fC [private]\fP"
.PP
Definition at line 698 of file tlm_annotated.h.
.SS "template<typename T> \fBtlm_internal_annotated_fifo\fP<T> \fBtlm_annotated::tlm_annotated_fifo\fP< T >::\fBm_fifo\fP\fC [protected]\fP"
.PP
Definition at line 702 of file tlm_annotated.h.
.SS "template<typename T> \fBtlm_peq\fP<T> \fBtlm_annotated::tlm_annotated_fifo\fP< T >::\fBm_put_peq\fP\fC [protected]\fP"
.PP
Definition at line 704 of file tlm_annotated.h.
.SS "template<typename T> \fBtlm_peq\fP< tlm_tag<T> *> \fBtlm_annotated::tlm_annotated_fifo\fP< T >::\fBm_get_peq\fP\fC [protected]\fP"
.PP
Definition at line 705 of file tlm_annotated.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
