.TH "tlm_annotated_req_rsp_channel" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_annotated_req_rsp_channel \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_annotated_req_rsp.h>\fP
.PP
Inherits \fBsc_module\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtlm_annotated_req_rsp_channel\fP (int req_size=1, int rsp_size=1)"
.br
.ti -1c
.RI "\fBtlm_annotated_req_rsp_channel\fP (sc_module_name module_name, int req_size=1, int rsp_size=1)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "sc_export< \fBtlm_annotated_get_peek_if\fP< REQ > > \fBget_request_export\fP"
.br
.ti -1c
.RI "sc_export< \fBtlm_annotated_put_if\fP< RSP > > \fBput_response_export\fP"
.br
.ti -1c
.RI "sc_export< \fBtlm_annotated_put_if\fP< REQ > > \fBput_request_export\fP"
.br
.ti -1c
.RI "sc_export< \fBtlm_annotated_get_peek_if\fP< RSP > > \fBget_response_export\fP"
.br
.ti -1c
.RI "sc_export< \fBtlm_annotated_master_if\fP< REQ, RSP > > \fBmaster_export\fP"
.br
.ti -1c
.RI "sc_export< \fBtlm_annotated_slave_if\fP< REQ, RSP > > \fBslave_export\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "REQ_CHANNEL \fBrequest_fifo\fP"
.br
.ti -1c
.RI "RSP_CHANNEL \fBresponse_fifo\fP"
.br
.ti -1c
.RI "\fBtlm_annotated_master_imp\fP< REQ, RSP > \fBmaster\fP"
.br
.ti -1c
.RI "\fBtlm_annotated_slave_imp\fP< REQ, RSP > \fBslave\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBbind_exports\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_annotated_fifo<REQ>, typename RSP_CHANNEL = tlm_annotated_fifo<RSP>> class tlm_annotated_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >"

.PP
Definition at line 12 of file tlm_annotated_req_rsp.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_annotated_fifo<REQ>, typename RSP_CHANNEL = tlm_annotated_fifo<RSP>> \fBtlm_annotated_req_rsp_channel\fP< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::\fBtlm_annotated_req_rsp_channel\fP (int req_size = \fC1\fP, int rsp_size = \fC1\fP)\fC [inline]\fP"
.PP
Definition at line 31 of file tlm_annotated_req_rsp.h.
.PP
References tlm_annotated_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::bind_exports().
.SS "template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_annotated_fifo<REQ>, typename RSP_CHANNEL = tlm_annotated_fifo<RSP>> \fBtlm_annotated_req_rsp_channel\fP< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::\fBtlm_annotated_req_rsp_channel\fP (sc_module_name module_name, int req_size = \fC1\fP, int rsp_size = \fC1\fP)\fC [inline]\fP"
.PP
Definition at line 43 of file tlm_annotated_req_rsp.h.
.PP
References tlm_annotated_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::bind_exports().
.SH "Member Function Documentation"
.PP 
.SS "template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_annotated_fifo<REQ>, typename RSP_CHANNEL = tlm_annotated_fifo<RSP>> void \fBtlm_annotated_req_rsp_channel\fP< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::bind_exports ()\fC [inline, private]\fP"
.PP
Definition at line 57 of file tlm_annotated_req_rsp.h.
.PP
References tlm_annotated_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::get_request_export, tlm_annotated_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::get_response_export, tlm_annotated_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::master, tlm_annotated_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::master_export, tlm_annotated_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::put_request_export, tlm_annotated_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::put_response_export, tlm_annotated_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::request_fifo, tlm_annotated_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::response_fifo, tlm_annotated_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::slave, and tlm_annotated_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::slave_export.
.PP
Referenced by tlm_annotated_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::tlm_annotated_req_rsp_channel().
.SH "Member Data Documentation"
.PP 
.SS "template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_annotated_fifo<REQ>, typename RSP_CHANNEL = tlm_annotated_fifo<RSP>> sc_export< \fBtlm_annotated_get_peek_if\fP< REQ > > \fBtlm_annotated_req_rsp_channel\fP< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::\fBget_request_export\fP"
.PP
Definition at line 17 of file tlm_annotated_req_rsp.h.
.PP
Referenced by tlm_annotated_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::bind_exports().
.SS "template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_annotated_fifo<REQ>, typename RSP_CHANNEL = tlm_annotated_fifo<RSP>> sc_export< \fBtlm_annotated_put_if\fP< RSP > > \fBtlm_annotated_req_rsp_channel\fP< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::\fBput_response_export\fP"
.PP
Definition at line 18 of file tlm_annotated_req_rsp.h.
.PP
Referenced by tlm_annotated_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::bind_exports().
.SS "template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_annotated_fifo<REQ>, typename RSP_CHANNEL = tlm_annotated_fifo<RSP>> sc_export< \fBtlm_annotated_put_if\fP< REQ > > \fBtlm_annotated_req_rsp_channel\fP< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::\fBput_request_export\fP"
.PP
Definition at line 22 of file tlm_annotated_req_rsp.h.
.PP
Referenced by tlm_annotated_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::bind_exports().
.SS "template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_annotated_fifo<REQ>, typename RSP_CHANNEL = tlm_annotated_fifo<RSP>> sc_export< \fBtlm_annotated_get_peek_if\fP< RSP > > \fBtlm_annotated_req_rsp_channel\fP< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::\fBget_response_export\fP"
.PP
Definition at line 23 of file tlm_annotated_req_rsp.h.
.PP
Referenced by tlm_annotated_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::bind_exports().
.SS "template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_annotated_fifo<REQ>, typename RSP_CHANNEL = tlm_annotated_fifo<RSP>> sc_export< \fBtlm_annotated_master_if\fP< REQ , RSP > > \fBtlm_annotated_req_rsp_channel\fP< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::\fBmaster_export\fP"
.PP
Definition at line 27 of file tlm_annotated_req_rsp.h.
.PP
Referenced by tlm_annotated_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::bind_exports().
.SS "template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_annotated_fifo<REQ>, typename RSP_CHANNEL = tlm_annotated_fifo<RSP>> sc_export< \fBtlm_annotated_slave_if\fP< REQ , RSP > > \fBtlm_annotated_req_rsp_channel\fP< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::\fBslave_export\fP"
.PP
Definition at line 28 of file tlm_annotated_req_rsp.h.
.PP
Referenced by tlm_annotated_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::bind_exports().
.SS "template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_annotated_fifo<REQ>, typename RSP_CHANNEL = tlm_annotated_fifo<RSP>> REQ_CHANNEL \fBtlm_annotated_req_rsp_channel\fP< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::\fBrequest_fifo\fP\fC [protected]\fP"
.PP
Definition at line 71 of file tlm_annotated_req_rsp.h.
.PP
Referenced by tlm_annotated_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::bind_exports().
.SS "template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_annotated_fifo<REQ>, typename RSP_CHANNEL = tlm_annotated_fifo<RSP>> RSP_CHANNEL \fBtlm_annotated_req_rsp_channel\fP< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::\fBresponse_fifo\fP\fC [protected]\fP"
.PP
Definition at line 72 of file tlm_annotated_req_rsp.h.
.PP
Referenced by tlm_annotated_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::bind_exports().
.SS "template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_annotated_fifo<REQ>, typename RSP_CHANNEL = tlm_annotated_fifo<RSP>> \fBtlm_annotated_master_imp\fP< REQ , RSP > \fBtlm_annotated_req_rsp_channel\fP< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::\fBmaster\fP\fC [protected]\fP"
.PP
Definition at line 74 of file tlm_annotated_req_rsp.h.
.PP
Referenced by tlm_annotated_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::bind_exports().
.SS "template<typename REQ, typename RSP, typename REQ_CHANNEL = tlm_annotated_fifo<REQ>, typename RSP_CHANNEL = tlm_annotated_fifo<RSP>> \fBtlm_annotated_slave_imp\fP< REQ , RSP > \fBtlm_annotated_req_rsp_channel\fP< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::\fBslave\fP\fC [protected]\fP"
.PP
Definition at line 75 of file tlm_annotated_req_rsp.h.
.PP
Referenced by tlm_annotated_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >::bind_exports().

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
