.TH "tlm_annotated::tlm_internal_annotated_fifo" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_annotated::tlm_internal_annotated_fifo \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_annotated.h>\fP
.PP
Inherits \fBanalysis::analysis_if< T >< T >\fP, and \fBanalysis::analysis_if< T >< tlm_tag< T > * >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef tlm_tag< T > * \fBmy_tag_ptr\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtlm_internal_annotated_fifo\fP (const char *nm, int size)"
.br
.ti -1c
.RI "void \fBwrite\fP (const T &t)"
.br
.ti -1c
.RI "void \fBwrite\fP (const \fBmy_tag_ptr\fP &)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T> class tlm_annotated::tlm_internal_annotated_fifo< T >"

.PP
Definition at line 496 of file tlm_annotated.h.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T> typedef tlm_tag<T>* \fBtlm_annotated::tlm_internal_annotated_fifo\fP< T >::\fBmy_tag_ptr\fP"
.PP
Definition at line 502 of file tlm_annotated.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> \fBtlm_annotated::tlm_internal_annotated_fifo\fP< T >::\fBtlm_internal_annotated_fifo\fP (const char * nm, int size)\fC [inline]\fP"
.PP
Definition at line 504 of file tlm_annotated.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T> void \fBtlm_annotated::tlm_internal_annotated_fifo\fP< T >::write (const T & t)\fC [inline, virtual]\fP"
.PP
Implements \fBanalysis::analysis_if< T >\fP.
.PP
Definition at line 507 of file tlm_annotated.h.
.SS "template<typename T> void \fBtlm_annotated::tlm_internal_annotated_fifo\fP< T >::write (const \fBmy_tag_ptr\fP &)\fC [inline]\fP"
.PP
Definition at line 512 of file tlm_annotated.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
