.TH "tlm_nonblocking_slave_if" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_nonblocking_slave_if \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_master_slave_ifs.h>\fP
.PP
Inherits \fBtlm_nonblocking_put_if< RSP >\fP, and \fBtlm_nonblocking_get_peek_if< REQ >\fP.
.PP
Inherited by \fBtlm_slave_if< REQ, RSP >\fP\fC [virtual]\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename REQ, typename RSP> class tlm_nonblocking_slave_if< REQ, RSP >"

.PP
Definition at line 49 of file tlm_master_slave_ifs.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
