.TH "tlm_generic_payload::tlm_generic_payload" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_generic_payload::tlm_generic_payload \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_generic_payload.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtlm_generic_payload\fP ()"
.br
.ti -1c
.RI "virtual \fB~tlm_generic_payload\fP ()"
.br
.ti -1c
.RI "\fBtlm_command\fP \fBget_command\fP () const "
.br
.ti -1c
.RI "sc_dt::uint64 \fBget_address\fP () const "
.br
.ti -1c
.RI "unsigned int \fBget_burst_length\fP () const "
.br
.ti -1c
.RI "unsigned int \fBget_burst_data_size\fP () const "
.br
.ti -1c
.RI "\fBtlm_burst_mode\fP \fBget_burst_mode\fP () const "
.br
.ti -1c
.RI "unsigned char * \fBget_data_ptr\fP () const "
.br
.ti -1c
.RI "\fBtlm_response_status\fP \fBget_response_status\fP () const "
.br
.ti -1c
.RI "bool \fBget_lock\fP () const "
.br
.ti -1c
.RI "void \fBset_command\fP (const \fBtlm_command\fP command)"
.br
.ti -1c
.RI "void \fBset_address\fP (const sc_dt::uint64 address)"
.br
.ti -1c
.RI "void \fBset_burst_length\fP (const unsigned int burst_length)"
.br
.ti -1c
.RI "void \fBset_burst_data_size\fP (const unsigned int burst_data_size)"
.br
.ti -1c
.RI "void \fBset_burst_mode\fP (const \fBtlm_burst_mode\fP burst_mode)"
.br
.ti -1c
.RI "void \fBset_data_ptr\fP (unsigned char *data)"
.br
.ti -1c
.RI "void \fBset_response_status\fP (const \fBtlm_response_status\fP response_status)"
.br
.ti -1c
.RI "void \fBset_lock\fP (const bool lock)"
.br
.ti -1c
.RI "template<typename T> void \fBset_extension\fP (T *ext)"
.br
.ti -1c
.RI "void \fBset_extension\fP (unsigned int index, \fBtlm_extension_base\fP *ext)"
.br
.ti -1c
.RI "template<typename T> void \fBget_extension\fP (T *&ext)"
.br
.ti -1c
.RI "\fBtlm_extension_base\fP * \fBget_extension\fP (unsigned int index)"
.br
.ti -1c
.RI "template<typename T> void \fBclear_extension\fP (const T *ext)"
.br
.ti -1c
.RI "void \fBclear_extension\fP (unsigned int index)"
.br
.ti -1c
.RI "void \fBresize_extensions\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtlm_command\fP \fBm_command\fP"
.br
.ti -1c
.RI "sc_dt::uint64 \fBm_address\fP"
.br
.ti -1c
.RI "unsigned char * \fBm_data\fP"
.br
.ti -1c
.RI "unsigned int \fBm_burst_length\fP"
.br
.ti -1c
.RI "unsigned int \fBm_burst_data_size\fP"
.br
.ti -1c
.RI "\fBtlm_burst_mode\fP \fBm_burst_mode\fP"
.br
.ti -1c
.RI "\fBtlm_response_status\fP \fBm_response_status\fP"
.br
.ti -1c
.RI "bool \fBm_lock\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBtlm_array\fP< \fBtlm_extension_base\fP * > \fBm_extensions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 369 of file tlm_generic_payload.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tlm_generic_payload::tlm_generic_payload::tlm_generic_payload ()\fC [inline]\fP"
.PP
Definition at line 377 of file tlm_generic_payload.h.
.SS "virtual tlm_generic_payload::tlm_generic_payload::~tlm_generic_payload ()\fC [inline, virtual]\fP"
.PP
Definition at line 394 of file tlm_generic_payload.h.
.SH "Member Function Documentation"
.PP 
.SS "\fBtlm_command\fP tlm_generic_payload::tlm_generic_payload::get_command () const\fC [inline]\fP"
.PP
Definition at line 400 of file tlm_generic_payload.h.
.SS "sc_dt::uint64 tlm_generic_payload::tlm_generic_payload::get_address () const\fC [inline]\fP"
.PP
Definition at line 401 of file tlm_generic_payload.h.
.SS "unsigned int tlm_generic_payload::tlm_generic_payload::get_burst_length () const\fC [inline]\fP"
.PP
Definition at line 402 of file tlm_generic_payload.h.
.SS "unsigned int tlm_generic_payload::tlm_generic_payload::get_burst_data_size () const\fC [inline]\fP"
.PP
Definition at line 403 of file tlm_generic_payload.h.
.SS "\fBtlm_burst_mode\fP tlm_generic_payload::tlm_generic_payload::get_burst_mode () const\fC [inline]\fP"
.PP
Definition at line 404 of file tlm_generic_payload.h.
.SS "unsigned char* tlm_generic_payload::tlm_generic_payload::get_data_ptr () const\fC [inline]\fP"
.PP
Definition at line 405 of file tlm_generic_payload.h.
.SS "\fBtlm_response_status\fP tlm_generic_payload::tlm_generic_payload::get_response_status () const\fC [inline]\fP"
.PP
Definition at line 406 of file tlm_generic_payload.h.
.SS "bool tlm_generic_payload::tlm_generic_payload::get_lock () const\fC [inline]\fP"
.PP
Definition at line 407 of file tlm_generic_payload.h.
.SS "void tlm_generic_payload::tlm_generic_payload::set_command (const \fBtlm_command\fP command)\fC [inline]\fP"
.PP
Definition at line 409 of file tlm_generic_payload.h.
.SS "void tlm_generic_payload::tlm_generic_payload::set_address (const sc_dt::uint64 address)\fC [inline]\fP"
.PP
Definition at line 411 of file tlm_generic_payload.h.
.SS "void tlm_generic_payload::tlm_generic_payload::set_burst_length (const unsigned int burst_length)\fC [inline]\fP"
.PP
Definition at line 413 of file tlm_generic_payload.h.
.SS "void tlm_generic_payload::tlm_generic_payload::set_burst_data_size (const unsigned int burst_data_size)\fC [inline]\fP"
.PP
Definition at line 415 of file tlm_generic_payload.h.
.SS "void tlm_generic_payload::tlm_generic_payload::set_burst_mode (const \fBtlm_burst_mode\fP burst_mode)\fC [inline]\fP"
.PP
Definition at line 417 of file tlm_generic_payload.h.
.SS "void tlm_generic_payload::tlm_generic_payload::set_data_ptr (unsigned char * data)\fC [inline]\fP"
.PP
Definition at line 419 of file tlm_generic_payload.h.
.SS "void tlm_generic_payload::tlm_generic_payload::set_response_status (const \fBtlm_response_status\fP response_status)\fC [inline]\fP"
.PP
Definition at line 421 of file tlm_generic_payload.h.
.SS "void tlm_generic_payload::tlm_generic_payload::set_lock (const bool lock)\fC [inline]\fP"
.PP
Definition at line 423 of file tlm_generic_payload.h.
.SS "template<typename T> void tlm_generic_payload::tlm_generic_payload::set_extension (T * ext)\fC [inline]\fP"
.PP
Definition at line 508 of file tlm_generic_payload.h.
.SS "void tlm_generic_payload::tlm_generic_payload::set_extension (unsigned int index, \fBtlm_extension_base\fP * ext)\fC [inline]\fP"
.PP
Definition at line 514 of file tlm_generic_payload.h.
.SS "template<typename T> void tlm_generic_payload::tlm_generic_payload::get_extension (T *& ext)\fC [inline]\fP"
.PP
Definition at line 521 of file tlm_generic_payload.h.
.SS "\fBtlm_extension_base\fP* tlm_generic_payload::tlm_generic_payload::get_extension (unsigned int index)\fC [inline]\fP"
.PP
Definition at line 526 of file tlm_generic_payload.h.
.SS "template<typename T> void tlm_generic_payload::tlm_generic_payload::clear_extension (const T * ext)\fC [inline]\fP"
.PP
Definition at line 532 of file tlm_generic_payload.h.
.SS "void tlm_generic_payload::tlm_generic_payload::clear_extension (unsigned int index)\fC [inline]\fP"
.PP
Definition at line 538 of file tlm_generic_payload.h.
.SS "void tlm_generic_payload::tlm_generic_payload::resize_extensions ()\fC [inline]\fP"
.PP
Definition at line 551 of file tlm_generic_payload.h.
.SH "Member Data Documentation"
.PP 
.SS "\fBtlm_command\fP \fBtlm_generic_payload::tlm_generic_payload::m_command\fP"
.PP
Definition at line 457 of file tlm_generic_payload.h.
.SS "sc_dt::uint64 \fBtlm_generic_payload::tlm_generic_payload::m_address\fP"
.PP
Definition at line 458 of file tlm_generic_payload.h.
.SS "unsigned char* \fBtlm_generic_payload::tlm_generic_payload::m_data\fP"
.PP
Definition at line 459 of file tlm_generic_payload.h.
.SS "unsigned int \fBtlm_generic_payload::tlm_generic_payload::m_burst_length\fP"
.PP
Definition at line 460 of file tlm_generic_payload.h.
.SS "unsigned int \fBtlm_generic_payload::tlm_generic_payload::m_burst_data_size\fP"
.PP
Definition at line 461 of file tlm_generic_payload.h.
.SS "\fBtlm_burst_mode\fP \fBtlm_generic_payload::tlm_generic_payload::m_burst_mode\fP"
.PP
Definition at line 462 of file tlm_generic_payload.h.
.SS "\fBtlm_response_status\fP \fBtlm_generic_payload::tlm_generic_payload::m_response_status\fP"
.PP
Definition at line 463 of file tlm_generic_payload.h.
.SS "bool \fBtlm_generic_payload::tlm_generic_payload::m_lock\fP"
.PP
Definition at line 464 of file tlm_generic_payload.h.
.SS "\fBtlm_array\fP<\fBtlm_extension_base\fP*> \fBtlm_generic_payload::tlm_generic_payload::m_extensions\fP\fC [protected]\fP"
.PP
Definition at line 557 of file tlm_generic_payload.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
