.TH "tlm_peek_if" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_peek_if \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_core_ifs.h>\fP
.PP
Inherits \fBtlm_blocking_peek_if< T >< T >\fP, and \fBtlm_nonblocking_peek_if< T >< T >\fP.
.PP
Inherited by \fBtlm_get_peek_if< T >\fP\fC [virtual]\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename T> class tlm_peek_if< T >"

.PP
Definition at line 120 of file tlm_core_ifs.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
