.TH "tlm_transport_to_master" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_transport_to_master \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_adapters.h>\fP
.PP
Inherits \fBsc_module\fP, and \fBtlm_transport_if< REQ, RSP >< REQ, RSP >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtlm_transport_to_master\fP (sc_module_name nm)"
.br
.ti -1c
.RI "\fBtlm_transport_to_master\fP ()"
.br
.ti -1c
.RI "RSP \fBtransport\fP (const REQ &req)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "sc_export< \fBtlm_transport_if\fP< REQ, RSP > > \fBtarget_export\fP"
.br
.ti -1c
.RI "sc_port< \fBtlm_master_if\fP< REQ, RSP > > \fBmaster_port\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "sc_mutex \fBmutex\fP"
.br
.ti -1c
.RI "RSP \fBrsp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename REQ, typename RSP> class tlm_transport_to_master< REQ, RSP >"

.PP
Definition at line 8 of file tlm_adapters.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename REQ, typename RSP> \fBtlm_transport_to_master\fP< REQ, RSP >::\fBtlm_transport_to_master\fP (sc_module_name nm)\fC [inline]\fP"
.PP
Definition at line 16 of file tlm_adapters.h.
.PP
References tlm_transport_to_master< REQ, RSP >::target_export.
.SS "template<typename REQ, typename RSP> \fBtlm_transport_to_master\fP< REQ, RSP >::\fBtlm_transport_to_master\fP ()\fC [inline]\fP"
.PP
Definition at line 23 of file tlm_adapters.h.
.PP
References tlm_transport_to_master< REQ, RSP >::target_export.
.SH "Member Function Documentation"
.PP 
.SS "template<typename REQ, typename RSP> RSP \fBtlm_transport_to_master\fP< REQ, RSP >::transport (const REQ & req)\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_transport_if< REQ, RSP >\fP.
.PP
Definition at line 30 of file tlm_adapters.h.
.PP
References tlm_transport_to_master< REQ, RSP >::master_port, tlm_transport_to_master< REQ, RSP >::mutex, and tlm_transport_to_master< REQ, RSP >::rsp.
.SH "Member Data Documentation"
.PP 
.SS "template<typename REQ, typename RSP> sc_export< \fBtlm_transport_if\fP< REQ , RSP > > \fBtlm_transport_to_master\fP< REQ, RSP >::\fBtarget_export\fP"
.PP
Definition at line 13 of file tlm_adapters.h.
.PP
Referenced by tlm_transport_to_master< REQ, RSP >::tlm_transport_to_master().
.SS "template<typename REQ, typename RSP> sc_port< \fBtlm_master_if\fP< REQ , RSP > > \fBtlm_transport_to_master\fP< REQ, RSP >::\fBmaster_port\fP"
.PP
Definition at line 14 of file tlm_adapters.h.
.PP
Referenced by tlm_transport_to_master< REQ, RSP >::transport().
.SS "template<typename REQ, typename RSP> sc_mutex \fBtlm_transport_to_master\fP< REQ, RSP >::\fBmutex\fP\fC [private]\fP"
.PP
Definition at line 43 of file tlm_adapters.h.
.PP
Referenced by tlm_transport_to_master< REQ, RSP >::transport().
.SS "template<typename REQ, typename RSP> RSP \fBtlm_transport_to_master\fP< REQ, RSP >::\fBrsp\fP\fC [private]\fP"
.PP
Definition at line 44 of file tlm_adapters.h.
.PP
Referenced by tlm_transport_to_master< REQ, RSP >::transport().

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
