.TH "tlm_core::tlm_nonblocking_peek_port" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_core::tlm_nonblocking_peek_port \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_core.h>\fP
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBtlm_nonblocking_peek_if\fP< T > \fBpeek_if_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtlm_nonblocking_peek_port\fP (const char *port_name)"
.br
.ti -1c
.RI "sc_event_finder & \fBok_to_peek\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T> class tlm_core::tlm_nonblocking_peek_port< T >"

.PP
Definition at line 451 of file tlm_core.h.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T> typedef \fBtlm_nonblocking_peek_if\fP<T> \fBtlm_core::tlm_nonblocking_peek_port\fP< T >::\fBpeek_if_type\fP"
.PP
Definition at line 455 of file tlm_core.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> \fBtlm_core::tlm_nonblocking_peek_port\fP< T >::\fBtlm_nonblocking_peek_port\fP (const char * port_name)\fC [inline]\fP"
.PP
Definition at line 457 of file tlm_core.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T> sc_event_finder& \fBtlm_core::tlm_nonblocking_peek_port\fP< T >::ok_to_peek () const\fC [inline]\fP"
.PP
Definition at line 460 of file tlm_core.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
