.TH "tlm_fifo_get_if" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_fifo_get_if \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_fifo_ifs.h>\fP
.PP
Inherits \fBtlm_get_peek_if< T >< T >\fP, and \fBtlm_fifo_debug_if< T >< T >\fP.
.PP
Inherited by \fBtlm_fifo< T >\fP\fC [virtual]\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<typename T> class tlm_fifo_get_if< T >"

.PP
Definition at line 64 of file tlm_fifo_ifs.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
