.TH "tlm_annotated_put_get_imp" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_annotated_put_get_imp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <tlm_annotated_put_get_imp.h>\fP
.PP
Inherits \fBtlm_annotated_put_if< PUT_DATA >\fP, \fBtlm_annotated_get_peek_if< GET_DATA >\fP, and \fBtlm_put_get_imp< PUT_DATA, GET_DATA >< PUT_DATA, GET_DATA >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtlm_annotated_put_get_imp\fP (\fBtlm_annotated_put_if\fP< PUT_DATA > &put_if, \fBtlm_annotated_get_peek_if\fP< GET_DATA > &get_peek_if)"
.br
.ti -1c
.RI "bool \fBnb_put\fP (const PUT_DATA &t, const sc_time &time)"
.br
.ti -1c
.RI "bool \fBnb_can_put\fP (const sc_time &time, \fBtlm_tag\fP< PUT_DATA > *t=0) const "
.br
.ti -1c
.RI "bool \fBnb_get\fP (GET_DATA &t, const sc_time &time)"
.br
.ti -1c
.RI "bool \fBnb_can_get\fP (const sc_time &time, \fBtlm_tag\fP< GET_DATA > *t=0) const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBtlm_annotated_nonblocking_put_if\fP< PUT_DATA > & \fBdelayed_put_if\fP"
.br
.ti -1c
.RI "\fBtlm_annotated_nonblocking_get_if\fP< GET_DATA > & \fBdelayed_get_if\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename PUT_DATA, typename GET_DATA> class tlm_annotated_put_get_imp< PUT_DATA, GET_DATA >"

.PP
Definition at line 32 of file tlm_annotated_put_get_imp.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename PUT_DATA, typename GET_DATA> \fBtlm_annotated_put_get_imp\fP< PUT_DATA, GET_DATA >::\fBtlm_annotated_put_get_imp\fP (\fBtlm_annotated_put_if\fP< PUT_DATA > & put_if, \fBtlm_annotated_get_peek_if\fP< GET_DATA > & get_peek_if)\fC [inline]\fP"
.PP
Definition at line 38 of file tlm_annotated_put_get_imp.h.
.SH "Member Function Documentation"
.PP 
.SS "template<typename PUT_DATA, typename GET_DATA> bool \fBtlm_annotated_put_get_imp\fP< PUT_DATA, GET_DATA >::nb_put (const PUT_DATA & t, const sc_time & time)\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_annotated_nonblocking_put_if< PUT_DATA >\fP.
.PP
Definition at line 43 of file tlm_annotated_put_get_imp.h.
.SS "template<typename PUT_DATA, typename GET_DATA> bool \fBtlm_annotated_put_get_imp\fP< PUT_DATA, GET_DATA >::nb_can_put (const sc_time & time, \fBtlm_tag\fP< PUT_DATA > * t = \fC0\fP) const\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_annotated_nonblocking_put_if< PUT_DATA >\fP.
.PP
Definition at line 47 of file tlm_annotated_put_get_imp.h.
.SS "template<typename PUT_DATA, typename GET_DATA> bool \fBtlm_annotated_put_get_imp\fP< PUT_DATA, GET_DATA >::nb_get (GET_DATA & t, const sc_time & time)\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_annotated_nonblocking_get_if< GET_DATA >\fP.
.PP
Definition at line 51 of file tlm_annotated_put_get_imp.h.
.SS "template<typename PUT_DATA, typename GET_DATA> bool \fBtlm_annotated_put_get_imp\fP< PUT_DATA, GET_DATA >::nb_can_get (const sc_time & time, \fBtlm_tag\fP< GET_DATA > * t = \fC0\fP) const\fC [inline, virtual]\fP"
.PP
Implements \fBtlm_annotated_nonblocking_get_if< GET_DATA >\fP.
.PP
Definition at line 55 of file tlm_annotated_put_get_imp.h.
.SH "Member Data Documentation"
.PP 
.SS "template<typename PUT_DATA, typename GET_DATA> \fBtlm_annotated_nonblocking_put_if\fP< PUT_DATA >& \fBtlm_annotated_put_get_imp\fP< PUT_DATA, GET_DATA >::\fBdelayed_put_if\fP\fC [private]\fP"
.PP
Definition at line 61 of file tlm_annotated_put_get_imp.h.
.PP
Referenced by tlm_annotated_put_get_imp< RSP, REQ >::nb_can_put(), and tlm_annotated_put_get_imp< RSP, REQ >::nb_put().
.SS "template<typename PUT_DATA, typename GET_DATA> \fBtlm_annotated_nonblocking_get_if\fP<GET_DATA>& \fBtlm_annotated_put_get_imp\fP< PUT_DATA, GET_DATA >::\fBdelayed_get_if\fP\fC [private]\fP"
.PP
Definition at line 62 of file tlm_annotated_put_get_imp.h.
.PP
Referenced by tlm_annotated_put_get_imp< RSP, REQ >::nb_can_get(), and tlm_annotated_put_get_imp< RSP, REQ >::nb_get().

.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
