.TH "C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_annotated/tlm_annotated.h" 3 "17 Oct 2007" "Version 1" "TLM 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/ESLX/projects/TLMWG/tlm2/include/tlm_h/tlm_annotated/tlm_annotated.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include <deque>\fP
.br
\fC#include 'tlm_annotated_ifs/tlm_annotated_ifs.h'\fP
.br
\fC#include 'tlm_annotated_ifs/tlm_annotated_master_slave_ifs.h'\fP
.br
\fC#include 'tlm_annotated_ifs/tlm_nonblocking_transport_if.h'\fP
.br
\fC#include 'tlm_annotated_channels/tlm_peq.h'\fP
.br
\fC#include 'tlm_annotated_channels/tlm_annotated_fifo.h'\fP
.br
\fC#include 'tlm_annotated_channels/tlm_annotated_req_rsp.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtlm_annotated\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtlm_annotated::tlm_delayed_transport_if< REQ, RSP >\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated::tlm_annotated_transport_if< REQ, RSP >\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated::tlm_annotated_nonblocking_get_if< T >\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated::tlm_annotated_nonblocking_put_if< T >\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated::tlm_annotated_get_if< T >\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated::tlm_annotated_put_if< T >\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated::tlm_annotated_nonblocking_get_peek_if< T >\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated::tlm_annotated_get_peek_if< T >\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated::tlm_annotated_nonblocking_master_if< REQ, RSP >\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated::tlm_annotated_nonblocking_slave_if< REQ, RSP >\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated::tlm_annotated_master_if< REQ, RSP >\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated::tlm_annotated_slave_if< REQ, RSP >\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated::tlm_nonblocking_transport_if< TRANS >\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated::tlm_peq< T >\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated::tlm_internal_annotated_fifo< T >\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated::tlm_annotated_fifo< T >\fP"
.br
.ti -1c
.RI "class \fBtlm_annotated::tlm_annotated_req_rsp_channel< REQ, RSP, REQ_CHANNEL, RSP_CHANNEL >\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBtlm_annotated::tlm_phase\fP { \fBtlm_annotated::BEGIN_REQ\fP, \fBtlm_annotated::END_REQ\fP, \fBtlm_annotated::BEGIN_RESP\fP, \fBtlm_annotated::END_RESP\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TLM 2 from the source code.
