SYSTEMC_HOME ?= ../../../..
include ../../../build-unix/Makefile.config

PROJECT = specialized_signals
SRCS    = $(wildcard *.cpp)
OBJS    = $(SRCS:.cpp=.o)

include ../../../build-unix/Makefile.rules
