# Should be set in the environment:
# TARGET_ARCH      = linux
# SYSTEMC_HOME = /usr/users/aernoudt/2/local/systemc-2.2
# TLM_HOME = /usr/users/aernoudt/projects/tlm2.0/eslx/svn

SYSTEMC_INC_DIR  = $(SYSTEMC_HOME)/include
SYSTEMC_LIB_DIR  = $(SYSTEMC_HOME)/lib-$(TARGET_ARCH)
TLM_INC_DIR      = $(TLM_HOME)/include

GXX = g++
GCC = gcc
LD  = g++
FLAGS = -g -Wall

