# Should be set in the environment:
# TARGET_ARCH      = linux
# SYSTEMC_HOME = /usr/users/aernoudt/2/local/systemc-2.2
# TLM_HOME = /usr/users/aernoudt/projects/tlm2.0/eslx/svn

SYSTEMC_INC_DIR  = $(SYSTEMC_HOME)/include
SYSTEMC_LIB_DIR  = $(SYSTEMC_HOME)/lib-$(TARGET_ARCH)
TLM_INC_DIR      = $(TLM_HOME)/include
TLM_UTIL_INC_DIR = $(TLM_HOME)/utilities

GXX = g++
GCC = gcc
LD  = g++
#FLAGS = -g -Wall -Werror -pedantic -Wno-long-long -DSC_INCLUDE_DYNAMIC_PROCESSES -I$(SYSTEMC_INC_DIR) -I$(TLM_INC_DIR) -I$(TLM_UTIL_INC_DIR)
# removed -Werror for SystemC-2.1v1 and boost and gcc-3.4.4
FLAGS = -g -Wall -pedantic -Wno-long-long -DSC_INCLUDE_DYNAMIC_PROCESSES -I$(SYSTEMC_INC_DIR) -I$(TLM_INC_DIR) -I$(TLM_UTIL_INC_DIR)
LDFLAGS = -L$(SYSTEMC_LIB_DIR) -lsystemc
#VALGRIND = valgrind --log-file-exactly=valgrind.log

