
# Cygwin WINDOWS build:
ifeq ($(shell uname -o), Cygwin)

CC = cl.exe
LD = link.exe /SUBSYSTEM:CONSOLE /nologo
OPT    = /O2
DEBUG  = /Od /ZI
FLAGS  = $(DEBUG) /GR /vmg /MD /EHsc /nologo /I"$(TLM_HOME)/include" /I"$(SYSTEMC_HOME)/src"

LDFLAGS = /debug /LIBPATH:"$(SYSTEMC_HOME)/msvc71/SystemC/Release" systemc.lib

#other g++ platforms
else

SYSTEMC_INC_DIR  = $(SYSTEMC_HOME)/include
SYSTEMC_LIB_DIR  = $(SYSTEMC_HOME)/lib-$(TARGET_ARCH)
TLM_INC_DIR      = $(TLM_HOME)/include

GXX = g++
GCC = gcc
LD  = g++
FLAGS = -g -Wall -I$(SYSTEMC_INC_DIR) -I$(TLM_INC_DIR)

endif

