# MSVC WINDOWS build: Visual C++ 2005 .Net Express Edition

# Perhaps better to set these as environment variables
SYSTEMC = C:\apps\systemc-2.2.0\msvc80
TLM = C:\apps\tlmwg\include

CC = cl.exe
LD = link.exe /SUBSYSTEM:CONSOLE /nologo
OPT    = /O2
DEBUG  = /Od /ZI -D_CRT_SECURE_NO_DEPRECATE

FLAGS  = $(DEBUG) /GR /vmg /MTd /EHsc /nologo /W3 /WX \
         /I"C:\Program Files\Microsoft Visual Studio 8\VC\INCLUDE" \
         /I"C:\Program Files\Microsoft Platform SDK\Include" \
         /I"$(TLM)" \
         /I"$(SYSTEMC)\..\src"

MAKE = nmake /NOLOGO

LDFLAGS = /debug /NODEFAULTLIB:libcmt \
          /LIBPATH:"$(SYSTEMC)\SystemC\Debug" \
          /LIBPATH:"C:\Program Files\Microsoft Platform SDK\Lib" \
          systemc.lib kernel32.lib
