!include <..\..\..\build-msvc\Makefile.config>

PROJECT = lt_extension_mandatory

OBJS = \
	$(OUTDIR)\$(PROJECT).obj \
	$(OUTDIR)\$(PROJECT)_top.obj \
	$(OUTDIR)\lt_initiator_extension_mandatory.obj \
	$(OUTDIR)\lt_target_extension_mandatory.obj \
	\
	$(OUTDIR)\extension_initiator_id.obj \
	$(OUTDIR)\report.obj

!include <..\..\..\build-msvc\Makefile.rules>
