# MSVC WINDOWS build:

# Perhaps better to set these as environment variables
SYSTEMC = C:\apps\systemc-2.2.0\msvc80
TLM = C:\apps\TLM-2007-11-09\include

# The following path is for Visual C++ 2005. It should be changed
# for other versions of Visual C++
VCVARS = "C:\Program Files\Microsoft Visual Studio 8\Common7\Tools\vcvars32.bat"

CC = cl.exe
LD = link.exe /SUBSYSTEM:CONSOLE /nologo
OPT    = /O2
DEBUG  = /Od /ZI -D_CRT_SECURE_NO_DEPRECATE

# Adjust the following includes according to your version of Visual C++
FLAGS  = $(DEBUG) /GR /vmg /MTd /EHsc /nologo /W3 /WX \
         /I"C:\Program Files\Microsoft Visual Studio 8\VC\INCLUDE" \
         /I"C:\Program Files\Microsoft Platform SDK\Include" \
         /I"C:\Program Files\Microsoft Visual Studio .NET 2003\SDK\v1.1\include" \
         /I"$(TLM)" \
         /I"$(SYSTEMC)\..\src"

MAKE = nmake /NOLOGO

LDFLAGS = /debug /NODEFAULTLIB:libcmt \
          /LIBPATH:"$(SYSTEMC)\SystemC\Debug" \
          /LIBPATH:"C:\Program Files\Microsoft Platform SDK\Lib" \
          systemc.lib kernel32.lib
