# MSVC WINDOWS build:

MAKE = nmake /NOLOGO

# set, if you want to build the MSVC project files with VCBUILD
#VCBUILD = VCBUILD.exe
VCBUILDFLAGS = /nologo

# use INCLUDE, LIBS, LIBPATH, PATH from environment
#VCBUILDFLAGS = $(VCBUILDFLAGS) /useenv

# Project file extension
# (changed to .vcxproj in recent versions of VC++)
PROJEXT=.vcproj
#PROJECT=.vcxproj

# use CONFIG=Both, to build Debug and Release together
CONFIG=Debug

# Win32 and x64 are configured in the projects
PLATFORM=Win32

# underlying command-line tools
CXX = CL.exe   /nologo
LD  = LINK.exe /nologo

CXXFLAGS=$(CXXFLAGS_COMMON) $(CXXFLAGS_WARN) \
         $(CXXFLAGS_DEFINES) $(CXXFLAGS_INCLUDE)
LDFLAGS =/SUBSYSTEM:CONSOLE /LIBPATH:$(SYSTEMC_LIB_DIR)

CXXFLAGS_COMMON=/GR /vmg /EHsc /Zm800
CXXFLAGS_WARN=/W3 /WX \
              /wd4100 /wd4121 /wd4127 /wd4267 /wd4505 /wd4512 /wd4996

CXXFLAGS_DEFINES=\
  /D_CONSOLE \
  /DSC_INCLUDE_DYNAMIC_PROCESSES

CXXFLAGS_INCLUDE=\
  /I..\include \
  /I..\..\common\include \
  /I$(SYSTEMC_INC_DIR)

CXXFLAGS_RELEASE=/MT /O2 /DNDEBUG
LDFLAGS_RELEASE=

CXXFLAGS_DEBUG=/MTd /D_DEBUG /Zi /Fd"$(OUTDIR)/$(PROJECT).pdb"
LDFLAGS_DEBUG =/DEBUG /PDB:"$(OUTDIR)/$(PROJECT).pdb"

SRCDIR      =..\src
SRCDIRCOMMON=..\..\common\src

# defaults to environment variables if found
!IFNDEF SYSTEMC
SYSTEMC = $(SYSTEMC_HOME)\msvc80
!ENDIF
SYSTEMC_INC_DIR=$(SYSTEMC)\..\src
SYSTEMC_LIB_DIR=$(SYSTEMC)\SystemC\$(OUTDIR)

