# MSVC WINDOWS build:

# Perhaps better to set these as environment variables
SYSTEMC = C:\SystemC\systemc-2.2.0_osci\msvc80
TLM = C:\TLM_WG\include\tlm

CC = cl.exe
LD = link.exe /SUBSYSTEM:CONSOLE /nologo
OPT    = /O2
DEBUG  = /Od /ZI -D_CRT_SECURE_NO_DEPRECATE

# Adjust the following includes according to your version of Visual C++
FLAGS  = $(DEBUG) /GR /vmg /MTd /EHsc /nologo /W3 /WX /DSC_INCLUDE_DYNAMIC_PROCESSES\
         /I"C:\Program Files\Microsoft Visual Studio 8\VC\INCLUDE" \
         /I"C:\Program Files\Microsoft Visual Studio 8\VC\PlatformSDK\Include" \
         /I"C:\Program Files\Microsoft Platform SDK\Include" \
         /I"$(TLM)" \
         /I"$(SYSTEMC)\..\src"

MAKE = nmake /NOLOGO

LDFLAGS = /debug \
          /LIBPATH:"$(SYSTEMC)\SystemC\Debug" \
          /LIBPATH:"C:\Program Files\Microsoft Platform SDK\Lib" \
          systemc.lib kernel32.lib
