SUBDIRS := $(dir $(wildcard */Makefile */*/Makefile))

TARGETS := all build run check clean
.PHONY: $(TARGETS)

$(TARGETS): %:
	@set -e ; for i in $(SUBDIRS); do \
		$(MAKE) -C $$i FLAG_BATCH=1 $@ ; \
	done
