!include <..\..\..\build-msvc\Makefile.config>

PROJECT = lt_dmi

OBJS = \
	$(OUTDIR)\$(PROJECT).obj \
	$(OUTDIR)\$(PROJECT)_top.obj \
	$(OUTDIR)\initiator_top.obj \
	\
	$(OUTDIR)\dmi_memory.obj \
	$(OUTDIR)\lt_dmi_initiator.obj \
	$(OUTDIR)\lt_dmi_target.obj \
	$(OUTDIR)\memory.obj \
	$(OUTDIR)\report.obj \
	$(OUTDIR)\traffic_generator.obj

!include <..\..\..\build-msvc\Makefile.rules>
