// This file was generated by Claude Code (Sonnet 4.6 low and medium effort).

#include "tests.h"

using namespace testing;
using namespace sc_core;

// Helper: waits on an event indefinitely, tracking how many times it has woken
// and at what simulation time it last woke.
struct watcher_module : public sc_module {
    sc_event& watched;
    sc_time woke_at;
    int wake_count = 0;

    watcher_module(sc_module_name n, sc_event& e)
        : sc_module(n)
        , watched(e)
    {
        SC_THREAD(do_watch);
    }

    void do_watch()
    {
        for (;;) {
            wait(watched);
            woke_at = sc_time_stamp();
            wake_count++;
        }
    }
};

// ---- immediate notification ----

struct immediate_notify_module : public sc_module {
    sc_event e;
    watcher_module w;

    SC_CTOR(immediate_notify_module)
        : e("e")
        , w("w", e)
    {
        SC_THREAD(do_test);
    }

    void do_test()
    {
        wait(SC_ZERO_TIME); // let watcher reach its wait()

        // "A call to member function notify with an empty argument list shall
        // create an immediate notification. Any and all process instances
        // sensitive to the event shall be made runnable before control is
        // returned from function notify, with the exception of the currently
        // executing process instance, which shall not be made runnable due to
        // an immediate notification regardless of its static or dynamic
        // sensitivity" (§5.10.6)
        e.notify();
        // We have not suspended, so watcher cannot have run yet.
        // (NOTE 1: "Process instances sensitive to the event will not be
        // resumed or triggered until the process that called notify has
        // suspended or returned.")
        EXPECT_EQ(w.wake_count, 0);

        wait(SC_ZERO_TIME); // yield so watcher runs

        // §5.10.6: watcher was sensitive to e and shall have been made
        // runnable, so it must have run by now.
        EXPECT_EQ(w.wake_count, 1);

        // Immediate notification happens at the current simulation time.
        EXPECT_EQ(w.woke_at, sc_time_stamp());
    }
};

class immediate_notify_t : public Test {
public:
    immediate_notify_t()
        : m("m")
    {
    }
    immediate_notify_module m;
};

// ---- cancel cannot undo an immediate notification ----

struct immediate_not_cancellable_module : public sc_module {
    sc_event e;
    watcher_module w;

    SC_CTOR(immediate_not_cancellable_module)
        : e("e")
        , w("w", e)
    {
        SC_THREAD(do_test);
    }

    void do_test()
    {
        wait(SC_ZERO_TIME);

        e.notify(); // immediate — watcher queued as runnable

        // "Immediate notification cannot be cancelled." (§5.10.6 NOTE 6)
        // cancel() must be a no-op here; the watcher should still wake.
        e.cancel();

        wait(SC_ZERO_TIME);

        EXPECT_EQ(w.wake_count, 1);
    }
};

class immediate_not_cancellable_t : public Test {
public:
    immediate_not_cancellable_t()
        : m("m")
    {
    }
    immediate_not_cancellable_module m;
};

// ---- all processes sensitive to the event wake on immediate notify ----

struct multi_watcher_module : public sc_module {
    sc_event e;
    watcher_module w1;
    watcher_module w2;

    SC_CTOR(multi_watcher_module)
        : e("e")
        , w1("w1", e)
        , w2("w2", e)
    {
        SC_THREAD(do_test);
    }

    void do_test()
    {
        wait(SC_ZERO_TIME);

        // "Any and all process instances sensitive to the event shall be made
        // runnable before control is returned from function notify" (§5.10.6)
        e.notify();

        wait(SC_ZERO_TIME);

        EXPECT_EQ(w1.wake_count, 1);
        EXPECT_EQ(w2.wake_count, 1);
    }
};

class multi_watcher_t : public Test {
public:
    multi_watcher_t()
        : m("m")
    {
    }
    multi_watcher_module m;
};

// ---- delta notification ----

struct delta_notify_module : public sc_module {
    sc_event e;
    watcher_module w;

    SC_CTOR(delta_notify_module)
        : e("e")
        , w("w", e)
    {
        SC_THREAD(do_test);
    }

    void do_test()
    {
        wait(SC_ZERO_TIME); // let watcher reach its wait()

        sc_time t0 = sc_time_stamp();

        // "A call to member function notify with an argument that represents
        // a zero time shall create a delta notification." (§5.10.6)
        e.notify(SC_ZERO_TIME);

        // Watcher should not have run yet (we have not suspended).
        EXPECT_EQ(w.wake_count, 0);

        wait(SC_ZERO_TIME);
        wait(SC_ZERO_TIME);

        // §5.10.6 NOTE 4: processes sensitive to a delta notification are
        // made runnable in the subsequent evaluation phase, so the watcher
        // should have run now.
        EXPECT_EQ(w.wake_count, 1);

        // Delta notification does not advance simulation time.
        EXPECT_EQ(w.woke_at, t0);
    }
};

class delta_notify_t : public Test {
public:
    delta_notify_t()
        : m("m")
    {
    }
    delta_notify_module m;
};

// ---- cancel suppresses a pending delta notification ----

struct cancel_delta_module : public sc_module {
    sc_event e;
    watcher_module w;

    SC_CTOR(cancel_delta_module)
        : e("e")
        , w("w", e)
    {
        SC_THREAD(do_test);
    }

    void do_test()
    {
        wait(SC_ZERO_TIME);

        e.notify(SC_ZERO_TIME);

        // "Member function cancel shall delete any pending notification for
        // this event." (§5.10.6) A delta notification is a pending
        // notification and must be deleted by cancel().
        e.cancel();

        wait(SC_ZERO_TIME);
        wait(SC_ZERO_TIME);

        EXPECT_EQ(w.wake_count, 0);
    }
};

class cancel_delta_t : public Test {
public:
    cancel_delta_t()
        : m("m")
    {
    }
    cancel_delta_module m;
};

// ---- timed notification ----

struct timed_notify_module : public sc_module {
    sc_event e;
    watcher_module w;

    SC_CTOR(timed_notify_module)
        : e("e")
        , w("w", e)
    {
        SC_THREAD(do_test);
    }

    void do_test()
    {
        wait(SC_ZERO_TIME);

        sc_time t0 = sc_time_stamp();
        sc_time delay(10, SC_NS);

        // "A call to function notify with an argument that represents a
        // non-zero time shall create a timed notification at the given time,
        // expressed relative to the simulation time when function notify is
        // called." (§5.10.6)
        e.notify(delay);

        EXPECT_EQ(w.wake_count, 0);

        wait(delay);

        // §5.10.6 NOTE 4: processes sensitive to the event at the time the
        // event occurs will be made runnable at that future simulation time.
        EXPECT_EQ(w.wake_count, 1);
        EXPECT_EQ(w.woke_at, t0 + delay);
    }
};

class timed_notify_t : public Test {
public:
    timed_notify_t()
        : m("m")
    {
    }
    timed_notify_module m;
};

// ---- cancel suppresses a timed notification ----

struct cancel_module : public sc_module {
    sc_event e;
    watcher_module w;

    SC_CTOR(cancel_module)
        : e("e")
        , w("w", e)
    {
        SC_THREAD(do_test);
    }

    void do_test()
    {
        wait(SC_ZERO_TIME);

        e.notify(10, SC_NS);

        // "Member function cancel shall delete any pending notification for
        // this event." (§5.10.6)
        e.cancel();

        wait(20, SC_NS);

        // The notification was cancelled; watcher must not have woken.
        EXPECT_EQ(w.wake_count, 0);
    }
};

class cancel_t : public Test {
public:
    cancel_t()
        : m("m")
    {
    }
    cancel_module m;
};

// ---- cancel on an event with no pending notification is benign ----

struct cancel_no_pending_module : public sc_module {
    sc_event e;
    watcher_module w;

    SC_CTOR(cancel_no_pending_module)
        : e("e")
        , w("w", e)
    {
        SC_THREAD(do_test);
    }

    void do_test()
    {
        wait(SC_ZERO_TIME);

        // cancel() when there is no pending notification must be a no-op.
        // The spec says cancel "shall delete any pending notification" (§5.10.6);
        // with no pending notification there is nothing to delete.
        e.cancel();

        // A subsequent notify must still work normally.
        e.notify(10, SC_NS);

        wait(15, SC_NS);

        EXPECT_EQ(w.wake_count, 1);
    }
};

class cancel_no_pending_t : public Test {
public:
    cancel_no_pending_t()
        : m("m")
    {
    }
    cancel_no_pending_module m;
};

// ---- multiple notifications: at most one pending; earliest wins ----

struct earliest_timed_wins_module : public sc_module {
    sc_event e;
    watcher_module w;

    SC_CTOR(earliest_timed_wins_module)
        : e("e")
        , w("w", e)
    {
        SC_THREAD(do_test);
    }

    void do_test()
    {
        wait(SC_ZERO_TIME);

        // "If function notify is called for an event that already has a
        // notification pending, only the notification scheduled to occur at
        // the earliest time shall survive." (§5.10.9)
        // Schedule a later timed notification first, then an earlier one.
        e.notify(20, SC_NS);
        e.notify(10, SC_NS); // earlier — this one survives

        sc_time t0 = sc_time_stamp();
        wait(25, SC_NS);

        // Watcher should have been triggered exactly once, at 10 ns.
        EXPECT_EQ(w.wake_count, 1);
        EXPECT_EQ(w.woke_at, t0 + sc_time(10, SC_NS));
    }
};

class earliest_timed_wins_t : public Test {
public:
    earliest_timed_wins_t()
        : m("m")
    {
    }
    earliest_timed_wins_module m;
};

// Earlier timed notification wins regardless of which notify() call came first.
struct earlier_wins_regardless_of_order_module : public sc_module {
    sc_event e;
    watcher_module w;

    SC_CTOR(earlier_wins_regardless_of_order_module)
        : e("e")
        , w("w", e)
    {
        SC_THREAD(do_test);
    }

    void do_test()
    {
        wait(SC_ZERO_TIME);

        // "This is irrespective of the order in which function notify is
        // called." (§5.10.9) — schedule the earlier time first.
        e.notify(10, SC_NS);
        e.notify(20, SC_NS); // later — must be ignored

        sc_time t0 = sc_time_stamp();
        wait(25, SC_NS);

        EXPECT_EQ(w.wake_count, 1);
        EXPECT_EQ(w.woke_at, t0 + sc_time(10, SC_NS));
    }
};

class earlier_wins_regardless_of_order_t : public Test {
public:
    earlier_wins_regardless_of_order_t()
        : m("m")
    {
    }
    earlier_wins_regardless_of_order_module m;
};

// Two notifications at the exact same future time: only one wakeup.
struct same_time_fires_once_module : public sc_module {
    sc_event e;
    watcher_module w;

    SC_CTOR(same_time_fires_once_module)
        : e("e")
        , w("w", e)
    {
        SC_THREAD(do_test);
    }

    void do_test()
    {
        wait(SC_ZERO_TIME);

        // "A given event shall have no more than one pending notification."
        // (§5.10.9) When the same time is scheduled twice, the second call
        // does not create a second pending notification.
        e.notify(10, SC_NS);
        e.notify(10, SC_NS);

        wait(15, SC_NS);

        EXPECT_EQ(w.wake_count, 1);
    }
};

class same_time_fires_once_t : public Test {
public:
    same_time_fires_once_t()
        : m("m")
    {
    }
    same_time_fires_once_module m;
};

// ---- immediate supersedes timed (the other half of §5.10.9) ----

struct immediate_beats_timed_module : public sc_module {
    sc_event e;
    watcher_module w;

    SC_CTOR(immediate_beats_timed_module)
        : e("e")
        , w("w", e)
    {
        SC_THREAD(do_test);
    }

    void do_test()
    {
        wait(SC_ZERO_TIME);

        sc_time t0 = sc_time_stamp();

        // "An immediate notification is taken to occur earlier than a delta
        // notification, and a delta notification earlier than a timed
        // notification. This is irrespective of the order in which function
        // notify is called." (§5.10.9)
        e.notify(5, SC_NS); // TIMED pending
        e.notify(); // immediate — must cancel timed, fire now

        EXPECT_EQ(w.wake_count, 0);
        wait(SC_ZERO_TIME);

        // Watcher should have woken at the current time (immediate), not later.
        EXPECT_EQ(w.wake_count, 1);
        EXPECT_EQ(w.woke_at, t0);

        wait(10, SC_NS); // past the 5 ns mark that was cancelled

        // §5.10.9: only one notification survived; no second wakeup at 5 ns.
        EXPECT_EQ(w.wake_count, 1);
    }
};

class immediate_beats_timed_t : public Test {
public:
    immediate_beats_timed_t()
        : m("m")
    {
    }
    immediate_beats_timed_module m;
};

// ---- triggered() semantics ----

// triggered() is true in the evaluation phase of the immediate notification
// and false in the next evaluation phase.
struct triggered_after_immediate_module : public sc_module {
    sc_event e;
    watcher_module w;

    SC_CTOR(triggered_after_immediate_module)
        : e("e")
        , w("w", e)
    {
        SC_THREAD(do_test);
    }

    void do_test()
    {
        wait(SC_ZERO_TIME);

        e.notify();

        // "Member function triggered shall return the value true if and only
        // if the event has been triggered in the immediately preceding delta
        // notification phase or it has been triggered in the current
        // evaluation phase via an immediate notification." (§5.10.5)
        EXPECT_TRUE(e.triggered());

        wait(SC_ZERO_TIME); // enter a new evaluation phase

        // The immediate notification is now in a prior evaluation phase, not
        // the immediately preceding delta notification phase. §5.10.5 "if and
        // only if" means triggered() must now return false.
        EXPECT_FALSE(e.triggered());
    }
};

class triggered_after_immediate_t : public Test {
public:
    triggered_after_immediate_t()
        : m("m")
    {
    }
    triggered_after_immediate_module m;
};

// triggered() is false before the delta fires, true in the immediately
// following evaluation phase, and false in the one after that.
struct triggered_after_delta_module : public sc_module {
    sc_event e;
    watcher_module w;

    SC_CTOR(triggered_after_delta_module)
        : e("e")
        , w("w", e)
    {
        SC_THREAD(do_test);
    }

    void do_test()
    {
        wait(SC_ZERO_TIME);

        e.notify(SC_ZERO_TIME);

        // Delta notification is pending but has not yet fired.
        // §5.10.5: triggered() must be false.
        EXPECT_FALSE(e.triggered());

        wait(SC_ZERO_TIME); // delta fires; both do_test and watcher resume
        wait(SC_ZERO_TIME); // let watcher run if it hasn't yet, then one more delta

        // We are now two evaluation phases past the delta notification.
        // §5.10.5: triggered() must be false (e was not triggered in the
        // "immediately preceding" delta notification phase).
        EXPECT_FALSE(e.triggered());
    }
};

class triggered_after_delta_t : public Test {
public:
    triggered_after_delta_t()
        : m("m")
    {
    }
    triggered_after_delta_module m;
};

// In a wait(e1 | e2), triggered() identifies which event actually fired:
// the firing event returns true, the non-firing event returns false.
struct or_list_triggered_module : public sc_module {
    sc_event e1;
    sc_event e2;

    SC_CTOR(or_list_triggered_module)
        : e1("e1")
        , e2("e2")
    {
        SC_THREAD(do_test);
    }

    void do_test()
    {
        // Schedule e1 to fire in the next delta cycle, then wait for either.
        e1.notify(SC_ZERO_TIME);

        wait(e1 | e2);

        // "Member function triggered shall return the value true if and only
        // if the event has been triggered in the immediately preceding delta
        // notification phase..." (§5.10.5)
        // e1 fired in that phase; e2 did not.
        EXPECT_TRUE(e1.triggered());
        EXPECT_FALSE(e2.triggered());
    }
};

class or_list_triggered_t : public Test {
public:
    or_list_triggered_t()
        : m("m")
    {
    }
    or_list_triggered_module m;
};

struct immediate_beats_delta_module : public sc_module {
    sc_event e;
    watcher_module w;

    SC_CTOR(immediate_beats_delta_module)
        : e("e")
        , w("w", e)
    {
        SC_THREAD(do_test);
    }

    void do_test()
    {
        wait(SC_ZERO_TIME);

        // "An immediate notification is taken to occur earlier than a delta
        // notification, and a delta notification earlier than a timed
        // notification. This is irrespective of the order in which function
        // notify is called." (§5.10.9)
        e.notify(SC_ZERO_TIME); // delta notification pending
        e.notify(); // immediate — replaces delta

        // Having called notify() (immediate), the watcher is made runnable
        // but cannot run until we suspend. Confirm it runs this delta cycle.
        EXPECT_EQ(w.wake_count, 0);
        wait(SC_ZERO_TIME);

        // The watcher woke in the same simulation time (immediate notification).
        EXPECT_EQ(w.wake_count, 1);
        EXPECT_EQ(w.woke_at, sc_time_stamp());
    }
};

class immediate_beats_delta_t : public Test {
public:
    immediate_beats_delta_t()
        : m("m")
    {
    }
    immediate_beats_delta_module m;
};

struct delta_beats_timed_module : public sc_module {
    sc_event e;
    watcher_module w;

    SC_CTOR(delta_beats_timed_module)
        : e("e")
        , w("w", e)
    {
        SC_THREAD(do_test);
    }

    void do_test()
    {
        wait(SC_ZERO_TIME);

        sc_time t0 = sc_time_stamp();

        // "a delta notification [is] earlier than a timed notification"
        // (§5.10.9)
        e.notify(10, SC_NS); // timed notification pending
        e.notify(SC_ZERO_TIME); // delta — replaces timed notification

        wait(SC_ZERO_TIME);
        wait(SC_ZERO_TIME);

        // Watcher should have woken at the current time (delta), not at 10 ns.
        EXPECT_EQ(w.wake_count, 1);
        EXPECT_EQ(w.woke_at, t0);

        wait(15, SC_NS); // confirm no second wakeup at 10 ns

        // §5.10.9: only one notification survives; no second wakeup.
        EXPECT_EQ(w.wake_count, 1);
    }
};

class delta_beats_timed_t : public Test {
public:
    delta_beats_timed_t()
        : m("m")
    {
    }
    delta_beats_timed_module m;
};

TEST_F(immediate_notify_t, sc_event_notify_watcher_wakes)
{
    sc_start();
}

TEST_F(immediate_not_cancellable_t, sc_event_notify_immediate_not_cancellable)
{
    sc_start();
}

TEST_F(multi_watcher_t, sc_event_notify_all_watchers_wake)
{
    sc_start();
}

TEST_F(delta_notify_t, sc_event_notify_watcher_wakes_in_delta)
{
    sc_start();
}

TEST_F(cancel_delta_t, sc_event_notify_cancel_suppresses_delta)
{
    sc_start();
}

TEST_F(timed_notify_t, sc_event_notify_watcher_wakes_at_future_time)
{
    sc_start();
}

TEST_F(cancel_t, sc_event_notify_cancel_prevents_wakeup)
{
    sc_start();
}

TEST_F(cancel_no_pending_t, sc_event_notify_cancel_no_pending_is_benign)
{
    sc_start();
}

TEST_F(earliest_timed_wins_t, sc_event_notify_earliest_timed_notification_wins)
{
    sc_start();
}

TEST_F(earlier_wins_regardless_of_order_t, sc_event_notify_earlier_wins_regardless_of_order)
{
    sc_start();
}

TEST_F(same_time_fires_once_t, sc_event_notify_same_time_fires_once)
{
    sc_start();
}

TEST_F(immediate_beats_timed_t, sc_event_notify_immediate_supersedes_timed)
{
    sc_start();
}

TEST_F(triggered_after_immediate_t, sc_event_notify_triggered_after_immediate)
{
    sc_start();
}

TEST_F(triggered_after_delta_t, sc_event_notify_triggered_after_delta)
{
    sc_start();
}

TEST_F(or_list_triggered_t, sc_event_notify_or_list_triggered_identifies_event)
{
    sc_start();
}

TEST_F(immediate_beats_delta_t, sc_event_notify_immediate_supersedes_delta)
{
    sc_start();
}

TEST_F(delta_beats_timed_t, sc_event_notify_delta_supersedes_timed)
{
    sc_start();
}
