# MSVC WINDOWS build:

# Perhaps better to set these as environment variables
SYSTEMC = C:\SystemC\systemc-2.2.0_osci\msvc71
TLM = C:\TLM_WG\include

CC = cl.exe
LD = link.exe /SUBSYSTEM:CONSOLE /nologo
OPT    = /O2
DEBUG  = /Od /ZI -D_CRT_SECURE_NO_DEPRECATE

# Adjust the following includes according to your version of Visual C++
FLAGS  = $(DEBUG) /GR /vmg /MD /EHsc /nologo /W3 /WX /DSC_INCLUDE_DYNAMIC_PROCESSES \
         /I"C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\include" \
         /I"C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\Include" \
         /I"$(TLM)" \
         /I"$(SYSTEMC)\..\src"

MAKE = nmake /NOLOGO

LDFLAGS = /debug \
          /LIBPATH:"$(SYSTEMC)\SystemC\Debug" \
          /LIBPATH:"C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\Lib" \
          systemc.lib kernel32.lib
