!include <..\..\..\build-msvc\Makefile.config>

PROJECT = lt_temporal_decouple

OBJS = \
	$(OUTDIR)\$(PROJECT).obj \
	$(OUTDIR)\$(PROJECT)_top.obj \
	$(OUTDIR)\initiator_top.obj \
	$(OUTDIR)\td_initiator_top.obj \
	\
	$(OUTDIR)\lt_initiator.obj \
	$(OUTDIR)\lt_synch_target.obj \
	$(OUTDIR)\lt_target.obj \
	$(OUTDIR)\lt_td_initiator.obj \
	$(OUTDIR)\memory.obj \
	$(OUTDIR)\report.obj \
	$(OUTDIR)\traffic_generator.obj

!include <..\..\..\build-msvc\Makefile.rules>
