!include <..\..\..\build-msvc\Makefile.config>

PROJECT = lt

OBJS = \
	$(OUTDIR)\$(PROJECT).obj \
	$(OUTDIR)\$(PROJECT)_top.obj \
	$(OUTDIR)\lt_initiator.obj \
	\
	$(OUTDIR)\at_target_1_phase.obj \
	$(OUTDIR)\lt_target.obj \
	$(OUTDIR)\initiator_top.obj \
	$(OUTDIR)\memory.obj \
	$(OUTDIR)\report.obj \
	$(OUTDIR)\traffic_generator.obj

!include <..\..\..\build-msvc\Makefile.rules>
