# Should be set in the environment:
#TARGET_ARCH      = macosx-i386
#SYSTEMC_HOME	 = /Users/charleswilson/Documents/OSCI/SystemC/2.2-gcc4.0
#TLM_HOME		 = /Users/charleswilson/Documents/ESLX/projects/tlm_2

SYSTEMC_INC_DIR  = $(SYSTEMC_HOME)/include
SYSTEMC_LIB_DIR  = $(SYSTEMC_HOME)/lib-$(TARGET_ARCH)
TLM_INC_DIR      = $(TLM_HOME)/include/tlm

# use null WERROR_FLAG for SystemC-2.1v1 and boost and gcc-3.4.4
WERROR_FLAG = -Werror
#WERROR_FLAG =

GXX = g++
GCC = gcc
LD  = g++

FLAGS = -g -Wall $(WERROR_FLAG) -pedantic -Wno-long-long -DSC_INCLUDE_DYNAMIC_PROCESSES -I$(SYSTEMC_INC_DIR) -I$(TLM_INC_DIR)
LDFLAGS = -L$(SYSTEMC_LIB_DIR) -lsystemc
#VALGRIND = valgrind --log-file-exactly=valgrind.log
