# Should be set in the environment:
TARGET_ARCH     = macosx-i386
SYSTEMC_HOME	= /Users/charleswilson/Documents/SystemC/osci/systemc/2.2-gcc4.0
TLM_HOME		= /Users/charleswilson/Documents/ESLX/projects/tlm_2

SYSTEMC_INC_DIR  = $(SYSTEMC_HOME)/include
SYSTEMC_LIB_DIR  = $(SYSTEMC_HOME)/lib-$(TARGET_ARCH)
TLM_INC_DIR      = $(TLM_HOME)/include

GXX = g++
GCC = gcc
LD  = g++
FLAGS = -g -Wall

